class EntranceName():
    Menu_StartGame = "Menu - Start Game"

    #Indra
    Overworld_To_Daila_NorthSide = "Overworld - Daila North Side"
    Overworld_To_Daila_SouthSide = "Overworld - Daila South Side"
    Overworld_To_ShrineOfTheSeaGod = "Overworld - Shrine Of The Sea God"
    Overworld_To_KandoreanTemple = "Overworld - Kandorean Temple"
    Overworld_To_DehkanPlateau_NorthWestSide = "Overworld - Dehkan Plateau North Western Side"
    Overworld_To_DehkanPlateau_SouthEastSide = "Overworld - Dehkan Plateau South Eastern Side"
    Overworld_To_IndraCavern = "Overworld - Indra Cavern"
    Overworld_To_Madra = "Overworld - Madra"
    Overworld_To_GondowanCliffs_EastSide = "Overworld - Gondowan Cliffs East Side"
    Overworld_To_GondowanCliffs_WestSide = "Overworld - Gondowan Cliffs West Side"
    Overworld_To_MadraDrawbridge_SouthSide = "Overworld - Madra Drawbridge South Side"
    Overworld_To_MadraDrawbridge_NorthSide = "Overworld - Madra Drawbright North Side"
    Idejima_To_Overworld = "Idejima - Western Exit"
    Daila_North_To_Overworld = "Daila - Northern Exit"
    Daila_South_To_Overworld = "Daila - Southern Exit"
    KandoreanTemple_To_Overworld = "Kandorean Temple - Southern Exit"
    ShrineOfTheSeaGod_To_Overworld = "Shrine Of The Sea God - Southern Exit"
    DehkanPlateau_West_To_Overworld = "Dehkan Plateau - North Western Exit"
    DehkanPlateau_East_To_Overworld = "Dehkan Plateau - South Eastern Exit"
    IndraCavern_To_Overworld = "Indra Cavern - Southern Exit"
    Madra_To_Overworld = "Madra - Southern Exit"
    GondowanCliffs_East_To_Overworld = "Gondown Cliffs - Eastern Exit"
    MadraDrawbridge_South_To_Overworld = "Madra Drawbridge - Southern Exit"
    MadraDrawbridge_North_To_Overworld = "Madra Drawbridge - Northern Exit"

    #Osenia
    Overworld_To_OseniaCliffs_WestSide = "Overworld - Osenia Cliffs West Side"
    OseniaCliffs_West_To_Overworld = "Osenia Cliffs - Western Exit"
    Overworld_To_OseniaCliffs_EastSide = "Overworld - Osenia Cliffs East Side"
    OseniaCliffs_East_To_Overworld = "Osenia Cliffs - Eastern Exit"
    Overworld_To_Mikasalla = "Overworld - Mikasalla"
    Mikasalla_To_Overworld = "Mikasalla - Eastern Exit"
    Overworld_To_OseniaCavern = "Overworld - Osenia Cavern"
    OseniaCavern_To_Overworld = "Osenia Cavern - Southern Exit"
    Overworld_To_Garoh = "Overworld - Garoh"
    Garoh_To_Overworld = "Garoh - Southern Exit"
    Overworld_To_AirsRock = "Overworld - Airs Rock"
    AirsRock_To_Overworld = "Airs Rock - Southern Exit"
    Overworld_To_YampiDesertFront = "Overworld - Yampi Desert Front"
    Overworld_Garoh_To_YampiDesertBack = "Overworld (Garoh) - Yampi Desert Back"
    YampiDesertBack_To_Overworld_Garoh = "Yampi Desert Back - Southern Exit"
    YampDesertFront_To_Overworld = "Yampi Desert Front - Western Exit"
    YampiDesertBack_To_Overworld_Alhafra = "Yampi Desert Back - Northern Exit"
    Overworld_To_Alhafra = "Overworld - Alhafra"
    Overworld_Alhafra_To_YampiDesertBack = "Overworld (Alhafra) - Yampi Desert Back"
    Alhafra_To_Overworld = "Alhafra - Southern Exit"

    #Gondowan
    GondowanCliffs_West_To_Overworld = "Gondowan Cliffs - Western Exit"
    Overworld_To_KibomboMountains_SouthSide = "Overworld - Kibombo Mountains South Side"
    Overworld_To_KibomboMountains_NorthSide = "Overworld - Kibombo Mountains North Side"
    Overworld_To_Naribwe_SouthSide = "Overworld - Naribwe SouthSide"
    Overworld_To_Naribwe_NorthSide = "Overworld - Naribwe NorthSide"
    Naribwe_South_To_Overworld = "Naribwe - Southern Exit"
    Naribwe_North_To_Overworld = "Naribwe - Northern Exit"
    KibomboMountains_South_To_Overworld = "Kibombo Mountains - Southern Exit"
    KibomboMountains_NorthWest_To_Overworld = "Kibombo Mountains - Northwestern Exit"
    Overworld_To_Kibombo = "Overworld - Kibombo"
    Kibombo_To_Overworld = "Kibombo - Southern Exit"


    #Eastern Sea
    Overworld_Indra_North_To_EasternSea = "Overworld - Northern Indra To Eastern Sea"
    Overworld_Indra_South_To_EasternSea = "Overworld - Southern Indra To Eastern Sea"
    Overworld_Oseania_AlhafraArea_To_EasternSea = "Overworld - Osenia Alhafra Area To Eastern Sea"
    Overworld_Gondowan_Central_To_EasternSea = "Overworld - Central Gondowan To Eastern Sea"
    Overworld_Gondowan_South_To_EasternSea = "Overworld - Southern Gondowan To Eastern Sea"
    Overworld_WestIndraIslet_To_EasternSea = "Overworld - West Indra Islet To Eastern Sea"
    Overworld_EastTundariaIslet_To_EasternSea = "Overworld - East Tundaria Islet To Eastern Sea"
    Overworld_NorthOseniaIslet_To_EasternSea = "Overworld - North Osenia Islet To Eastern Sea"
    Overworld_SouthEastAngaraIslet_To_EasternSea = "Overworld - South East Angara Islet To Eastern Sea"
    Overworld_SeaOfTimeIslet_To_EasternSea = "Overworld - Sea of Time Islet To Eastern Sea"

    Overworld_EasternSea_To_Indra_North = "Eastern Sea To Northern Indra"
    Overworld_EasternSea_To_Indra_South = "Eastern Sea To Southern Indra"
    Overworld_EasternSea_To_Osenia_AlhafraArea = "Eastern Sea To Osenia Alhafra Area"
    Overworld_EasternSea_To_Gondowan_Central = "Eastern Sea To Central Gondowan"
    Overworld_EasternSea_To_Gondowan_South = "Eastern Sea To Southern Gondowan"
    Overworld_EasternSea_To_WestIndraIslet = "Eastern Sea To West Indra Islet"
    Overworld_EasternSea_To_EastTundariaIslet = "Eastern Sea To East Tundaria Islet"
    Overworld_EasternSea_To_NorthOseniaIslet = "Eastern Sea To North Osenia Islet"
    Overworld_EasternSea_To_SouthEastAngaraIslet = "Eastern Sea To South East Angara Islet"
    Overworld_EasternSea_To_SeaOfTimeIslet = "Eastern Sea To Sea Of Time Islet"

    Overworld_WestIndraIslet_To_WestIndraIslet = "Overworld - West Indra Islet"
    WestIndraIslet_To_Overworld = "West Indra Islet - Southern Exit"
    Overworld_EastTundariaIslet_To_EastTundariaIslet = "Overworld - East Tundaria Islet"
    EastTundariaIslet_To_Overworld = "East Tundaria Islet - Southern Exit"
    Overworld_NorthOseniaIslet_To_NorthOseniaIsletWest = "Overworld - North Osenia Islet West"
    NorthOseniaIsletWest_To_Overworld = "North Osenia Islet - Western Exit"
    Overworld_NorthOseniaIslet_To_NorthOseniaIsletSouth = "Overworld - North Osenia Islet South"
    NorthOseniaIsletSouth_To_Overworld = "North Osenia Islet - Southern Exit"
    Overworld_NorthOseniaIslet_To_NorthOseniaIsletEast = "Overworld - North Osenia Islet East"
    NorthOseniaIsletEast_To_Overworld = "North Osenia Islet - Eastern Exit"
    Overworld_SouthEastAngaraIslet_To_SouthEastAngaraIslet = "Overworld - SouthEast Angara Islet"
    SouthEastAngaraIslet_To_Overworld = "SouthEast Angara Islet - Western Exit"
    Overworld_SeaOfTimeIslet_To_SeaOfTimeIslet = "Overworld - Sea of Time Islet"
    SeaOfTimeIslet_To_Overworld = "Sea of Time Islet - Northern Exit"

    #TODO
    MadraToMadraCatacombs = "Madra To Madra Catacombs"
    MadraToLemurianShip = "Madra To Lemurian Ship"
    YampiDesertFrontToYampiDesertBack = "Yampi Desert Front To Yampi Desert Back"
    YampiDesertBackToYampiDesertCave = "Yampi Desert Back To Yampi Desert Cave"
    AlhafraToAlhafraCave = "Alhafra To Alhafra Cave"
    KibomboToGabombaStatue = "Kibombo To Gabomba Statue"
    GabombaStatueToGabombaCatacombs = "Gabomba Statue To Gabomba Catacombs"

    EasternSeaToSeaOfTime = "Eastern Sea To Sea Of Time"
    EasternSeaToTreasureIsland = "Eastern Sea To Treasure Island"
    EasternSeaToChampa = "Eastern Sea To Champa"
    EasternSeaToAnkohlRuins = "Eastern Sea To Ankohl Ruins"
    EasternSeaToIzumo = "Eastern Sea To Izumo"
    EasternSeaToGaiaRock = "Eastern Sea To Gaia Rock"
    EasternSeaToYallam = "Eastern Sea To Yallam"

    EasternSeaToTundariaTower = "Eastern Sea To Tundaria Tower"
    EasternSeaToApojiiIslands = "Eastern Sea To Apojii Islands"
    EasternSeaToAquaRock = "Eastern Sea To Aqua Rock"
    EasternSeaToWesternSea = "Eastern Sea To Western Sea"

    TreasureIslandToTreasureIsland_Grindstone = "Treasure Island To Treasure Island Post Grindstone"
    TreasureIsland_GrindstoneToTreasureIsland_PostReunion = "Treasure Island Post Grindstone To Treasure Island - PostReunion"
    TundariaTowerToTundariaTower_Parched = "Tundaria Tower To Tundaria Tower - Parched Areas"
    AnkohlRuinsToAnkohlRuins_Sand = "Ankohl Ruins To Ankohl Ruins - Post Sand"
    YallamToTaopoSwamp = "Yallam To Taopo Swamp"
    SeaOfTimeToLemuria = "Sea Of Time To Lemuria"
    LemuriaToShipRevisit = "Lemuria To Ship Revisit"
    WesternSeaToSouthWestAttekaIslet = "Western Sea To South West Atteka Islet"
    WesternSeaToHesperiaSettlement = "Western Sea To Hesperia Settlement"
    WesternSeaToShamanVillageCave = "Western Sea To Shaman Village Cave"
    WesternSeaToAttekaInlet = "Western Sea To Atteka Inlet"
    WesternSeaToAttekaCavern = "Western Sea To Atteka Cavern"
    WesternSeaToGondowanSettlement = "Western Sea To Gondowan Settlement"
    WesternSeaToMagmaRock = "Western Sea To Magma Rock"
    WesternSeaToLoho = "Western Sea To Loho"
    WesternSeaToAngaraCavern = "Western Sea To Angara Cavern"
    WesternSeaToKaltIsland = "Western Sea To Kalt Island"
    WesternSeaToProx = "Western Sea To Prox"
    ShamanVillageCaveToShamanVillage = "Shaman Village Cave To Shaman Village"
    AttekaInletToContigo = "Atteka Inlet To Contigo"
    AttekaInletToShipRevisit = "Atteka Inlet To Ship Revisit"
    ContigoToJupiterLighthouse = "Contigo To Jupiter Lighthouse"
    ContigoToReunion = "Contigo To Reunion"
    ContigoToAnemosInnerSanctum = "Contigo To Anemos Inner Sanctum"
    MagmaRockToMagmaRockInterior = "Magma Rock To Magma Rock Interior"
    ProxToMarsLighthouse = "Prox To Mars Lighthouse"
    MarsLighthouseToMarsLighthouse_Activated = "Mars Lighthouse To Mars Lighthouse - Activated"
    SeaOfTimeIsletToIsletCave = "Sea Of Time Islet To Islet Cave"
    AnywhereToJoinedPartyMembers = "Joined Party Characters"