class EntranceName():
    Menu_StartGame = "Menu - Start Game"

    #Idejima
    Idejima_To_Overworld = "Idejima - Western Exit"

    #Daila
    Daila_North_To_Overworld = "Daila - Northern Exit"
    Daila_South_To_Overworld = "Daila - Southern Exit"
    Overworld_To_Daila_NorthSide = "Overworld - Daila North Side"
    Overworld_To_Daila_SouthSide = "Overworld - Daila South Side"

    #Kandorean Temple
    Overworld_To_KandoreanTemple = "Overworld - Kandorean Temple"
    KandoreanTemple_To_Overworld = "Kandorean Temple Outside - Southern Exit"
    KandoreanTemple_Outside_SideCave = "Kandorean Temple Outside - Side Cavern"
    KandoreanTemple_Outside_Outer_Gates = "Kandorean Temple Outside - Entry Gates"
    KandoreanTemple_WellPath_To_CaveExit = "Kandorean Temple Watery Cave Path - West Staircase"
    KandoreanTemple_WellPath_To_WellRope = "Kandorean Temple Watery Cave Path - Well Rope"
    KandoreanTemple_TempleGrounds_SouthGates = "Kandorean Temple Outside Templegrounds - Entry Gates"
    KandoreanTemple_TempleGrounds_NorthDoor = "Kandorean Temple Outside Templegrounds - Temple Door"
    KandoreanTemple_TempleGrounds_WellRope = "Kandorean Temple Outside Templegrounds - Well Rope"
    KandoreanTemple_Lobby_To_SouthDoor = "Kandorean Temple Lobby - South Door"
    KandoreanTemple_Lobby_LashRope = "Kandorean Temple Lobby - Lash Rope Climb"
    KandoreanTemple_Lobby_To_NorthDoor = "Kandorean Temple Lobby - Challenge Entry Doorway"
    KandoreanTemple_DropDownLedge_Dropdown = "Kandorean Temple Lobby Drop Down Ledge - Drop Down"
    KandoreanTemple_DropDownLedge_Door = "Kandorean Temple Lobby Drop Down Ledge - Doorway"
    KandoreanTemple_LashLedge_Door = "Kandorean Temple Lobby Lash Rope Ledge - Doorway"
    KandoreanTemple_EntryRoom_SouthDoor = "Kandorean Temple Challenge Entry Room - South Door"
    KandoreanTemple_EntryRoom_BackStaircase = "Kandorean Temple Challenge Entry Room - Staircase in Back"
    KandoreanTemple_JumpColumns_CentralStaircase = "Kandorean Temple Jump Columns Room - Central Staircase"
    KandoreanTemple_JumpColumns_ZigZagsDoor = "Kandorean Temple Jump Columns Room - Northwestern Door"
    KandoreanTemple_CliffsEdge_SouthDoor = "Kandorean Temple Cliffs Edge - South Door"
    KandoreanTemple_CliffsEdge_Staircase = "Kandorean Temple Cliffs Edge - West Staircase"
    KandoreanTemple_WaterStream_WestsideStaircase = "Kandorean Temple Waterstream - West Staircase"
    KandoreanTemple_WaterStream_EastsideDoorway = "Kandorean Temple Waterstream - East Doorway"
    KandoreanTemple_GeyserPuzzles_SouthDoor = "Kandorean Temple Geyzer Puzzle Room - South Doorway"
    KandoreanTemple_GeyserPuzzles_WestGeyser = "Kandorean Temple Geyzer Puzzle Room - West Geyser"
    KandoreanTemple_GeyserPuzzles_EastGeyser = "Kandorean Temple Geyzer Puzzle Room - East Geyser"
    KandoreanTemple_TightRopeArea_EastGeyserPlatform = "Kandorean Temple Tightrope Legde - East Geyser"
    KandoreanTemple_TightRopeArea_WestGeyserPlatform = "Kandorean Temple Tightrope Room - West Geyser"
    KandoreanTemple_TightRopeArea_RopeGeyser = "Kandorean Temple Tightrope Room - Rope Fall"
    KandoreanTemple_TightRopeArea_StairsNearRopes = "Kandorean Temple Tightrope Room - Starcase near Ropes"
    KandoreanTemple_TightRopeArea_SouthEastDoor = "Kandorean Temple Tightrope Room - SouthEastern Door"
    KandoreanTemple_GeyzerPuzzleLedge_Staircase = "Kandorean Temple Geyser Puzzle Room Ledge - Staircase"
    KandoreanTemple_DjinnRoom_DoorNearLashRope = "Kandorean Temple Djinn Room - Door near Lash Rope"
    KandoreanTemple_DjinnRoom_SouthStairs = "Kandorean Temple Djinn Room - Southern Stairs"
    KandoreanTemple_StairWell_WestStairs = "Kandorean Temple Stairwell - Western Stairs"
    KandoreanTemple_StairWell_EastStairs = "Kandorean Temple Stairwell - Eastern Stairs"
    KandoreanTemple_PotRoom_SouthStairs = "Kandorean Temple Pot Room - Southern Stairs"
    KandoreanTemple_PotRoom_NorthLadder = "Kandorean Temple Pot Room - Northern Ladder"
    KandoreanTemple_PurpleHallway_NorthLadder = "Kandorean Temple Purple Hallway - Northern Ladder"
    KandoreanTemple_PurpleHallway_SouthDoor = "Kandorean Temple Purple Hallway - Southern Door"
    KandoreanTemple_MastersRoom_NorthWestDoor = "Kandorean Temple Masters Room - NorthWestern Door"
    KandoreanTemple_MastersRoom_SouthWestDoor = "Kandorean Temple Masters Room - SouthWestern Door"
    KandoreanTemple_MastersRoom_SouthEastDoor = "Kandorean Temple Masters Room- SouthEastern Door"

    #Shrine of the Sea God
    Overworld_To_ShrineOfTheSeaGod = "Overworld - Shrine Of The Sea God"
    ShrineOfTheSeaGod_To_Overworld = "Shrine Of The Sea God Entry Lower Half - Southern Exit"
    ShrineOfTheSeaGod_EntryLow_LashRope = "Shrine Of The Sea God Entry Lower Half - Lash Rope"
    ShrineOfTheSeaGod_EntryLow_EastDoor = "Shrine Of The Sea God Entry Lower Half - Eastern Door"
    ShrineOfTheSeaGod_TorchedDeadEnd_WestDoor = "Shrine Of The Sea God Torched Dead End - Western Door"
    ShrineOfTheSeaGod_EntryHigh_WestDoor = "Shrine Of The Sea God Entry Upper Half - Western Door"
    ShrineOfTheSeaGod_EntryHigh_DropDown = "Shrine Of The Sea God Entry Upper Half - Drop Down"
    ShrineOfTheSeaGod_QuadBridgesUpper_EasternDoor = "Shrine Of The Sea God Quad Bridges Upper Ridges - Eastern Door"
    ShrineOfTheSeaGod_QuadBridgesUpper_Stairs = "Shrine Of The Sea God Quad Bridges Upper Ridges - Central Staircase"
    ShrineOfTheSeaGod_QuadBridgesUpper_BridgeDropDown = "Shrine Of The Sea God Quad Bridges Upper Ridges - Bridge Drop Down"
    ShrineOfTheSeaGod_SkippingStonesDeadEnd_Staircase = "Shrine Of The Sea God Water Skipping STones - SouthEastern Stairs"
    ShrineOfTheSeaGod_QuadBridgesDroppedArea_DropDown = "Shrine Of The Sea God Quad Bridges Dropped Area - Drop Down"
    ShrineOfTheSeaGod_QuadBridgesDroppedArea_SouthStairs = "Shrine Of The Sea God Quad Bridges Dropped Area - Southern Stairs"
    ShrineOfTheSeaGod_DjinnFootstepsArea_NorthernStairs = "Shrine Of The Sea God Djinn Footstepps Area - Northern Stairs"
    ShrineOfTheSeaGod_DjinnFootstepsArea_WesternStairs = "Shrine Of The Sea God Djinn Footstepps Area - Western Stairs"
    ShrineOfTheSeaGod_DjinnFootstepsArea_EasternStairs = "Shrine Of The Sea God Djinn Footstepps Area - Eastern Stairs"
    ShrineOfTheSeaGod_DjinnFootstepsArea_SouthernStairs = "Shrine Of The Sea God Djinn Footstepps Area - Southern Stairs"
    ShrineOfTheSeaGod_DjinnFleeingBridge_WesternStairs = "Shrine Of The Sea God Djinn Fleeing Bridge - Western Stairs"
    ShrineOfTheSeaGod_DjinnFleeingBridge_EasternStairs = "Shrine Of The Sea God Djinn Fleeing Bridge - Eastern Stairs"
    ShrineOfTheSeaGod_DjinnTorchCorner_SouthernStairs = "Shrine Of The Sea God Djinn Torch Corner - Southern Stairs"
    ShrineOfTheSeaGod_DjinnTorchCorner_FrostJumps = "Shrine Of The Sea God Djinn Torch Corner - Frost Column Jumps"
    ShrineOfTheSeaGod_FrostLedge_NorthernDoor = "Shrine Of The Sea God Frosty Ledge - Northern Door"
    ShrineOfTheSeaGod_OceansView_SouthernDoor = "Shrine Of The Sea God Oceans View - Southern Door"
    ShrineOfTheSeaGod_OceansView_NorthEasternStairs = "Shrine Of The Sea God Oceans View - NorthEastern Stairs"
    ShrineOfTheSeaGod_RushingWaterBridges_WesternStairs = "Shrine Of The Sea God Rushing Water Bridges - Western Stairs"
    ShrineOfTheSeaGod_RushingWaterBridges_BridgeDropDown = "Shrine Of The Sea God Rushing Water Bridges - Brdige Drop Down"
    ShrineOfTheSeaGod_RushingWaterBridgesLash_EasternStairs = "Shrine Of The Sea God Rushing Water Bridges - Eastern Stairs"
    ShrineOfTheSeaGod_RushingWaterBridgesLash_LashRope = "Shrine Of The Sea God Rushing Water Bridges - Lash Rope"
    ShrineOfTheSeaGod_QuadBridgesWest_WesternStairs = "Shrine Of The Sea God Quad Bridges West - Western Stairs"
    ShrineOfTheSeaGod_QuadBridgesWest_EasternStairs = "Shrine Of The Sea God Quad Bridges West - Eastern Stairs"
    ShrineOfTheSeaGod_QuadBridgesWest_LogJump = "Shrine Of The Sea God Quad Bridges West - Log Jump"
    ShrineOfTheSeaGod_WateryShrineInWater_SouthWestStairs = "Shrine Of The Sea God Watery Shrine - SouthWestern Stairs"
    ShrineOfTheSeaGod_WateryShrineInWater_ElevateShrine = "Shrine Of The Sea God Watery Shrine - Elevate Shrine"
    ShrineOfTheSeaGod_ElevatedShrine_LoweringShrine = "Shrine Of The Sea God Elevated Shrine - Lower Shrine"
    ShrineOfTheSeaGod_ElevatedShrine_NorthWestLadder = "Shrine Of The Sea God Elevated Shrine - NorthWestern Ladder"
    ShrineOfTheSeaGod_UpperTowerArea_WestLadder = "Shrine Of The Sea God Upper Tower Area - Western Ladder"
    ShrineOfTheSeaGod_UpperTowerArea_EastLadder = "Shrine Of The Sea God Upper Tower Area - Eastern Ladder"
    ShrineOfTheSeaGod_TopOfTheShrine_EastLadder = "Shrine Of The Sea God Top of the Shrine - Eastern Ladder"


    #DehkanPlateau
    DehkanPlateau_West_To_Overworld = "Dehkan Plateau - North Western Exit"
    DehkanPlateau_East_To_Overworld = "Dehkan Plateau - South Eastern Exit"
    Overworld_To_DehkanPlateau_NorthWestSide = "Overworld - Dehkan Plateau North Western Side"
    Overworld_To_DehkanPlateau_SouthEastSide = "Overworld - Dehkan Plateau South Eastern Side"
    DehkanPlateau_TripleStairsCrackedFloor = "Dehkan Plateau - Triple Stairs Room Cracked Floor"
    DehkanPlateau_TripleStairsUpperLedgeEasternExit = "Dehkan Plateau - Triple Stairs Room Upper Ledge Eastern Exit"
    DehkanPlateau_TripleStairsUpperLedgeDoorway = "Dehkan Plateau - Triple Stairs Room Upper Ledge Doorway"
    DehkanPlateau_TripleStairsUpperLedgeDropDown = "Dehkan Plateau - Triple Stairs Room Upper Ledge DropDown"
    DehkanPlateau_IsolatedNearTripleStairs_Doorway = "Dehkan Plateau - Triple Stairs Room Isolated Ledge Doorway"
    DehkanPlateau_HorizontalOvalShapedCave_NorthDoorway = "Dehkan Plateau - Oval Shaped Cavern Northern Doorway"
    DehkanPlateau_HorizontalOvalShapedCave_SouthDoorway = "Dehkan Plateau - Oval Shaped Cavern Southern Doorway"
    DehkanPlateau_TripleStonePillars_WesternExit = "Dehkan Plateau - Triple Stone Pillar Room Western Exit"
    DehkanPlateau_TripleStonePillars_NorthernExit = "Dehkan Plateau - Triple Stone Pillar Room Northern Exit"
    DehkanPlateau_TripleStonePillars_CrackedFloor = "Dehkan Plateau - Triple Stone Pillar Room Cracked Floor"
    DehkanPlateau_TeasingCavernSouthernExit = "Dehkan Plateau - Teasing Cavern Southern Exit"
    DehkanPlateau_TeasingCavernDropDown = "Dehkan Plateau - Teasing Cavern DropDown"
    DehkanPlateau_UShapedCavern_WestDoorway = "Dehkan Plateau - U Cavern Western Doorway"
    DehkanPlateau_UShapedCavern_EastDoorway = "Dehkan Plateau - U Cavern Eastern Doorway"
    DehkanPlateau_StonePillarsLogLedge_LogJump = "Dehkan Plateau - Stone Pillars Log Ledge Log Jump"
    DehkanPlateau_StonePillarsLogLedge_Doorway = "Dehkan Plateau - Stone Pillars Log Ledge Eastern Doorway"
    DehkanPlateau_StonePillarMaze_SouthernExit = "Dehkan Plateau - Stone Pillar Maze Southern Exit"
    DehkanPlateau_StonePillarMaze_EasternExit = "Dehkan Plateau - Stone Pillar Maze Eastern Exit"
    DehkanPlateau_CrackedFloorsRockSlide_WesternExit = "Dehkan Plateau - Rockslide Cracked Floors Area Western Exit"
    DehkanPlateau_CrackedFloorsRockSlide_CrackedFloor = "Dehkan Plateau - Rockslide Cracked Floors Area Cracked Floor"
    DehkanPlateau_BalloonCavern_SouthernExit = "Dehkan Plateau - Balloon Cavern Southern Exit"
    DehkanPlateau_MirrorJCavern_WesternExit = "Dehkan Plateau - Mirror J Cavern Western Exit"
    DehkanPlateau_MirrorJCavern_EasternExit = "Dehkan Plateau - Mirror J Cavern Eastern Exit"
    DehkanPlateau_IsolatedCrakcedFloorsArea_Doorway = "Dehkan Plateau - Isolated Cracked Floors Area Doorway"
    DehkanPlateau_IsolatedCrakcedFloorsArea_CrackedFloor = "Dehkan Plateau - Isolated Cracked Floors Area Cracked Floor"
    DehkanPlateau_SideEyeCavern_Doorway = "Dehkan Plateau - SideEye Cavern Doorway"
    DehkanPlateau_RockSlideArea_Doorway = "Dehkan Plateau - Rockslide Area Doorway"
    DehkanPlateau_RockSlideArea_EasternExit = "Dehkan Plateau - Rockslide Area Eastern Exit"
    DehkanPlateau_RockSlideArea_LogJump = "Dehkan Plateau - Rockslide Area Log Jump"
    DehkanPlateau_RopeBridge_WesternExit = "Dehkan Plateau - Rope Bridge Western Exit"
    DehkanPlateau_RopeBridge_Doorway = "Dehkan Plateau - Rope Bridge Doorway"
    DehkanPlateau_RopeBridge_ToCrackedFloorArea = "Dehkan Plateau - Rope Bridge To Cracked Floors"
    DehkanPlateau_RopeBridge_VineLogClimb = "Dehkan Plateau - Vine Log Climb"
    DehkanPlateau_RopeBridge_CrackedFloor = "Dehkan Plateau - Rope Bridge Cracked Floor"
    DehkanPlateau_BottleCavern_Doorway = "Dehkan Plateau - Bottle Cavern Doorway"
    DehkanPlateau_BelowRopeBridge_ToCrackedFloorArea = "Dehkan Plateau - Below Rope Bridge To Cracked Floors"
    DehkanPlateau_BelowRopeBridge_EasternExit = "Dehkan Plateau - Below Rope Bridge Eastern Exit"
    DehkanPlateau_CrampedWesternLedge_WesternExit = "Dehkan Plateau - Cramped Western Ledge Western Exit"
    DehkanPlateau_CrampedWesternLedge_LogJumpToMCentralLedge = "Dehkan Plateau - Cramped Western Ledge Log Jump To Central Ledge"
    DehkanPlateau_MiddleLedgeBetweenPillars_Doorway = "Dehkan Plateau - Middle Ledge Between Pillars Doorway"
    DehkanPlateau_MiddleLedgeBetweenPillars_Dropdown = "Dehkan Plateau - Middle Ledge Between Pillars DropDown"
    DehkanPlateau_ThreeAngledCavern_NorthernDoorway = "Dehkan Plateau - Three Angled Cavern Northen Doorway"
    DehkanPlateau_ThreeAngledCavern_EasternDoorway = "Dehkan Plateau - Three Angled Cavern Eastern Doorway"
    DehkanPlateau_CrackedFloorCaveLowerHalf_EasternDoorway = "Dehkan Plateau - Cracked Floor Cavern Lower Half Eastern Doorway"
    DehkanPlateau_CrackedFloorCaveLowerHalf_SouthernDoorway = "Dehkan Plateau - Cracked Floor Cavern Lower Half Southern Doorway"
    DehkanPlateau_CrackedFloorCaveLowerHalf_WesternDoorway = "Dehkan Plateau - Cracked Floor Cavern Lower Half Western Doorway"
    DehkanPlateau_CrackedFloorCaveLowerHalf_ToCrackedFloorArea = "Dehkan Plateau - Cracked Floor Cavern Lower Half To Cracked Floors"
    DehkanPlateau_CrackedFloorCave_CrackedFloor = "Dehkan Plateau - Cracked Floor Cavern Cracked Floor"
    DehkanPlateau_CrackedFloorCaveDjinnDrop_ToLowerHalf = "Dehkan Plateau - Cracked Floor Cavern Djinn Drop To Lower Half"
    DehkanPlateau_CrackedFloorCaveDjinnDrop_ToUpperHalf = "Dehkan Plateau - Cracked Floor Cavern Djinn Drop To Upper Half"
    DehkanPlateau_CrackedFloorCaveUpperHalf_ToCrackedFloorArea = "Dehkan Plateau - Cracked Floor Cavern Upper Half To Cracked Floors"
    DehkanPlateau_CrackedFloorCaveUpperHalf_NorthenDoorway = "Dehkan Plateau - Cracked Floor Cavern Upper Half Northern Doorway"
    DehkanPlateau_DeepCavenDropDownArea_Doorway = "Dehkan Plateau - Deep Cavern Drop Down Area Doorway"
    DehkanPlateau_PoundPillarCavernUpperHalf_WesternDoorway = "Dehkan Plateau - Pound Pillar Cave Upper Half Western Doorway"
    DehkanPlateau_PoundPillarCavernUpperHalf_EasternDoorway = "Dehkan Plateau - Pound Pillar Cave Upper Half Eastern Doorway"
    DehkanPlateau_PoundPillarCavernUpperHalf_ToLowerHalf = "Dehkan Plateau - Pound Pillar Cave Upper Half To Lower Half"
    DehkanPlateau_PoundPillarCavernLowerHalf_WesternDoorway = "Dehkan Plateau - Pound Pillar Cave Lower Half Western Doorway"
    DehkanPlateau_PoundPillarCavernLowerHalf_EasternDoorway = "Dehkan Plateau - Pound Pillar Cave Lower Half Eastern Doorway"
    DehkanPlateau_PoundPillarCavernLowerHalf_ToUpperHalf = "Dehkan Plateau - Pound Pillar Cave Lower Half To Upper Half"
    DehkanPlateau_CrackedFloorsNorthOfPillar_Doorway = "Dehkan Plateau - Cracked Floors North of Pillar Doorway"
    DehkanPlateau_CrackedFloorsNorthOfPillar_CrackedFloor = "Dehkan Plateau - Cracked Floors North of Pillar Cracked Floor"
    DehkanPlateau_DeepCavernUpperLedge_NorthernDoorway = "Dehkan Plateau - Deep Cavern Upper Ledge - Northern Doorway"
    DehkanPlateau_DeepCavernUpperLedge_SouthernDoorway = "Dehkan Plateau - Deep Cavern Upper Ledge - Southern Doorway"
    DehkanPlateau_DjinnCombatCavernRoom_NorthernDoorway = "Dehkan Plateau - Djinn Combat Cavern - Northern Doorway"
    DehkanPlateau_DjinnCombatCavernRoom_SouthernDoorway = "Dehkan Plateau - Djinn Combat Cavern - Southern Doorway"
    DehkanPlateau_FlatHallwayDeepCavern_WesternDoorway = "Dehkan Plateau - Flat Hallway Cavern - Western Doorway"
    DehkanPlateau_FlatHallwayDeepCavern_EasternDoorway = "Dehkan Plateau - Flat Hallway Cavern - Eastern Doorway"
    DehkanPlateau_QuadStairs_LogVines = "Dehkan Plateau - Quad Stairs - Log Vines"
    DehkanPlateau_QuadStairs_EasternDoorway = "Dehkan Plateau - Quad Stairs - Eastern Doorway"

    #Indra Cavern
    IndraCavern_To_Overworld = "Indra Cavern - Southern Exit"
    Overworld_To_IndraCavern = "Overworld - Indra Cavern"

    #MAdra
    Madra_To_Overworld = "Madra - Southern Exit"
    Overworld_To_Madra = "Overworld - Madra"
    MadraToMadraCatacombsEast = "Madra - Eastern Ladder"
    MadraToMadraCatacombsWest = "Madra - Western Ladder"

    #Madra Catacombs
    MadraCatacombsEastToMadra = "Madra Catacombs Lader Room East - Ladder"
    MadraCatacombsWestToMadra = "Madra Catacombs Lader Room West - Ladder"
    MadraCatacombsLadderRoomEast_SouthernDoorway = "Madra Catacombs Lader Room East - Doorway"
    MadraCatacombsLadderRoomWest_SouthernDoorway = "Madra Catacombs Lader Room West - Doorway"
    MadraCatacombsEastConnectorRoom_NorthEasternDoorway = "Madra Catacombs Eastern Connector Room - North Eastern Doorway"
    MadraCatacombsEastConnectorRoom_NorthWesternDoorway = "Madra Catacombs Eastern Connector Room - North Western Doorway"
    MadraCatacombsEastConnectorRoom_SouthWesternDoorway = "Madra Catacombs Eastern Connector Room - South Western Doorway"
    MadraCatacombsRockBlockedRoom_SouthernDoorway = "Madra Catacombs Rock Blocked Room - South Doorway"
    MadraCatacombsRockLedgeEastRidge_Doorway = "Madra Catacombs Rock Ledge East Ridge - Doorway"
    MadraCatacombsRockLedgeEastRidge_LashRope = "Madra Catacombs Rock Ledge East Ridge - LashRope"
    MadraCatacombsRockLedgeWestRidge_NorthernDoorway = "Madra Catacombs Rock Ledge West Ridge - Northern Doorway"
    MadraCatacombsRockLedgeWestRidge_WesternDoorway = "Madra Catacombs Rock Ledge West Ridge - Western Doorway"
    MadraCatacombsRuinsEntry_EasternDoorway = "Madra Catacombs Ruins Entry - Eastern Doorway"
    MadraCatacombsRuinsEntry_RevealDoor = "Madra Catacombs Ruins Entry - Reveal Door"
    MadraCatacombsMainRuins_RevealDoor = "Madra Catacombs Main Ruins - Reveal Door"
    MadraCatacombsMainRuins_VineClimb = "Madra Catacombs Main Ruins - VineLog Climb"
    MadraCatacombsMainRuinsArea_MainRuinEntry = "Madra Catacombs Main Ruins - Main Building Central Doorway"
    MadraCatacombsBackRuins_EasternRuinEntry = "Madra Catacombs Back Ruins - Main Building Eastern Doorway"
    MadraCatacombsBackRuins_ScalingTheRuins = "Madra Catacombs Back Ruins - Scaling the Ruins"
    MadraCatacombsUpperRuins_DropDown = "Madra Catacombs Upper Ruins - Drop Down"
    MadraCatacombsUpperRuinsArea_RuinsUpperDoorway = "Madra Catacombs Upper Ruins - Main Building Upper Doorway"
    MadraCatacombsRuinedBuilding_EasternHallway_EasternLedge_SouthExit = "Madra Catacombs Building - Eastern Hallway Eastern Ledge Southern Doorway"
    MadraCatacombsRuinedBuilding_EasternHallway_EasternLedge_Stairway = "Madra Catacombs Building - Eastern Hallway Eastern Ledge Northern Stairway"
    MadraCatacombsRuinedBuilding_TightRidge_Stairway = "Madra Catacombs Building - Basement Tightledge Stairway"
    MadraCatacombsRuinedBuilding_TightRidge_Doorway = "Madra Catacombs Building - Basement Tightledge Doorway"
    MadraCatacombsRuinedBuilding_TremorRoom_SouthDoorway = "Madra Catacombs Building - Basement TremorRoom Doorway"
    MadraCatacombsRuinedBuilding_EntryHall_SouthernDoorway = "Madra Catacombs Building - Entry Hall Southern Doorway"
    MadraCatacombsRuinedBuilding_EntryHall_WesternDoorway = "Madra Catacombs Building - Entry Hall Western Doorway"
    MadraCatacombsRuinedBuilding_EntryHall_NorthernDoorway = "Madra Catacombs Building - Entry Hall Northern Doorway"
    MadraCatacombsRuinedBuilding_EntryHall_EastStairs = "Madra Catacombs Building - Entry Hall Eastern Stairs"
    MadraCatacombsRuinedBuilding_EntryHall_EasternDoorway = "Madra Catacombs Building - Entry Hall Eastern Doorway"
    MadraCatacombsRuinedBuilding_CollapsedHall_SouthDoorway = "Madra Catacombs Building - Collapsed Hall Southern Doorrway"
    MadraCatacombsRuinedBuilding_CentralRoom_SouthDoor = "Madra Catacombs Building - Central Room Southern Doorrway"
    MadraCatacombsRuinedBuilding_MainUpstairsEastArea_EastStairs = "Madra Catacombs Building - Main Upstairs Eastern Stairs"
    MadraCatacombsRuinedBuilding_MainUpstairsEastArea_EastDoorway = "Madra Catacombs Building - Main Upstairs Eastern Doorway"
    MadraCatacombsRuinedBuilding_EastBedroom_Doorway = "Madra Catacombs Building - Upstairs Eastern Bedroom Southern Doorway"
    MadraCatacombsRuinedBuilding_EasternHallway_WesternLedge_SouthDoor = "Madra Catacombs Building - Eastern Hallway Western Ledge Southern Doorway"
    MadraCatacombsRuinedBuilding_EasternHallway_WesternLedge_DownStairway = "Madra Catacombs Building - Eastern Hallway Western Ledge DownStairs"
    MadraCatacombsRuinedBuilding_EasternHallway_WesternLedge_UpStairway = "Madra Catacombs Building - Eastern Hallway Western Ledge UpStairs"
    MadraCatacombsRuinedBuilding_LockedRoom_Stairway = "Madra Catacombs Building - Downstairs LockedRoom Stairway"
    MadraCatacombsRuinedBuilding_LongHallway_EastDownStairway = "Madra Catacombs Building - Uptairs Longhallway Eastern Stairway"
    MadraCatacombsRuinedBuilding_LongHallway_WestDownStairway = "Madra Catacombs Building - Uptairs Longhallway Western Stairway"
    MadraCatacombsRuinedBuilding_CollapsedHall_NorthSide_Stairway = "Madra Catacombs Building - Collapsed Hall Northern Doorrway"
    MadraCatacombsRuinedBuilding_MainUpstairsWestArea_SouthDoorway = "Madra Catacombs Building - Main Upstairs Southern Doorway"
    MadraCatacombsRuinedBuilding_MainUpstairsWestArea_NorthDoorway = "Madra Catacombs Building - Main Upstairs Western Doorway"
    MadraCatacombsRuinedBuilding_WestBedroom_Doorway = "Madra Catacombs Building - Upstairs Western Bedroom Southern Doorway"

    #Madra Drawbridge
    Overworld_To_MadraDrawbridge_SouthSide = "Overworld - Madra Drawbridge South Side"
    Overworld_To_MadraDrawbridge_NorthSide = "Overworld - Madra Drawbright North Side"
    MadraDrawbridge_South_To_Overworld = "Madra Drawbridge - Southern Exit"
    MadraDrawbridge_North_To_Overworld = "Madra Drawbridge - Northern Exit"

    #Indra


    Overworld_To_GondowanCliffs_EastSide = "Overworld - Gondowan Cliffs East Side"
    Overworld_To_GondowanCliffs_WestSide = "Overworld - Gondowan Cliffs West Side"
    GondowanCliffs_East_To_Overworld = "Gondown Cliffs - Eastern Exit"

    #Osenia
    Overworld_To_OseniaCliffs_WestSide = "Overworld - Osenia Cliffs West Side"
    OseniaCliffs_West_To_Overworld = "Osenia Cliffs - Western Exit"
    Overworld_To_OseniaCliffs_EastSide = "Overworld - Osenia Cliffs East Side"
    OseniaCliffs_East_To_Overworld = "Osenia Cliffs - Eastern Exit"
    Overworld_To_Mikasalla = "Overworld - Mikasalla"
    Mikasalla_To_Overworld = "Mikasalla - Eastern Exit"
    Overworld_To_OseniaCavern = "Overworld - Osenia Cavern"
    OseniaCavern_To_Overworld = "Osenia Cavern - Southern Exit"
    Overworld_To_Garoh = "Overworld - Garoh"
    Garoh_To_Overworld = "Garoh - Southern Exit"
    Overworld_To_AirsRock = "Overworld - Airs Rock"
    AirsRock_To_Overworld = "Airs Rock - Southern Exit"
    Overworld_To_YampiDesertFront = "Overworld - Yampi Desert Front"
    Overworld_Garoh_To_YampiDesertBack = "Overworld (Garoh) - Yampi Desert Back"
    YampiDesertBack_To_Overworld_Garoh = "Yampi Desert Back - Southern Exit"
    YampDesertFront_To_Overworld = "Yampi Desert Front - Western Exit"
    YampiDesertBack_To_Overworld_Alhafra = "Yampi Desert Back - Northern Exit"
    Overworld_To_Alhafra = "Overworld - Alhafra"
    Overworld_Alhafra_To_YampiDesertBack = "Overworld (Alhafra) - Yampi Desert Back"
    Alhafra_To_Overworld = "Alhafra - Southern Exit"

    #Gondowan
    GondowanCliffs_West_To_Overworld = "Gondowan Cliffs - Western Exit"
    Overworld_To_KibomboMountains_SouthSide = "Overworld - Kibombo Mountains South Side"
    Overworld_To_KibomboMountains_NorthSide = "Overworld - Kibombo Mountains North Side"
    Overworld_To_Naribwe_SouthSide = "Overworld - Naribwe SouthSide"
    Overworld_To_Naribwe_NorthSide = "Overworld - Naribwe NorthSide"
    Naribwe_South_To_Overworld = "Naribwe - Southern Exit"
    Naribwe_North_To_Overworld = "Naribwe - Northern Exit"
    KibomboMountains_South_To_Overworld = "Kibombo Mountains - Southern Exit"
    KibomboMountains_NorthWest_To_Overworld = "Kibombo Mountains - Northwestern Exit"
    Overworld_To_Kibombo = "Overworld - Kibombo"
    Kibombo_To_Overworld = "Kibombo - Southern Exit"


    #Eastern Sea
    Overworld_Indra_North_To_EasternSea = "Overworld - Northern Indra To Eastern Sea"
    Overworld_Indra_South_To_EasternSea = "Overworld - Southern Indra To Eastern Sea"
    Overworld_Oseania_AlhafraArea_To_EasternSea = "Overworld - Osenia Alhafra Area To Eastern Sea"
    Overworld_Gondowan_Central_To_EasternSea = "Overworld - Central Gondowan To Eastern Sea"
    Overworld_Gondowan_South_To_EasternSea = "Overworld - Southern Gondowan To Eastern Sea"
    Overworld_WestIndraIslet_To_EasternSea = "Overworld - West Indra Islet To Eastern Sea"
    Overworld_EastTundariaIslet_To_EasternSea = "Overworld - East Tundaria Islet To Eastern Sea"
    Overworld_NorthOseniaIslet_To_EasternSea = "Overworld - North Osenia Islet To Eastern Sea"
    Overworld_SouthEastAngaraIslet_To_EasternSea = "Overworld - South East Angara Islet To Eastern Sea"
    Overworld_SeaOfTimeIslet_To_EasternSea = "Overworld - Sea of Time Islet To Eastern Sea"
    Overworld_ApojiiIslands_To_EasternSea = "Overworld - Apojii Islands To Eastern Sea"
    Overworld_AquaRock_To_EasternSea = "Overworld - Aqua Rock To Eastern Sea"
    Overworld_Izumo_To_EasternSea = "Overworld - Izumo To Eastern Sea"
    Overworld_TreasureIsland_To_EasternSea = "Overworld - Treasure Island To Eastern Sea"
    Overworld_Tundaria_To_EasternSea = "Overworld - Tundaria To Eastern Sea"
    Overworld_SEAngara_To_EasternSea = "Overworld - SouthEastern Angara to Eastern Sea"
    Overworld_SouthernAngara_To_EasternSea = "Overworld - Southern Angara to Eastern Sea"
    Overworld_SouthEastOsenia_To_EasternSea = "Overworld - SouthEastern Osenia to Eastern Sea"

    Overworld_EasternSea_To_Indra_North = "Eastern Sea To Northern Indra"
    Overworld_EasternSea_To_Indra_South = "Eastern Sea To Southern Indra"
    Overworld_EasternSea_To_Osenia_AlhafraArea = "Eastern Sea To Osenia Alhafra Area"
    Overworld_EasternSea_To_Gondowan_Central = "Eastern Sea To Central Gondowan"
    Overworld_EasternSea_To_Gondowan_South = "Eastern Sea To Southern Gondowan"
    Overworld_EasternSea_To_WestIndraIslet = "Eastern Sea To West Indra Islet"
    Overworld_EasternSea_To_EastTundariaIslet = "Eastern Sea To East Tundaria Islet"
    Overworld_EasternSea_To_NorthOseniaIslet = "Eastern Sea To North Osenia Islet"
    Overworld_EasternSea_To_SouthEastAngaraIslet = "Eastern Sea To South East Angara Islet"
    Overworld_EasternSea_To_SeaOfTimeIslet = "Eastern Sea To Sea Of Time Islet"
    Overworld_EasternSea_To_ApojiiIslands = "Eastern Sea To Apojii Islands"
    Overworld_EasternSea_To_AquaRock = "Eastern Sea To Aqua Rock"
    Overworld_EasternSea_To_Izumo = "Eastern Sea To Izumo"
    Overworld_EasternSea_To_TreasureIsland = "Eastern Sea To Treasure Island"
    Overworld_EasternSea_To_Tundaria = "Eastern Sea To Tundaria"
    Overworld_EasternSea_To_SEAngara = "Eastern Sea To SouthEastern Angara"
    Overworld_EasternSea_To_SouthernAngara = "Eastern Sea To Southern Angara"
    Overworld_EasternSea_To_SouthEastOsenia = "Eastern Sea To SouthEastern Osenia"

    Overworld_WestIndraIslet_To_WestIndraIslet = "Overworld - West Indra Islet"
    WestIndraIslet_To_Overworld = "West Indra Islet - Southern Exit"
    Overworld_EastTundariaIslet_To_EastTundariaIslet = "Overworld - East Tundaria Islet"
    EastTundariaIslet_To_Overworld = "East Tundaria Islet - Southern Exit"
    Overworld_NorthOseniaIslet_To_NorthOseniaIslet = "Overworld - North Osenia Islet"
    NorthOseniaIslet_To_Overworld = "North Osenia Islet - Southern Exit"
    Overworld_SouthEastAngaraIslet_To_SouthEastAngaraIslet = "Overworld - SouthEast Angara Islet"
    SouthEastAngaraIslet_To_Overworld = "SouthEast Angara Islet - Western Exit"
    Overworld_SeaOfTimeIslet_To_SeaOfTimeIslet = "Overworld - Sea of Time Islet"
    SeaOfTimeIslet_To_Overworld = "Sea of Time Islet - Northern Exit"
    Overworld_ApojiiIslands_To_ApojiIslands = "Overworld - Apojii Islands"
    ApojiiIslands_To_Overworld = "Apojii Islands - Western Exit"
    Overworld_AquaRock_To_AquaRock = "Overworld - Aqua Rock"
    AquaRock_To_Overworld = "Aqua Rock - Southern Exit"
    Overworld_Izumo_To_Izumo = "Overworld - Izumo"
    Izumo_To_Overworld = "Izumo - Western Exit"
    Overworld_Izumo_To_GaiaRock = "Overworld - Gaia Rock"
    GaiaRock_To_Overworld = "Gaia Rock - Southern Exit"
    Overworld_TreasureIsland_To_TreasureIsland = "Overworld - Treasure Island"
    TreasureIsland_To_Overworld = "Treasure Island - Southern Exit"
    Overworld_Tundaria_To_TundariaTower = "Overworld - Tundaria Tower"
    TundariaTower_To_Overworld = "Tundaria Tower - Southern Exit"
    Overworld_SEAngara_To_AnkohlRuins = "Overworld - Ankohl Ruins"
    AnkohlRuins_To_Overworld = "Ankohl Ruins - Southern Exit"
    Overworld_SouthernAngara_To_Champa = "Overworld - Champa"
    Champa_To_Overworld = "Champa - Southern Exit"
    Overworld_SouthEastOsenia_To_YallamSouth = "Overworld - Yallam Southside"
    Overworld_NorthEastOsenia_To_YallamNorth = "Overworld - Yallam Northside"
    YallamSouth_To_Overworld = "Yallam - Southern Exit"
    YallamNorth_To_Overworld = "Yallam - Northern Exit"
    Overworld_NorthEastOsenia_To_TaopoSwamp = "Overworld - Taopo Swamp"
    TaopoSwamp_To_Overworld = "Taopo Swamp - Western Exit"

    
    Overworld_WesternSea_To_SouthWestAttekaIslet = "Western Sea To South West Atteka Islet"
    Overworld_SouthWestAttekaIslet_To_WesternSea = "Overworld - South West Atteka Islet To Western Sea"
    Overworld_WesternSea_To_KaltIsland = "Western Sea To Kalt Island"
    Overworld_KaltIsland_To_WesternSea = "Overworld - Kalt Island To Western Sea"
    Overworld_WesternSea_To_WestGondowan = "Western Sea To Western Gondowan"
    Overworld_WestGondowan_To_WesternSea = "Overworld - Western Gondowan To Western Sea"
    Overworld_WesternSea_To_WesternAngara = "Western Sea To Western Anagra"
    Overworld_WesternAngara_To_WesternSea = "Overworld - Western Angara To Western Sea"
    Overworld_WesternSea_To_NeHesperia = "Western Sea To NorthEastern Hesperia"
    Overworld_WesternSea_To_WestHesperia = "Western Sea To Western Hesperia"
    Overworld_WesternHesperia_To_WesternSea = "Overworld - Western Hesperia To Western Sea"
    Overworld_WesternSea_To_CentralHesperia = "Western Sea To Central Hesperia"
    Overworld_CentralHesperia_To_WesternSea = "Overworld - Central Hesperia To Western Sea"
    Overworld_WesternSea_To_WesternAtteka = "Western Sea To Western Atteka"
    Overworld_WesternSea_To_SouthernAtteka = "Western Sea To Southern Atteka"
    Overworld_SouthernAtteka_To_WesternSea = "Overworld - Southern Atteka to Western Sea"

    
    Overworld_SouthWestAttekaIslet_To_SouthWestAttekaIslet = "Overworld - South West Atteka Islet"
    SouthWestAttekaIslet_To_Overworld = "South West Atteka Islet - North Eastern Exit"
    Overworld_KaltIsland_To_KaltIsland = "Overworld - Kalt Island"
    KaltIsland_To_Overworld = "Kalt Island - Southern Exit"
    Overworld_WestGondowan_To_GondowanSettlement = "Overworld - Gondowan Settlement"
    GondowanSettlement_To_Overworld = "Gondowan Settlement - Southern Exit"
    Overworld_WestGondowan_To_MagmaRock = "Overworld - Magma Rock"
    MagmaRock_To_Overworld = "Magma Rock - Southern Exit"
    Overworld_WestAngara_To_Loho = "Overworld - Loho"
    Loho_To_Overworld = "Loho - Western Exit"
    Overworld_WestAngara_To_AngaraCavern = "Overworld - Angara Cavern"
    AngaraCavern_To_Overworld = "Angara Cavern - Southern Exit"
    Overworld_WeHesperia_HesperiaSettlement = "Overworld - Hesperia Settlement"
    HesperiaSettlement_To_Overworld = "Hesperia Settlement - Southern Exit"
    Overworld_CentralHesperia_To_ShamanVillageCave = "Overworld - Shaman Village Cave SouthWestern Side"
    ShamanVillageCave_SouthWest_To_Overworld = "Shaman Village Cave - SouthWestern Exit"
    ShamanVillageCave_East_To_Overworld = "Shaman Village Cave - Eastern Exit"
    Overworld_ShamanHesperia_To_ShamanVillageCave = "Overworld - Shaman Village Cave Eastern Side"
    Overworld_ShamanHesperia_To_ShamanVillage = "Overworld - Shaman Village"
    ShamanVillage_To_Overworld = "Shaman Village - Southern Exit"
    Overworld_SouthernAtteka_To_AttekaCavern = "Overworld - Atteka Cavern"
    AttekaCavern_To_Overworld = "Atteka Cavern - Southern Exit"
    Overworld_CentralAtteka_To_AttekaInlet_Land = "Overworld - Atteka Inlet Land"
    AttekaInlet_To_Overworld_Land = "Atteka Inlet - Northern Exit"
    Overworld_CentralAtteka_To_Contigo = "Overworld - Contigo"
    Contigo_To_Overworld = "Contigo - Southern Exit"
    Overworld_CentralAtteka_To_JupiterLighthouse = "Overworld - Jupiter Lighthouse"
    JupiterLighthouse_To_Overworld = "Jupiter Lightouse - Southern Exit"

    Overworld_LowNorthernReaches_To_Prox = "Overworld - Prox South Side"
    Prox_To_Overworld_SouthSide = "Prox - Southern Exit"
    Prox_To_Overworld_NorthSide = "Prox - Northern Exit"
    Overworld_HighNorthenReaches_To_Prox = "Overworld - Prox North Side"
    Overworld_HighNorthenReaches_To_MarsLighthouse = "Overworld - Mars Lighthouse"
    MarsLighthouse_To_Overworld = "Mars Lighthouse - Southern Exit"


    #TODO
    MadraToLemurianShip = "Madra To Lemurian Ship"
    YampiDesertFrontToYampiDesertBack = "Yampi Desert Front To Yampi Desert Back"
    YampiDesertBackToYampiDesertCave = "Yampi Desert Back To Yampi Desert Cave"
    AlhafraToAlhafraCave = "Alhafra To Alhafra Cave"
    KibomboToGabombaStatue = "Kibombo To Gabomba Statue"
    GabombaStatueToGabombaCatacombs = "Gabomba Statue To Gabomba Catacombs"

    EasternSeaToSeaOfTime = "Eastern Sea To Sea Of Time"
    EasternSeaToWesternSea = "Eastern Sea To Western Sea"

    TreasureIslandToTreasureIsland_Grindstone = "Treasure Island To Treasure Island Post Grindstone"
    TreasureIsland_GrindstoneToTreasureIsland_PostReunion = "Treasure Island Post Grindstone To Treasure Island - PostReunion"
    TundariaTowerToTundariaTower_Parched = "Tundaria Tower To Tundaria Tower - Parched Areas"
    AnkohlRuinsToAnkohlRuins_Sand = "Ankohl Ruins To Ankohl Ruins - Post Sand"
    SeaOfTimeToLemuria = "Sea Of Time To Lemuria"
    LemuriaToShipRevisit = "Lemuria To Ship Revisit"
    WesternSeaToAttekaInlet = "Western Sea To Atteka Inlet"
    WesternSeaToProx = "Western Sea To Prox"
    AttekaInletToShipRevisit = "Atteka Inlet To Ship Revisit"
    ContigoToReunion = "Contigo To Reunion"
    ContigoToAnemosInnerSanctum = "Contigo To Anemos Inner Sanctum"
    MagmaRockToMagmaRockInterior = "Magma Rock To Magma Rock Interior"
    MarsLighthouseToMarsLighthouse_Activated = "Mars Lighthouse To Mars Lighthouse - Activated"
    SeaOfTimeIsletToIsletCave = "Sea Of Time Islet To Islet Cave"
    AnywhereToJoinedPartyMembers = "Joined Party Characters"