class EntranceName():
    Menu_StartGame = "Menu - Start Game"

    #Indra
    Overworld_To_Daila_NorthSide = "Overworld - Daila North Side"
    Overworld_To_Daila_SouthSide = "Overworld - Daila South Side"
    Overworld_To_ShrineOfTheSeaGod = "Overworld - Shrine Of The Sea God"
    Overworld_To_KandoreanTemple = "Overworld - Kandorean Temple"
    Overworld_To_DehkanPlateau_NorthWestSide = "Overworld - Dehkan Plateau North Western Side"
    Overworld_To_DehkanPlateau_SouthEastSide = "Overworld - Dehkan Plateau South Eastern Side"
    Overworld_To_IndraCavern = "Overworld - Indra Cavern"
    Overworld_To_Madra = "Overworld - Madra"
    Overworld_To_GondowanCliffs_EastSide = "Overworld - Gondowan Cliffs East Side"
    Overworld_To_GondowanCliffs_WestSide = "Overworld - Gondowan Cliffs West Side"
    Overworld_To_MadraDrawbridge_SouthSide = "Overworld - Madra Drawbridge South Side"
    Overworld_To_MadraDrawbridge_NorthSide = "Overworld - Madra Drawbright North Side"
    Idejima_To_Overworld = "Idejima - Western Exit"
    Daila_North_To_Overworld = "Daila - Northern Exit"
    Daila_South_To_Overworld = "Daila - Southern Exit"
    KandoreanTemple_To_Overworld = "Kandorean Temple - Southern Exit"
    ShrineOfTheSeaGod_To_Overworld = "Shrine Of The Sea God - Southern Exit"
    DehkanPlateau_West_To_Overworld = "Dehkan Plateau - North Western Exit"
    DehkanPlateau_East_To_Overworld = "Dehkan Plateau - South Eastern Exit"
    IndraCavern_To_Overworld = "Indra Cavern - Southern Exit"
    Madra_To_Overworld = "Madra - Southern Exit"
    GondowanCliffs_East_To_Overworld = "Gondown Cliffs - Eastern Exit"
    MadraDrawbridge_South_To_Overworld = "Madra Drawbridge - Southern Exit"
    MadraDrawbridge_North_To_Overworld = "Madra Drawbridge - Northern Exit"

    #Osenia
    Overworld_To_OseniaCliffs_WestSide = "Overworld - Osenia Cliffs West Side"
    OseniaCliffs_West_To_Overworld = "Osenia Cliffs - Western Exit"
    Overworld_To_OseniaCliffs_EastSide = "Overworld - Osenia Cliffs East Side"
    OseniaCliffs_East_To_Overworld = "Osenia Cliffs - Eastern Exit"
    Overworld_To_Mikasalla = "Overworld - Mikasalla"
    Mikasalla_To_Overworld = "Mikasalla - Eastern Exit"
    Overworld_To_OseniaCavern = "Overworld - Osenia Cavern"
    OseniaCavern_To_Overworld = "Osenia Cavern - Southern Exit"
    Overworld_To_Garoh = "Overworld - Garoh"
    Garoh_To_Overworld = "Garoh - Southern Exit"
    Overworld_To_AirsRock = "Overworld - Airs Rock"
    AirsRock_To_Overworld = "Airs Rock - Southern Exit"
    Overworld_To_YampiDesertFront = "Overworld - Yampi Desert Front"
    Overworld_Garoh_To_YampiDesertBack = "Overworld (Garoh) - Yampi Desert Back"
    YampiDesertBack_To_Overworld_Garoh = "Yampi Desert Back - Southern Exit"
    YampDesertFront_To_Overworld = "Yampi Desert Front - Western Exit"
    YampiDesertBack_To_Overworld_Alhafra = "Yampi Desert Back - Northern Exit"
    Overworld_To_Alhafra = "Overworld - Alhafra"
    Overworld_Alhafra_To_YampiDesertBack = "Overworld (Alhafra) - Yampi Desert Back"
    Alhafra_To_Overworld = "Alhafra - Southern Exit"

    #Gondowan
    GondowanCliffs_West_To_Overworld = "Gondowan Cliffs - Western Exit"
    Overworld_To_KibomboMountains_SouthSide = "Overworld - Kibombo Mountains South Side"
    Overworld_To_KibomboMountains_NorthSide = "Overworld - Kibombo Mountains North Side"
    Overworld_To_Naribwe_SouthSide = "Overworld - Naribwe SouthSide"
    Overworld_To_Naribwe_NorthSide = "Overworld - Naribwe NorthSide"
    Naribwe_South_To_Overworld = "Naribwe - Southern Exit"
    Naribwe_North_To_Overworld = "Naribwe - Northern Exit"
    KibomboMountains_South_To_Overworld = "Kibombo Mountains - Southern Exit"
    KibomboMountains_NorthWest_To_Overworld = "Kibombo Mountains - Northwestern Exit"
    Overworld_To_Kibombo = "Overworld - Kibombo"
    Kibombo_To_Overworld = "Kibombo - Southern Exit"


    #Eastern Sea
    Overworld_Indra_North_To_EasternSea = "Overworld - Northern Indra To Eastern Sea"
    Overworld_Indra_South_To_EasternSea = "Overworld - Southern Indra To Eastern Sea"
    Overworld_Oseania_AlhafraArea_To_EasternSea = "Overworld - Osenia Alhafra Area To Eastern Sea"
    Overworld_Gondowan_Central_To_EasternSea = "Overworld - Central Gondowan To Eastern Sea"
    Overworld_Gondowan_South_To_EasternSea = "Overworld - Southern Gondowan To Eastern Sea"
    Overworld_WestIndraIslet_To_EasternSea = "Overworld - West Indra Islet To Eastern Sea"
    Overworld_EastTundariaIslet_To_EasternSea = "Overworld - East Tundaria Islet To Eastern Sea"
    Overworld_NorthOseniaIslet_To_EasternSea = "Overworld - North Osenia Islet To Eastern Sea"
    Overworld_SouthEastAngaraIslet_To_EasternSea = "Overworld - South East Angara Islet To Eastern Sea"
    Overworld_SeaOfTimeIslet_To_EasternSea = "Overworld - Sea of Time Islet To Eastern Sea"
    Overworld_ApojiiIslands_To_EasternSea = "Overworld - Apojii Islands To Eastern Sea"
    Overworld_AquaRock_To_EasternSea = "Overworld - Aqua Rock To Eastern Sea"
    Overworld_Izumo_To_EasternSea = "Overworld - Izumo To Eastern Sea"
    Overworld_TreasureIsland_To_EasternSea = "Overworld - Treasure Island To Eastern Sea"
    Overworld_Tundaria_To_EasternSea = "Overworld - Tundaria To Eastern Sea"
    Overworld_SEAngara_To_EasternSea = "Overworld - SouthEastern Angara to Eastern Sea"
    Overworld_SouthernAngara_To_EasternSea = "Overworld - Southern Angara to Eastern Sea"
    Overworld_SouthEastOsenia_To_EasternSea = "Overworld - SouthEastern Osenia to Eastern Sea"

    Overworld_EasternSea_To_Indra_North = "Eastern Sea To Northern Indra"
    Overworld_EasternSea_To_Indra_South = "Eastern Sea To Southern Indra"
    Overworld_EasternSea_To_Osenia_AlhafraArea = "Eastern Sea To Osenia Alhafra Area"
    Overworld_EasternSea_To_Gondowan_Central = "Eastern Sea To Central Gondowan"
    Overworld_EasternSea_To_Gondowan_South = "Eastern Sea To Southern Gondowan"
    Overworld_EasternSea_To_WestIndraIslet = "Eastern Sea To West Indra Islet"
    Overworld_EasternSea_To_EastTundariaIslet = "Eastern Sea To East Tundaria Islet"
    Overworld_EasternSea_To_NorthOseniaIslet = "Eastern Sea To North Osenia Islet"
    Overworld_EasternSea_To_SouthEastAngaraIslet = "Eastern Sea To South East Angara Islet"
    Overworld_EasternSea_To_SeaOfTimeIslet = "Eastern Sea To Sea Of Time Islet"
    Overworld_EasternSea_To_ApojiiIslands = "Eastern Sea To Apojii Islands"
    Overworld_EasternSea_To_AquaRock = "Eastern Sea To Aqua Rock"
    Overworld_EasternSea_To_Izumo = "Eastern Sea To Izumo"
    Overworld_EasternSea_To_TreasureIsland = "Eastern Sea To Treasure Island"
    Overworld_EasternSea_To_Tundaria = "Eastern Sea To Tundaria"
    Overworld_EasternSea_To_SEAngara = "Eastern Sea To SouthEastern Angara"
    Overworld_EasternSea_To_SouthernAngara = "Eastern Sea To Southern Angara"
    Overworld_EasternSea_To_SouthEastOsenia = "Eastern Sea To SouthEastern Osenia"

    Overworld_WestIndraIslet_To_WestIndraIslet = "Overworld - West Indra Islet"
    WestIndraIslet_To_Overworld = "West Indra Islet - Southern Exit"
    Overworld_EastTundariaIslet_To_EastTundariaIslet = "Overworld - East Tundaria Islet"
    EastTundariaIslet_To_Overworld = "East Tundaria Islet - Southern Exit"
    Overworld_NorthOseniaIslet_To_NorthOseniaIslet = "Overworld - North Osenia Islet"
    NorthOseniaIslet_To_Overworld = "North Osenia Islet - Southern Exit"
    Overworld_SouthEastAngaraIslet_To_SouthEastAngaraIslet = "Overworld - SouthEast Angara Islet"
    SouthEastAngaraIslet_To_Overworld = "SouthEast Angara Islet - Western Exit"
    Overworld_SeaOfTimeIslet_To_SeaOfTimeIslet = "Overworld - Sea of Time Islet"
    SeaOfTimeIslet_To_Overworld = "Sea of Time Islet - Northern Exit"
    Overworld_ApojiiIslands_To_ApojiIslands = "Overworld - Apojii Islands"
    ApojiiIslands_To_Overworld = "Apojii Islands - Western Exit"
    Overworld_AquaRock_To_AquaRock = "Overworld - Aqua Rock"
    AquaRock_To_Overworld = "Aqua Rock - Southern Exit"
    Overworld_Izumo_To_Izumo = "Overworld - Izumo"
    Izumo_To_Overworld = "Izumo - Western Exit"
    Overworld_Izumo_To_GaiaRock = "Overworld - Gaia Rock"
    GaiaRock_To_Overworld = "Gaia Rock - Southern Exit"
    Overworld_TreasureIsland_To_TreasureIsland = "Overworld - Treasure Island"
    TreasureIsland_To_Overworld = "Treasure Island - Southern Exit"
    Overworld_Tundaria_To_TundariaTower = "Overworld - Tundaria Tower"
    TundariaTower_To_Overworld = "Tundaria Tower - Southern Exit"
    Overworld_SEAngara_To_AnkohlRuins = "Overworld - Ankohl Ruins"
    AnkohlRuins_To_Overworld = "Ankohl Ruins - Southern Exit"
    Overworld_SouthernAngara_To_Champa = "Overworld - Champa"
    Champa_To_Overworld = "Champa - Southern Exit"
    Overworld_SouthEastOsenia_To_YallamSouth = "Overworld - Yallam Southside"
    Overworld_NorthEastOsenia_To_YallamNorth = "Overworld - Yallam Northside"
    YallamSouth_To_Overworld = "Yallam - Southern Exit"
    YallamNorth_To_Overworld = "Yallam - Northern Exit"
    Overworld_NorthEastOsenia_To_TaopoSwamp = "Overworld - Taopo Swamp"
    TaopoSwamp_To_Overworld = "Taopo Swamp - Western Exit"

    
    Overworld_WesternSea_To_SouthWestAttekaIslet = "Western Sea To South West Atteka Islet"
    Overworld_SouthWestAttekaIslet_To_WesternSea = "Overworld - South West Atteka Islet To Western Sea"
    Overworld_WesternSea_To_KaltIsland = "Western Sea To Kalt Island"
    Overworld_KaltIsland_To_WesternSea = "Overworld - Kalt Island To Western Sea"
    Overworld_WesternSea_To_WestGondowan = "Western Sea To Western Gondowan"
    Overworld_WestGondowan_To_WesternSea = "Overworld - Western Gondowan To Western Sea"
    Overworld_WesternSea_To_WesternAngara = "Western Sea To Western Anagra"
    Overworld_WesternAngara_To_WesternSea = "Overworld - Western Angara To Western Sea"
    Overworld_WesternSea_To_NeHesperia = "Western Sea To NorthEastern Hesperia"
    Overworld_WesternSea_To_WestHesperia = "Western Sea To Western Hesperia"
    Overworld_WesternHesperia_To_WesternSea = "Overworld - Western Hesperia To Western Sea"
    Overworld_WesternSea_To_CentralHesperia = "Western Sea To Central Hesperia"
    Overworld_CentralHesperia_To_WesternSea = "Overworld - Central Hesperia To Western Sea"

    
    Overworld_SouthWestAttekaIslet_To_SouthWestAttekaIslet = "Overworld - South West Atteka Islet"
    SouthWestAttekaIslet_To_Overworld = "South West Atteka Islet - North Eastern Exit"
    Overworld_KaltIsland_To_KaltIsland = "Overworld - Kalt Island"
    KaltIsland_To_Overworld = "Kalt Island - Southern Exit"
    Overworld_WestGondowan_To_GondowanSettlement = "Overworld - Gondowan Settlement"
    GondowanSettlement_To_Overworld = "Gondowan Settlement - Southern Exit"
    Overworld_WestGondowan_To_MagmaRock = "Overworld - Magma Rock"
    MagmaRock_To_Overworld = "Magma Rock - Southern Exit"
    Overworld_WestAngara_To_Loho = "Overworld - Loho"
    Loho_To_Overworld = "Loho - Western Exit"
    Overworld_WestAngara_To_AngaraCavern = "Overworld - Angara Cavern"
    AngaraCavern_To_Overworld = "Angara Cavern - Southern Exit"
    Overworld_WeHesperia_HesperiaSettlement = "Overworld - Hesperia Settlement"
    HesperiaSettlement_To_Overworld = "Hesperia Settlement - Southern Exit"
    Overworld_CentralHesperia_To_ShamanVillageCave = "Overworld - Shaman Village Cave SouthWestern Side"
    ShamanVillageCave_SouthWest_To_Overworld = "Shaman Village Cave - SouthWestern Exit"
    ShamanVillageCave_East_To_Overworld = "Shaman Village Cave - Eastern Exit"
    Overworld_ShamanHesperia_To_ShamanVillageCave = "Overworld - Shaman Village Cave Eastern Side"
    Overworld_ShamanHesperia_To_ShamanVillage = "Overworld - Shaman Village"
    ShamanVillage_To_Overworld = "Shaman Village - Southern Exit"


    #TODO
    MadraToMadraCatacombs = "Madra To Madra Catacombs"
    MadraToLemurianShip = "Madra To Lemurian Ship"
    YampiDesertFrontToYampiDesertBack = "Yampi Desert Front To Yampi Desert Back"
    YampiDesertBackToYampiDesertCave = "Yampi Desert Back To Yampi Desert Cave"
    AlhafraToAlhafraCave = "Alhafra To Alhafra Cave"
    KibomboToGabombaStatue = "Kibombo To Gabomba Statue"
    GabombaStatueToGabombaCatacombs = "Gabomba Statue To Gabomba Catacombs"

    EasternSeaToSeaOfTime = "Eastern Sea To Sea Of Time"
    EasternSeaToWesternSea = "Eastern Sea To Western Sea"

    TreasureIslandToTreasureIsland_Grindstone = "Treasure Island To Treasure Island Post Grindstone"
    TreasureIsland_GrindstoneToTreasureIsland_PostReunion = "Treasure Island Post Grindstone To Treasure Island - PostReunion"
    TundariaTowerToTundariaTower_Parched = "Tundaria Tower To Tundaria Tower - Parched Areas"
    AnkohlRuinsToAnkohlRuins_Sand = "Ankohl Ruins To Ankohl Ruins - Post Sand"
    SeaOfTimeToLemuria = "Sea Of Time To Lemuria"
    LemuriaToShipRevisit = "Lemuria To Ship Revisit"
    WesternSeaToAttekaInlet = "Western Sea To Atteka Inlet"
    WesternSeaToAttekaCavern = "Western Sea To Atteka Cavern"
    WesternSeaToProx = "Western Sea To Prox"
    AttekaInletToContigo = "Atteka Inlet To Contigo"
    AttekaInletToShipRevisit = "Atteka Inlet To Ship Revisit"
    ContigoToJupiterLighthouse = "Contigo To Jupiter Lighthouse"
    ContigoToReunion = "Contigo To Reunion"
    ContigoToAnemosInnerSanctum = "Contigo To Anemos Inner Sanctum"
    MagmaRockToMagmaRockInterior = "Magma Rock To Magma Rock Interior"
    ProxToMarsLighthouse = "Prox To Mars Lighthouse"
    MarsLighthouseToMarsLighthouse_Activated = "Mars Lighthouse To Mars Lighthouse - Activated"
    SeaOfTimeIsletToIsletCave = "Sea Of Time Islet To Islet Cave"
    AnywhereToJoinedPartyMembers = "Joined Party Characters"