class RegionName():
    Menu = "Menu"

    #Overworld
    EasternSea = "Eastern Sea"
    WesternSea = "Western Sea"
    Indra_IdejimaArea = "Overworld - Indra Idejima Area"
    Indra_NorthernIndra = "Overworld - Northern Indra"
    Indra_SouthernIndra = "Overworld - Southern Indra"
    Indra_MadraDrawBridgeArea = "Overworld - Madra Drawbridge Area"

    #Idejima
    Indra_Idejima = "Indra - Idejima"

    #Daila
    Indra_Daila = "Indra - Daila"

    #Shrine of the Sea God
    ShrineOfTheSeaGod_EntryRoom_LowerHalf = "Shrine of the Sea God - Entry Room Lower Half"
    ShrineOfTheSeaGod_EntryRoom_UpperHalf = "Shrine of the Sea God - Entry Room Upper Half"
    ShrineOfTheSeaGod_Torched_DeadEnd= "Shrine of the Sea God - Toched Dead End"
    ShrineOfTheSeaGod_Quad_Bridge_Upper_Ridges = "Shrine of the Sea God - Quad Bridges Upper Ridges"
    ShrineOfTheSeaGod_SkippingStones_DeadEnd= "Shrine of the Sea God - Skipping Stones Dead End"
    ShrineOfTheSeaGod_Quad_Bridge_Dropped_Area= "Shrine of the Sea God - Quad Bridges Dropped Area"
    ShrineOfTheSeaGod_Djinn_Footsteps_Area = "Shrine of the Sea God - Foot Steps Area"
    ShrineOfTheSeaGod_Djinn_Fleeing_Bridge = "Shrine of the Sea God - Djinn Fleeing Bridge"
    ShrineOfTheSeaGod_Djinn_Torch_Corner = "Shrine of the Sea God - Djinn Torch Corner"
    ShrineOfTheSeaGod_NearDjinn_Frost_Ledge = "Shrine of the Sea God - Near Djinn Frost Ledge"
    ShrineOfTheSeaGod_OceansView = "Shrine of the Sea God - Oceans View"
    ShrineOfTheSeaGod_RushingWaterBridges = "Shrine of the Sea God - Rushing Water Bridges"
    ShrineOfTheSeaGod_RushingWaterLash = "Shrine of the Sea God - Rushing Water Near Lash Rope"
    ShrineOfTheSeaGod_QuadBridgeWestLedge = "Shrine of the Sea God - Quad Bridges Western Ledge"
    ShrineOfTheSeaGod_WateryShrineInWater = "Shrine of the Sea God - Skipping Stones to Shrine"
    ShrineOfTheSeaGod_ElevatedShrine = "Shrine of the Sea God - Elevated Shrine Area"
    ShrineOfTheSeaGod_UpperTowerArea = "Shrine of the Sea God - Upper Shrine Area"
    ShrineOfTheSeaGod_TopOfTheShrine = "Shrine of the Sea God - Top of the Shrine"

    #Kandorean Temple
    KandoreanTemple_Outside_OuterEdge = "Kandorean Temple - Outside Outer Gates"
    KandoreanTemple_WellPathway = "Kandorean Temple - Well pathway"
    KandoreanTemple_Outside_Templegrounds = "Kandorean Temple - Outside Temple Grounds"
    KandoreanTemple_PreChallenge_Lobby = "Kandorean Temple - Pre-Challenge Lobby"
    KandoreanTemple_PreChallenge_DropDownLedge = "Kandorean Temple - Pre-Challenge Drop Down Ledge"
    KandoreanTemple_PreChallenge_LashLedge = "Kandorean Temple - Pre-Challenge Lash Ledge"
    KandoreanTemple_Challenge_Entry_Room = "Kandorean Temple - Challenge Entry Room"
    KandoreanTemple_Challenge_ZigZagColumns_Room = "Kandorean Temple - Challenge Zigzag Columns Area"
    KandoreanTemple_Challenge_CliffsEdge = "Kandorean Temple - Challenge Cliffs Edge Area"
    KandoreanTemple_Challenge_WaterStream = "Kandorean Temple - Challenge Water Stream Area"
    KandoreanTemple_Challenge_GeyserPuzzles = "Kandorean Temple - Challenge Geyser Puzzle Area"
    KandoreanTemple_Challenge_TightRopeIsolated = "Kandorean Temple - Challenge East Geyser Upper Area"
    KandoreanTemple_Challenge_TightRopeArea = "Kandorean Temple - Challenge Tight Rope Area"
    KandoreanTemple_Challenge_GeyserPuzzleLedgeArea = "Kandorean Temple - Challenge Geyser Puzzle Ledge Area"
    KandoreanTemple_Challenge_DjinnRoom = "Kandorean Temple - Challenge Djinn Room"
    KandoreanTemple_Challenge_StairWell = "Kandorean Temple - Challenge Stairwell"
    KandoreanTemple_Challenge_BurningPotRoom = "Kandorean Temple - Challenge Burning Pot Room"
    KandoreanTemple_Challenge_PurpleHallway = "Kandorean Temple - Challenge Purple Hallway"
    KandoreanTemple_Challenge_MastersRoom = "Kandorean Temple - Challenge Masters Room"

    #Dehkan Platea
    DehkanPlateau_TripleStairs = "Dehkan Plateau - Triple Stair Entry"
    DehkanPlateau_AboveTripleStairs = "Dekhan Plateau - Above Triple Stairs"
    DehkanPlateau_IsolatedNearTripleStairs = "Dekhan Plateau - Isolated Ledge Near Triple Stairs"
    DehkanPlateau_HorizontalOvalShapedCavern = "Dekhan Plateau - Horizontal Oval Shaped Cavern"

    DehkanPlateau_TripleStonePillars = "Dekhan Plateau - Triple Stone Pillars"
    DehkanPlateau_StonePillarsLogLedge = "Dehkan Plateau - Triple Stone Pillars Log Ledge"
    DehkanPlateau_TeasingCavernLowerSide = "Dekhan Plateau - Teasing Item Cavern Lower Side"
    DehkanPlateau_TeasingCavernUpperSide = "Dekhan Plateau - Teasing Item Cavern Upper Side"
    DehkanPlateau_UShapedCavern = "Dekhan Plateau - U Shaped Cavern"

    DehkanPlateau_StonePillarMaze = "Dekhan Plateau - Stone Pillar Maze"

    DehkanPlateau_CrackedFloorsRockSlide = "Dekhan Plateau - Cracked Floors near Rockslides"
    DehkanPlateau_BalloonCavern = "Dekhan Plateau - Balloon Shaped Cavern"
    DehkanPlateau_MirrorJCavern = "Dekhan Plateau - Mirrored J Shaped Cavern"
    DehkanPlateau_IsolatedCrackedFloors = "Dekhan Plateau - Isolated Cracked Floors Area"
    DehkanPlateau_SideEyeCavern = "Dekhan Plateau - SideEye Shaped Cavern"
    DehkanPlateau_RockslideArea = "Dekhan Plateau - Rockslide Area"

    DehkanPlateau_RopeBridgeArea = "Dekhan Plateau - Rope Bridge Area"
    DehkanPlateau_RopeBridgeCrackedFloorArea = "Dekhan Plateau - Rope Bridge Cracked Floors Area"
    DehkanPlateau_BottleCavern = "Dekhan Plateau - Bottle Shaped Cavern"
    DehkanPlateau_BelowRopeBridgeArea = "Dekhan Plateau - Below Rope Bridge Area"

    DehkanPlateau_CrampedWesternLedge = "Dekhan Plateau - Cramped Western Ledge"
    DehkanPlateau_MiddleLedgeBetweenStonePillars = "Dekhan Plateau - Middle Ledge Between Stone Pillars Area"
    DehkanPlateau_ThreeAngledCavern = "Dekhan Plateau - Three-Angled Cavern"
    DehkanPlateau_CrackedFloorCavernLowerHalf = "Dekhan Plateau - Cracked Floors Cavern Lower Half"
    DehkanPlateau_CrackedFloorCavernCrackedFloor = "Dekhan Plateau - Cracked Floors Cavern Cracked Floor Area"
    DehkanPlateau_CrackedFloorCavernDjinnDropDown = "Dekhan Plateau - Cracked Floors Cavern Djinn DropDown Spot"
    DehkanPlateau_CrackedFloorCavernUpperHalf = "Dekhan Plateau -  Cracked Floors Cavern Upper Half"

    DehkanPlateau_DeepCavernDropDownArea = "Dekhan Plateau - Deep Cavern Drop Down Area"
    DehkanPlateau_PoundPillarCavernUpperHalf = "Dekhan Plateau - Pound Pillar Cavern Upper Half"
    DehkanPlateau_PoundPillarCavernLowerHalf = "Dekhan Plateau - Pound Pillar Cavern Lower Half"

    DehkanPlateau_CrackedFloorsNorthOfCrackedPillar = "Dekhan Plateau - Cracked Floors North of Cracked Stone Pillar"
    DehkanPlateau_DeepCavernUpperLedge = "Dekhan Plateau - Deep Cavern Upper Ledge"

    DehkanPlateau_DjinnCombatCavern = "Dekhan Plateau - Djinn Combat Cavern"
    DehkanPlateau_FlatHallwayCavern = "Dekhan Plateau - Flat Hallway Cavern"
    DehkanPlateau_QuadStairs = "Dekhan Plateau - Quad Stairs Entry"

    #Madra
    Madra = "Indra - Madra"

    #Madra Catacombs
    MadraCatacombsLadderRoomEast = "Madra Catacombs - Eastern Laddern Room"
    MadraCatacombsLadderRoomWest = "Madra Catacombs - Western Laddern Room"
    MadraCatacombsEastConnectorRoom = "Madra Catacombs - Eastern Connector Room"
    MadraCatacombsRockBlockedRoom = "Madra Catacombs - Eastern Rock Blocked Room"
    MadraCatacombsRockLedgeEastRidge = "Madra Catacombs - Eastern Rocky Ledge"
    MadraCatacombsRockLedgeWestRidge = "Madra Catacombs - Western Rocky Ledge"
    MadraCatacombs_RuinsEntry = "Madra Catacombs - Ruins Entry"
    MadraCatacombsMainRuinsArea = "Madra Catacombs - Main Ruins Area"
    MadraCatacombsBackRuinsArea = "Madra Catacombs - Back Ruins Area"
    MadraCatacombsUpperRuinsArea = "Madra Catacombs - Upper Ruins Area"
    MadraCatacombsRuinedBuilding_EasternHallway_EasternLedge = "Madra Catacombs - Eastern Hallway - Eastern Ledge"
    MadraCatacombsRuinedBuilding_TightRidge = "Madra Catacombs - Basement Tight Ridge"
    MadraCatacombsRuinedBuilding_TremorRoom = "Madra Catacombs - Basement TremorBit Room"
    MadraCatacombsRuinedBuilding_EntryHall = "Madra Catacombs - Entry Hall"
    MadraCatacombsRuinedBuilding_CollapsedHall_SouthSide = "Madra Catacombs - Collapsed Hallway Southside"
    MadraCatacombsRuinedBuilding_CentralRoom = "Madra Catacombs - Central Room"
    MadraCatacombsRuinedBuilding_MainUpstairsEastArea = "Madra Catacombs - Main Upstairs - East Side"
    MadraCatacombsRuinedBuilding_EastBedroom = "Madra Catacombs - Upstairs Eastern Bedroom"
    MadraCatacombsRuinedBuilding_EasternHallway_WesternLedge = "Madra Catacombs - Eastern Hallway - Western Ledge"
    MadraCatacombsRuinedBuilding_LockedRoom = "Madra Catacombs - Locked Room"
    MadraCatacombsRuinedBuilding_LongHallway = "Madra Catacombs - Upstairs Longhallway"
    MadraCatacombsRuinedBuilding_CollapsedHall_NorthSide = "Madra Catacombs - Collapsed Hallway Northside"
    MadraCatacombsRuinedBuilding_MainUpstairsWestArea = "Madra Catacombs - Main Upstairs - West Side"
    MadraCatacombsRuinedBuilding_WestBedroom = "Madra Catacombs - Upstairs Western Bedroom"


    #Indra Cavern
    IndraCavern = "Indra - Indra Cavern"

    #Madra Drawbridge
    MadraDrawBridge = "Indra - Madra Drawbridge"

    #Osenia
    Oseania_SouthWesternOsenia = "Overworld - SouthWestern Osenia"
    Oseania_AlhafraArea = "Overworld - Osenia Alhafra Area"
    OseniaCliffs = "Osenia Cliffs"
    YampiDesertFront = "Yampi Desert Front"
    YampiDesertBack = "Yampi Desert Back"
    Alhafra = "Alhafra"
    Mikasalla = "Mikasalla"
    Garoh = "Garoh"
    AirsRock = "AirsRock"
    OseniaCavern = "Osenia Cavern"


    #Gondowan
    GondowanCliffs = "Gondowan Cliffs"
    Gondowan_SouthernGondowan = "Overworld - Southern Gondowan"
    Gondowan_CentralGondowan = "Overworld - Central Gondowan"
    Gondowan_WesternGondowan = "Overworld - Western Gondowan"
    Naribwe = "Naribwe"
    KibomboMountains = "Kibombo Mountains"
    Kibombo = "Kibombo"
    GabombaStatue = "Gabomba Statue"
    GabombaCatacombs = "Gabomba Catacombs"


    #Eastern Sea
    Overworld_WestIndraIslet = "Overworld - West Indra Islet"
    WestIndraIslet = "West Indra Islet"
    Overworld_EastTundariaIslet = "Overworld - East Tundaria Islet"
    EastTundariaIslet = "East Tundaria Islet"
    Overworld_NorthOseniaIslet = "Overworld - North Osenia Islet"
    NorthOseniaIslet = "North Osenia Islet"
    Overworld_SouthEastAngaraIslet = "Overworld - SouthEast Angara Islet"
    SouthEastAngaraIslet = "SouthEast Angara Islet"
    Overworld_SeaOfTimeIslet = "Overworld - Sea Of Time Islet"
    SeaOfTimeIslet = "Sea Of Time Islet"
    Overworld_ApojiiIslands = "Overworld - Apojii Islands"
    ApojiiIslands = "Apojii Islands"
    Overworld_AquaRock = "Overworld - Aqua Rock"
    AquaRock = "Aqua Rock"
    Overworld_Izumo = "Overworld - Izumo"
    Izumo = "Izumo"
    GaiaRock = "Gaia Rock"
    Overworld_TreasureIsland = "Overworld - Treasure Island"
    TreasureIsland = "Treasure Island"
    Overworld_Tundaria = "Overworld - Tundaria"
    TundariaTower = "Tundaria Tower"
    TundariaTower_Parched = "Tundaria Tower Parched"
    Overworld_SouthEasternAngara = "Overworld - SouthEastern Angara"
    AnkohlRuins = "Ankohl Ruins"
    AnkohlRuins_Sand = "Ankohl Ruins Sand"
    Overworld_SouthernAngara = "Overworld - Southern Angara"
    Champa = "Champa"
    Overworld_SouthEasternOsenia = "Overworld - SouthEastern Osenia"
    Yallam = "Yallam"
    Overworld_NorthEasternOsenia = "Overworld - NorthEastern Osenia"
    TaopoSwamp = "Taopo Swamp"
    SouthWestAttekaIslet = "South West Atteka Islet"
    Overworld_SouthWestAttekaIslet = "Overworld - South West Atteka Islet"
    KaltIsland = "Kalt Island"
    Overworld_KaltIsland = "Overworld - Kalt Island"
    GondowanSettlement = "Gondowan Settlement"
    MagmaRock = "Magma Rock"
    Overworld_WesternAngara = "Overworld - Western Angara"
    Overworld_NeHesperia = "Overworld - NorthEastern Hesperia"
    Overworld_WesternHesperia = "Overworld - Western Hesperia"
    Overworld_CentralHesperia = "Overworld - Central Hesperia"
    Overworld_ShamanHesperia = "Overworld - Hesperia Shamen Village Area"
    Overworld_WesternAtteka = "Overworld - Western Atteka"
    Overworld_CentralAtteka = "Overworld - Central Atteka"
    Overworld_SouthernAtteka = "Overworld - Southern Atteka"
    Loho = "Loho"
    AngaraCavern = "Angara Cavern"    
    ShamanVillageCave = "Shaman Village Cave"
    ShamanVillage = "Shaman Village"
    HesperiaSettlement = "Hesperia Settlement"
    AttekaInlet = "Atteka Inlet"
    AttekaCavern = "Atteka Cavern"
    Contigo = "Contigo"
    JupiterLighthouse = "Jupiter Lighthouse"

    Overworld_Lower_NorthernReaches = "Overworld - Lower Northern Reaches"
    Prox = "Prox"
    Overworld_Upper_NorthernReaches = "Overworld - Upper Northern Reaches"
    MarsLighthouse = "Mars Lighthouse"



    SeaOfTime = "Sea Of Time"
    Lemuria = "Lemuria"
    PreShipLand = "PreShipLand"
    TreasureIsland_Grindstone = "Treasure Island - Grindstone"
    TreasureIsland_PostReunion = "TreasureIsland - PostReunion"
    MagmaRockInterior = "Magma Rock Interior"
    AnemosSanctum = "Anemos Sanctum"
    MarsLighthouse_Activated = "MarsLighthouse Activated"
    IsletCave = "Islet Cave"
    YampiDesertCave = "Yampi Desert Cave"
    AlhafraCave = "Alhafra Cave"
    Lemurian_Ship = "Lemurian Ship"
    Lemurian_Ship_Revisit = "Lemurian Ship - Revisit"
    Reunion = "Reunion"
    PartyMembers = "Party Members"