class RegionName():
    Menu = "Menu"

    #Overworld
    EasternSea = "Eastern Sea"
    WesternSea = "Western Sea"


    #Indra
    Indra_IdejimaArea = "Overworld - Indra Idejima Area"
    Indra_NorthernIndra = "Overworld - Northern Indra"
    Indra_SouthernIndra = "Overworld - Southern Indra"
    Indra_MadraDrawBridgeArea = "Overworld - Madra Drawbridge Area"
    Indra_Idejima = "Indra - Idejima"
    Indra_Daila = "Indra - Daila"
    Indra_ShrineOfTheSeaGod = "Indra - Shrine of the Sea God"
    Indra_KandoreanTemple = "Indra - Kandorean Temple"
    Indra_DehkanPlateau = "Indra - Dehkan Plateau"
    Madra = "Indra - Madra"
    MadraCatacombs = "Indra - Madra - Madra Catacombs"
    IndraCavern = "Indra - Indra Cavern"
    MadraDrawBridge = "Indra - Madra Drawbridge"

    #Osenia
    Oseania_SouthWesternOsenia = "Overworld - SouthWestern Osenia"
    Oseania_AlhafraArea = "Overworld - Osenia Alhafra Area"
    OseniaCliffs = "Osenia Cliffs"
    YampiDesertFront = "Yampi Desert Front"
    YampiDesertBack = "Yampi Desert Back"
    Alhafra = "Alhafra"
    Mikasalla = "Mikasalla"
    Garoh = "Garoh"
    AirsRock = "AirsRock"
    OseniaCavern = "Osenia Cavern"


    #Gondowan
    GondowanCliffs = "Gondowan Cliffs"
    Gondowan_SouthernGondowan = "Overworld - Southern Gondowan"
    Gondowan_CentralGondowan = "Overworld - Central Gondowan"
    Gondowan_WesternGondowan = "Overworld - Western Gondowan"
    Naribwe = "Naribwe"
    KibomboMountains = "Kibombo Mountains"
    Kibombo = "Kibombo"
    GabombaStatue = "Gabomba Statue"
    GabombaCatacombs = "Gabomba Catacombs"


    #Eastern Sea
    Overworld_WestIndraIslet = "Overworld - West Indra Islet"
    WestIndraIslet = "West Indra Islet"
    Overworld_EastTundariaIslet = "Overworld - East Tundaria Islet"
    EastTundariaIslet = "East Tundaria Islet"
    NorthOseniaIslet = "North Osenia Islet"
    SouthEastAngaraIslet = "SouthEast Angara Islet"
    SeaOfTimeIslet = "Sea Of Time Islet"
    ApojiiIslands = "Apojii Islands"
    AquaRock = "Aqua Rock"
    Izumo = "Izumo"
    GaiaRock = "Gaia Rock"
    TreasureIsland = "Treasure Island"

    SouthernAngara = "Southern Angara"
    Champa = "Champa"
    AnkohlRuins = "Ankohl Ruins"
    AnkohlRuins_Sand = "Ankohl Ruins Sand"
    Yallam = "Yallam"
    TaopoSwamp = "Taopo Swamp"
    TundariaTower = "Tundaria Tower"
    TundariaTower_Parched = "Tundaria Tower Parched"
    SeaOfTime = "Sea Of Time"
    Lemuria = "Lemuria"
    PreShipLand = "PreShipLand"
    TreasureIsland_Grindstone = "Treasure Island - Grindstone"
    TreasureIsland_PostReunion = "TreasureIsland - PostReunion"
    GondowanSettlement = "Gondowan Settlement"
    MagmaRock = "Magma Rock"
    MagmaRockInterior = "Magma Rock Interior"
    Loho = "Loho"
    AngaraCavern = "Angara Cavern"
    ShamanVillageCave = "Shaman Village Cave"
    ShamanVillage = "Shaman Village"
    HesperiaSettlement = "Hesperia Settlement"
    AttekaInlet = "Atteka Inlet"
    AttekaCavern = "Atteka Cavern"
    Contigo = "Contigo"
    JupiterLighthouse = "Jupiter Lighthouse"
    AnemosSanctum = "Anemos Sanctum"
    SouthWestAttekaIslet = "South West Atteka Islet"
    KaltIsland = "Kalt Island"
    Prox = "Prox"
    MarsLighthouse = "Mars Lighthouse"
    MarsLighthouse_Activated = "MarsLighthouse Activated"
    IsletCave = "Islet Cave"
    YampiDesertCave = "Yampi Desert Cave"
    AlhafraCave = "Alhafra Cave"
    Lemurian_Ship = "Lemurian Ship"
    Lemurian_Ship_Revisit = "Lemurian Ship - Revisit"
    Reunion = "Reunion"
    PartyMembers = "Party Members"