from typing import List
from BaseClasses import MultiWorld, EntranceType
from .Names.RegionName import RegionName
from .Names.EntranceName import EntranceName
from .GstlaTypes import EntranceData, ERTestGroups

vanilla_connections: List[EntranceData] = \
[
    EntranceData(EntranceName.Menu_StartGame, RegionName.Indra_Idejima),
    EntranceData(EntranceName.AnywhereToJoinedPartyMembers, RegionName.PartyMembers),

    #Overworld
    EntranceData(EntranceName.Overworld_To_Daila_NorthSide, RegionName.Indra_Daila, '2:3', ERTestGroups.SOUTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_To_Daila_SouthSide, RegionName.Indra_Daila, '2:2', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_To_KandoreanTemple, RegionName.Indra_KandoreanTemple, '2:4', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_To_ShrineOfTheSeaGod, RegionName.Indra_ShrineOfTheSeaGod, '2:5', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_To_DehkanPlateau_NorthWestSide, RegionName.Indra_DehkanPlateau, '2:6',  ERTestGroups.EAST | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_To_DehkanPlateau_SouthEastSide, RegionName.Indra_DehkanPlateau, '2:7',  ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_To_IndraCavern, RegionName.IndraCavern, '2:83', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_To_Madra, RegionName.Madra, '2:9', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_To_GondowanCliffs_EastSide, RegionName.GondowanCliffs, '2:22', ERTestGroups.WEST | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_To_MadraDrawbridge_SouthSide, RegionName.MadraDrawBridge, '2:10', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_To_MadraDrawbridge_NorthSide, RegionName.MadraDrawBridge, '2:11', ERTestGroups.SOUTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_To_OseniaCliffs_WestSide, RegionName.OseniaCliffs, '2:12', ERTestGroups.EAST | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_To_OseniaCliffs_EastSide, RegionName.OseniaCliffs, '2:13', ERTestGroups.WEST | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_To_Mikasalla, RegionName.Mikasalla, '2:14', ERTestGroups.WEST | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_To_OseniaCavern, RegionName.OseniaCavern, '2:82', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_To_Garoh, RegionName.Garoh, '2:15', ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_To_AirsRock, RegionName.AirsRock, '2:16', ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_To_YampiDesertFront, RegionName.YampiDesertFront, '2:17', ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_Garoh_To_YampiDesertBack, RegionName.YampiDesertBack, '2:19', ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_Alhafra_To_YampiDesertBack, RegionName.YampiDesertBack, '2:18', ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_To_Alhafra, RegionName.Alhafra, '2:20', ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_To_GondowanCliffs_WestSide, RegionName.GondowanCliffs, '2:21', ERTestGroups.EAST | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_To_Naribwe_SouthSide, RegionName.Naribwe, '2:23', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_To_Naribwe_NorthSide, RegionName.Naribwe, '2:24', ERTestGroups.SOUTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_To_KibomboMountains_SouthSide, RegionName.KibomboMountains, '2:25', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_To_KibomboMountains_NorthSide, RegionName.KibomboMountains, '2:26', ERTestGroups.SOUTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_To_Kibombo, RegionName.Kibombo, '2:27', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_WestIndraIslet_To_WestIndraIslet, RegionName.WestIndraIslet, '2:28', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_EastTundariaIslet_To_EastTundariaIslet, RegionName.EastTundariaIslet, '2:29', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_NorthOseniaIslet_To_NorthOseniaIslet, RegionName.NorthOseniaIslet, '2:30', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_SouthEastAngaraIslet_To_SouthEastAngaraIslet, RegionName.SouthEastAngaraIslet, '2:31', ERTestGroups.WEST | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_SeaOfTimeIslet_To_SeaOfTimeIslet, RegionName.SeaOfTimeIslet, '2:32', ERTestGroups.SOUTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_ApojiiIslands_To_ApojiIslands, RegionName.ApojiiIslands, '2:36', ERTestGroups.EAST | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_AquaRock_To_AquaRock, RegionName.AquaRock, '2:37', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_Izumo_To_Izumo, RegionName.Izumo, '2:38', ERTestGroups.EAST | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_Izumo_To_GaiaRock, RegionName.GaiaRock, '2:39', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_TreasureIsland_To_TreasureIsland, RegionName.TreasureIsland, '2:87', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_Tundaria_To_TundariaTower, RegionName.TundariaTower, '2:46', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_SEAngara_To_AnkohlRuins, RegionName.AnkohlRuins, '2:41', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_SouthernAngara_To_Champa, RegionName.Champa, '2:40', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_SouthEastOsenia_To_YallamSouth, RegionName.Yallam, '2:34', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_NorthEastOsenia_To_YallamNorth, RegionName.Yallam, '2:33', ERTestGroups.SOUTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_NorthEastOsenia_To_TaopoSwamp, RegionName.TaopoSwamp, '2:35', ERTestGroups.EAST | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_SouthWestAttekaIslet_To_SouthWestAttekaIslet, RegionName.SouthWestAttekaIslet, '2:47', ERTestGroups.WEST | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_KaltIsland_To_KaltIsland, RegionName.KaltIsland, '2:50', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_WestGondowan_To_GondowanSettlement, RegionName.GondowanSettlement, '2:48', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_WestGondowan_To_MagmaRock, RegionName.MagmaRock, '2:51', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_WestAngara_To_Loho, RegionName.Loho, '2:59', ERTestGroups.EAST | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_WestAngara_To_AngaraCavern, RegionName.AngaraCavern, '2:89', ERTestGroups.EAST | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_WeHesperia_HesperiaSettlement, RegionName.HesperiaSettlement, '2:49', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_CentralHesperia_To_ShamanVillageCave, RegionName.ShamanVillageCave, '2:56', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_ShamanHesperia_To_ShamanVillageCave, RegionName.ShamanVillageCave, '2:57', ERTestGroups.WEST | ERTestGroups.OW_WALK),
    EntranceData(EntranceName.Overworld_ShamanHesperia_To_ShamanVillage, RegionName.ShamanVillage, '2:58', ERTestGroups.NORTH | ERTestGroups.OW_WALK),

    #Indra
    EntranceData(EntranceName.Idejima_To_Overworld, RegionName.Indra_IdejimaArea, '9:4', ERTestGroups.WEST | ERTestGroups.SCREEN_EDGE_WALK, EntranceType.ONE_WAY),
    EntranceData(EntranceName.Daila_North_To_Overworld, RegionName.Indra_IdejimaArea, '13:9', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.Daila_South_To_Overworld, RegionName.Indra_NorthernIndra, '13:8', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.KandoreanTemple_To_Overworld, RegionName.Indra_NorthernIndra, '21:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.ShrineOfTheSeaGod_To_Overworld, RegionName.Indra_NorthernIndra, '23:3', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.DehkanPlateau_West_To_Overworld, RegionName.Indra_NorthernIndra, '34:1', ERTestGroups.WEST | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.DehkanPlateau_East_To_Overworld, RegionName.Indra_SouthernIndra, '36:6', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.IndraCavern_To_Overworld, RegionName.Indra_SouthernIndra, '275:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.Madra_To_Overworld, RegionName.Indra_SouthernIndra, '44:11', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.GondowanCliffs_East_To_Overworld, RegionName.Indra_SouthernIndra, '102:2', ERTestGroups.EAST | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.MadraDrawbridge_South_To_Overworld, RegionName.Indra_SouthernIndra, '53:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.MadraDrawbridge_North_To_Overworld, RegionName.Indra_MadraDrawBridgeArea, '53:2', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.OseniaCliffs_West_To_Overworld, RegionName.Indra_MadraDrawBridgeArea, '54:1', ERTestGroups.WEST | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.OseniaCliffs_East_To_Overworld, RegionName.Oseania_SouthWesternOsenia, '54:2', ERTestGroups.EAST | ERTestGroups.SCREEN_EDGE_WALK),

    #Osenia
    EntranceData(EntranceName.Mikasalla_To_Overworld, RegionName.Oseania_SouthWesternOsenia, '55:6', ERTestGroups.EAST | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.OseniaCavern_To_Overworld, RegionName.Oseania_SouthWesternOsenia, '276:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.Garoh_To_Overworld, RegionName.Oseania_SouthWesternOsenia, '61:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.AirsRock_To_Overworld, RegionName.Oseania_SouthWesternOsenia, '82:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.YampiDesertBack_To_Overworld_Garoh, RegionName.Oseania_SouthWesternOsenia, '75:2', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.YampDesertFront_To_Overworld, RegionName.Oseania_SouthWesternOsenia, '67:1', ERTestGroups.WEST | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.YampiDesertBack_To_Overworld_Alhafra, RegionName.Oseania_AlhafraArea, '74:2', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.Alhafra_To_Overworld, RegionName.Oseania_AlhafraArea, '95:9', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
 
    #Gondowan
    EntranceData(EntranceName.GondowanCliffs_West_To_Overworld, RegionName.Gondowan_SouthernGondowan, '102:1', ERTestGroups.WEST | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.Naribwe_South_To_Overworld, RegionName.Gondowan_SouthernGondowan, '105:6', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.Naribwe_North_To_Overworld, RegionName.Gondowan_SouthernGondowan, '105:7', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.KibomboMountains_South_To_Overworld, RegionName.Gondowan_SouthernGondowan, '108:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.KibomboMountains_NorthWest_To_Overworld, RegionName.Gondowan_CentralGondowan, '107:1', ERTestGroups.WEST | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.Kibombo_To_Overworld, RegionName.Gondowan_CentralGondowan, '113:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),


    #Eastern Sea
    EntranceData(EntranceName.Overworld_Indra_North_To_EasternSea, RegionName.EasternSea),
    EntranceData(EntranceName.Overworld_Indra_South_To_EasternSea, RegionName.EasternSea),
    EntranceData(EntranceName.Overworld_Oseania_AlhafraArea_To_EasternSea, RegionName.EasternSea),
    EntranceData(EntranceName.Overworld_Gondowan_Central_To_EasternSea, RegionName.EasternSea),
    EntranceData(EntranceName.Overworld_Gondowan_South_To_EasternSea, RegionName.EasternSea),
    EntranceData(EntranceName.Overworld_WestIndraIslet_To_EasternSea, RegionName.EasternSea),
    EntranceData(EntranceName.Overworld_EastTundariaIslet_To_EasternSea, RegionName.EasternSea),
    EntranceData(EntranceName.Overworld_NorthOseniaIslet_To_EasternSea, RegionName.EasternSea),
    EntranceData(EntranceName.Overworld_SouthEastAngaraIslet_To_EasternSea, RegionName.EasternSea),
    EntranceData(EntranceName.Overworld_SeaOfTimeIslet_To_EasternSea, RegionName.EasternSea),
    EntranceData(EntranceName.Overworld_ApojiiIslands_To_EasternSea, RegionName.EasternSea),
    EntranceData(EntranceName.Overworld_AquaRock_To_EasternSea, RegionName.EasternSea),
    EntranceData(EntranceName.Overworld_Izumo_To_EasternSea, RegionName.EasternSea),
    EntranceData(EntranceName.Overworld_TreasureIsland_To_EasternSea, RegionName.EasternSea),
    EntranceData(EntranceName.Overworld_Tundaria_To_EasternSea, RegionName.EasternSea),
    EntranceData(EntranceName.Overworld_SEAngara_To_EasternSea, RegionName.EasternSea),
    EntranceData(EntranceName.Overworld_SouthernAngara_To_EasternSea, RegionName.EasternSea),
    EntranceData(EntranceName.Overworld_SouthEastOsenia_To_EasternSea, RegionName.EasternSea),

    EntranceData(EntranceName.Overworld_EasternSea_To_Indra_North, RegionName.Indra_NorthernIndra),
    EntranceData(EntranceName.Overworld_EasternSea_To_Indra_South, RegionName.Indra_SouthernIndra),
    EntranceData(EntranceName.Overworld_EasternSea_To_Osenia_AlhafraArea, RegionName.Oseania_AlhafraArea),
    EntranceData(EntranceName.Overworld_EasternSea_To_Gondowan_Central, RegionName.Gondowan_CentralGondowan),
    EntranceData(EntranceName.Overworld_EasternSea_To_Gondowan_South, RegionName.Gondowan_SouthernGondowan),
    EntranceData(EntranceName.Overworld_EasternSea_To_WestIndraIslet, RegionName.Overworld_WestIndraIslet),
    EntranceData(EntranceName.Overworld_EasternSea_To_EastTundariaIslet, RegionName.Overworld_EastTundariaIslet),
    EntranceData(EntranceName.Overworld_EasternSea_To_NorthOseniaIslet, RegionName.Overworld_NorthOseniaIslet),
    EntranceData(EntranceName.Overworld_EasternSea_To_SouthEastAngaraIslet, RegionName.Overworld_SouthEastAngaraIslet),
    EntranceData(EntranceName.Overworld_EasternSea_To_SeaOfTimeIslet, RegionName.Overworld_SeaOfTimeIslet),
    EntranceData(EntranceName.Overworld_EasternSea_To_ApojiiIslands, RegionName.Overworld_ApojiiIslands),
    EntranceData(EntranceName.Overworld_EasternSea_To_AquaRock, RegionName.Overworld_AquaRock),
    EntranceData(EntranceName.Overworld_EasternSea_To_Izumo, RegionName.Overworld_Izumo),
    EntranceData(EntranceName.Overworld_EasternSea_To_TreasureIsland, RegionName.Overworld_TreasureIsland),
    EntranceData(EntranceName.Overworld_EasternSea_To_Tundaria, RegionName.Overworld_Tundaria),
    EntranceData(EntranceName.Overworld_EasternSea_To_SEAngara, RegionName.Overworld_SouthEasternAngara),
    EntranceData(EntranceName.Overworld_EasternSea_To_SouthernAngara, RegionName.Overworld_SouthernAngara),
    EntranceData(EntranceName.Overworld_EasternSea_To_SouthEastOsenia, RegionName.Overworld_SouthEasternOsenia),

    EntranceData(EntranceName.WestIndraIslet_To_Overworld, RegionName.Overworld_WestIndraIslet, '131:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.EastTundariaIslet_To_Overworld, RegionName.Overworld_EastTundariaIslet, '132:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.NorthOseniaIslet_To_Overworld, RegionName.Overworld_NorthOseniaIslet, '133:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.SouthEastAngaraIslet_To_Overworld, RegionName.Overworld_SouthEastAngaraIslet, '134:10', ERTestGroups.WEST | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.SeaOfTimeIslet_To_Overworld, RegionName.Overworld_SeaOfTimeIslet, '135:1', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.ApojiiIslands_To_Overworld, RegionName.Overworld_ApojiiIslands, '154:1', ERTestGroups.WEST | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.AquaRock_To_Overworld, RegionName.Overworld_AquaRock, '158:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.Izumo_To_Overworld, RegionName.Overworld_Izumo, '171:1', ERTestGroups.WEST | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.GaiaRock_To_Overworld, RegionName.Overworld_Izumo, '174:5', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.TreasureIsland_To_Overworld, RegionName.Overworld_TreasureIsland, '298:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.TundariaTower_To_Overworld, RegionName.Overworld_Tundaria, '206:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.AnkohlRuins_To_Overworld, RegionName.Overworld_SouthEasternAngara, '195:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.Champa_To_Overworld, RegionName.Overworld_SouthernAngara, '182:9', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.YallamSouth_To_Overworld, RegionName.Overworld_SouthEasternOsenia, '139:10', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.YallamNorth_To_Overworld, RegionName.Overworld_NorthEasternOsenia, '139:11', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.TaopoSwamp_To_Overworld, RegionName.Overworld_NorthEasternOsenia, '143:1', ERTestGroups.WEST | ERTestGroups.SCREEN_EDGE_WALK),

    #Western Sea
    EntranceData(EntranceName.Overworld_WesternSea_To_SouthWestAttekaIslet, RegionName.Overworld_SouthWestAttekaIslet),
    EntranceData(EntranceName.Overworld_WesternSea_To_KaltIsland, RegionName.Overworld_KaltIsland),
    EntranceData(EntranceName.Overworld_WesternSea_To_WestGondowan, RegionName.Gondowan_WesternGondowan),
    EntranceData(EntranceName.Overworld_WesternSea_To_WesternAngara, RegionName.Overworld_WesternAngara),
    EntranceData(EntranceName.Overworld_WesternSea_To_NeHesperia, RegionName.Overworld_NeHesperia),
    EntranceData(EntranceName.Overworld_WesternSea_To_WestHesperia, RegionName.Overworld_WesternHesperia),
    EntranceData(EntranceName.Overworld_WesternSea_To_CentralHesperia, RegionName.Overworld_CentralHesperia),

    EntranceData(EntranceName.Overworld_SouthWestAttekaIslet_To_WesternSea, RegionName.WesternSea),
    EntranceData(EntranceName.Overworld_KaltIsland_To_WesternSea, RegionName.WesternSea),
    EntranceData(EntranceName.Overworld_WestGondowan_To_WesternSea, RegionName.WesternSea),
    EntranceData(EntranceName.Overworld_WesternAngara_To_WesternSea, RegionName.WesternSea),
    EntranceData(EntranceName.Overworld_WesternHesperia_To_WesternSea, RegionName.WesternSea),
    EntranceData(EntranceName.Overworld_CentralHesperia_To_WesternSea, RegionName.WesternSea),

    EntranceData(EntranceName.SouthWestAttekaIslet_To_Overworld, RegionName.Overworld_SouthWestAttekaIslet, '221:1', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.KaltIsland_To_Overworld, RegionName.Overworld_KaltIsland, '219:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.GondowanSettlement_To_Overworld, RegionName.Gondowan_WesternGondowan, '213:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.MagmaRock_To_Overworld, RegionName.Gondowan_WesternGondowan, '223:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.Loho_To_Overworld, RegionName.Overworld_WesternAngara, '266:1', ERTestGroups.WEST | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.AngaraCavern_To_Overworld, RegionName.Overworld_WesternAngara, '278:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.HesperiaSettlement_To_Overworld, RegionName.Overworld_WesternHesperia, '216:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.ShamanVillageCave_SouthWest_To_Overworld, RegionName.Overworld_CentralHesperia, '240:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.ShamanVillageCave_East_To_Overworld, RegionName.Overworld_ShamanHesperia, '240:10', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceData(EntranceName.ShamanVillage_To_Overworld, RegionName.Overworld_ShamanHesperia, '242:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),



    EntranceData(EntranceName.MadraToMadraCatacombs, RegionName.MadraCatacombs),
    EntranceData(EntranceName.MadraToLemurianShip, RegionName.Lemurian_Ship),
    EntranceData(EntranceName.YampiDesertFrontToYampiDesertBack, RegionName.YampiDesertBack),
    EntranceData(EntranceName.YampiDesertBackToYampiDesertCave, RegionName.YampiDesertCave),
    EntranceData(EntranceName.AlhafraToAlhafraCave, RegionName.AlhafraCave),
    EntranceData(EntranceName.KibomboToGabombaStatue, RegionName.GabombaStatue),
    EntranceData(EntranceName.GabombaStatueToGabombaCatacombs, RegionName.GabombaCatacombs),
    EntranceData(EntranceName.EasternSeaToSeaOfTime, RegionName.SeaOfTime),
    EntranceData(EntranceName.EasternSeaToWesternSea, RegionName.WesternSea),
    EntranceData(EntranceName.SeaOfTimeIsletToIsletCave, RegionName.IsletCave),
    EntranceData(EntranceName.TreasureIslandToTreasureIsland_Grindstone, RegionName.TreasureIsland_Grindstone),
    EntranceData(EntranceName.TreasureIsland_GrindstoneToTreasureIsland_PostReunion, RegionName.TreasureIsland_PostReunion),
    EntranceData(EntranceName.TundariaTowerToTundariaTower_Parched, RegionName.TundariaTower_Parched),
    EntranceData(EntranceName.AnkohlRuinsToAnkohlRuins_Sand, RegionName.AnkohlRuins_Sand),
    EntranceData(EntranceName.SeaOfTimeToLemuria, RegionName.Lemuria),
    EntranceData(EntranceName.LemuriaToShipRevisit, RegionName.Lemurian_Ship_Revisit),
    EntranceData(EntranceName.WesternSeaToAttekaInlet, RegionName.AttekaInlet),
    EntranceData(EntranceName.WesternSeaToAttekaCavern, RegionName.AttekaCavern),
    EntranceData(EntranceName.WesternSeaToProx, RegionName.Prox),
    EntranceData(EntranceName.AttekaInletToContigo, RegionName.Contigo),
    EntranceData(EntranceName.AttekaInletToShipRevisit, RegionName.Lemurian_Ship_Revisit),
    EntranceData(EntranceName.ContigoToJupiterLighthouse, RegionName.JupiterLighthouse),
    EntranceData(EntranceName.ContigoToAnemosInnerSanctum, RegionName.AnemosSanctum),
    EntranceData(EntranceName.ContigoToReunion, RegionName.Reunion),
    EntranceData(EntranceName.MagmaRockToMagmaRockInterior, RegionName.MagmaRockInterior),
    EntranceData(EntranceName.ProxToMarsLighthouse, RegionName.MarsLighthouse),
    EntranceData(EntranceName.MarsLighthouseToMarsLighthouse_Activated, RegionName.MarsLighthouse_Activated)
]


def create_vanilla_connections(multiworld: MultiWorld, player: int):
    for connection in vanilla_connections:
        entrance = multiworld.get_entrance(connection.source_entrance, player)
        target = multiworld.get_region(connection.target, player)

        entrance.connect(target)