from typing import List, Dict
from BaseClasses import MultiWorld, EntranceType
from .Names.RegionName import RegionName
from .Names.EntranceName import EntranceName
from .GstlaTypes import EntranceData, ERTestGroups

vanilla_connections: Dict[str, EntranceData] = {
    EntranceName.Menu_StartGame: EntranceData(EntranceName.Menu_StartGame, RegionName.Indra_Idejima),
    EntranceName.AnywhereToJoinedPartyMembers: EntranceData(EntranceName.AnywhereToJoinedPartyMembers, RegionName.PartyMembers),

    #Overworld
    EntranceName.Overworld_To_GondowanCliffs_EastSide: EntranceData(EntranceName.Overworld_To_GondowanCliffs_EastSide, RegionName.GondowanCliffs, '2:22', ERTestGroups.OW_WALK),

    EntranceName.Overworld_To_YampiDesertFront: EntranceData(EntranceName.Overworld_To_YampiDesertFront, RegionName.YampiDesertFront, '2:17', ERTestGroups.OW_WALK),
    EntranceName.Overworld_Garoh_To_YampiDesertBack: EntranceData(EntranceName.Overworld_Garoh_To_YampiDesertBack, RegionName.YampiDesertBack, '2:19', ERTestGroups.OW_WALK),
    EntranceName.Overworld_Alhafra_To_YampiDesertBack: EntranceData(EntranceName.Overworld_Alhafra_To_YampiDesertBack, RegionName.YampiDesertBack, '2:18', ERTestGroups.OW_WALK),
    EntranceName.Overworld_To_GondowanCliffs_WestSide: EntranceData(EntranceName.Overworld_To_GondowanCliffs_WestSide, RegionName.GondowanCliffs, '2:21', ERTestGroups.OW_WALK),
    EntranceName.Overworld_To_Naribwe_SouthSide: EntranceData(EntranceName.Overworld_To_Naribwe_SouthSide, RegionName.Naribwe, '2:23', ERTestGroups.OW_WALK),
    EntranceName.Overworld_To_Naribwe_NorthSide: EntranceData(EntranceName.Overworld_To_Naribwe_NorthSide, RegionName.Naribwe, '2:24', ERTestGroups.OW_WALK),
    EntranceName.Overworld_To_KibomboMountains_SouthSide: EntranceData(EntranceName.Overworld_To_KibomboMountains_SouthSide, RegionName.KibomboMountains, '2:25', ERTestGroups.OW_WALK),
    EntranceName.Overworld_To_KibomboMountains_NorthSide: EntranceData(EntranceName.Overworld_To_KibomboMountains_NorthSide, RegionName.KibomboMountains, '2:26', ERTestGroups.OW_WALK),
    EntranceName.Overworld_To_Kibombo: EntranceData(EntranceName.Overworld_To_Kibombo, RegionName.Kibombo, '2:27', ERTestGroups.OW_WALK),
    EntranceName.Overworld_WestIndraIslet_To_WestIndraIslet: EntranceData(EntranceName.Overworld_WestIndraIslet_To_WestIndraIslet, RegionName.WestIndraIslet, '2:28', ERTestGroups.OW_WALK),
    EntranceName.Overworld_EastTundariaIslet_To_EastTundariaIslet: EntranceData(EntranceName.Overworld_EastTundariaIslet_To_EastTundariaIslet, RegionName.EastTundariaIslet, '2:29', ERTestGroups.OW_WALK),
    EntranceName.Overworld_NorthOseniaIslet_To_NorthOseniaIslet: EntranceData(EntranceName.Overworld_NorthOseniaIslet_To_NorthOseniaIslet, RegionName.NorthOseniaIslet, '2:30', ERTestGroups.OW_WALK),
    EntranceName.Overworld_SouthEastAngaraIslet_To_SouthEastAngaraIslet: EntranceData(EntranceName.Overworld_SouthEastAngaraIslet_To_SouthEastAngaraIslet, RegionName.SouthEastAngaraIslet, '2:31', ERTestGroups.OW_WALK),
    EntranceName.Overworld_SeaOfTimeIslet_To_SeaOfTimeIslet: EntranceData(EntranceName.Overworld_SeaOfTimeIslet_To_SeaOfTimeIslet, RegionName.SeaOfTimeIslet, '2:32', ERTestGroups.OW_WALK),
    EntranceName.Overworld_ApojiiIslands_To_ApojiIslands: EntranceData(EntranceName.Overworld_ApojiiIslands_To_ApojiIslands, RegionName.ApojiiIslands, '2:36', ERTestGroups.OW_WALK),
    EntranceName.Overworld_AquaRock_To_AquaRock: EntranceData(EntranceName.Overworld_AquaRock_To_AquaRock, RegionName.AquaRock, '2:37', ERTestGroups.OW_WALK),
    EntranceName.Overworld_Izumo_To_Izumo: EntranceData(EntranceName.Overworld_Izumo_To_Izumo, RegionName.Izumo, '2:38', ERTestGroups.OW_WALK),
    EntranceName.Overworld_Izumo_To_GaiaRock: EntranceData(EntranceName.Overworld_Izumo_To_GaiaRock, RegionName.GaiaRock, '2:39', ERTestGroups.OW_WALK),
    EntranceName.Overworld_TreasureIsland_To_TreasureIsland: EntranceData(EntranceName.Overworld_TreasureIsland_To_TreasureIsland, RegionName.TreasureIsland, '2:87', ERTestGroups.OW_WALK),
    EntranceName.Overworld_Tundaria_To_TundariaTower: EntranceData(EntranceName.Overworld_Tundaria_To_TundariaTower, RegionName.TundariaTower, '2:46', ERTestGroups.OW_WALK),
    EntranceName.Overworld_SEAngara_To_AnkohlRuins: EntranceData(EntranceName.Overworld_SEAngara_To_AnkohlRuins, RegionName.AnkohlRuins, '2:41', ERTestGroups.OW_WALK),
    EntranceName.Overworld_SouthernAngara_To_Champa: EntranceData(EntranceName.Overworld_SouthernAngara_To_Champa, RegionName.Champa, '2:40', ERTestGroups.OW_WALK),
    EntranceName.Overworld_SouthEastOsenia_To_YallamSouth: EntranceData(EntranceName.Overworld_SouthEastOsenia_To_YallamSouth, RegionName.Yallam, '2:34', ERTestGroups.OW_WALK),
    EntranceName.Overworld_NorthEastOsenia_To_YallamNorth: EntranceData(EntranceName.Overworld_NorthEastOsenia_To_YallamNorth, RegionName.Yallam, '2:33', ERTestGroups.OW_WALK),
    EntranceName.Overworld_NorthEastOsenia_To_TaopoSwamp: EntranceData(EntranceName.Overworld_NorthEastOsenia_To_TaopoSwamp, RegionName.TaopoSwamp, '2:35', ERTestGroups.OW_WALK),
    EntranceName.Overworld_SouthWestAttekaIslet_To_SouthWestAttekaIslet: EntranceData(EntranceName.Overworld_SouthWestAttekaIslet_To_SouthWestAttekaIslet, RegionName.SouthWestAttekaIslet, '2:47', ERTestGroups.OW_WALK),
    EntranceName.Overworld_KaltIsland_To_KaltIsland: EntranceData(EntranceName.Overworld_KaltIsland_To_KaltIsland, RegionName.KaltIsland, '2:50', ERTestGroups.OW_WALK),
    EntranceName.Overworld_WestGondowan_To_GondowanSettlement: EntranceData(EntranceName.Overworld_WestGondowan_To_GondowanSettlement, RegionName.GondowanSettlement, '2:48', ERTestGroups.OW_WALK),
    EntranceName.Overworld_WestGondowan_To_MagmaRock: EntranceData(EntranceName.Overworld_WestGondowan_To_MagmaRock, RegionName.MagmaRock, '2:51', ERTestGroups.OW_WALK),
    EntranceName.Overworld_WestAngara_To_Loho: EntranceData(EntranceName.Overworld_WestAngara_To_Loho, RegionName.Loho, '2:59', ERTestGroups.OW_WALK),
    EntranceName.Overworld_WestAngara_To_AngaraCavern: EntranceData(EntranceName.Overworld_WestAngara_To_AngaraCavern, RegionName.AngaraCavern, '2:89', ERTestGroups.OW_WALK),
    EntranceName.Overworld_WeHesperia_HesperiaSettlement: EntranceData(EntranceName.Overworld_WeHesperia_HesperiaSettlement, RegionName.HesperiaSettlement, '2:49', ERTestGroups.OW_WALK),
    EntranceName.Overworld_CentralHesperia_To_ShamanVillageCave: EntranceData(EntranceName.Overworld_CentralHesperia_To_ShamanVillageCave, RegionName.ShamanVillageCave, '2:56', ERTestGroups.OW_WALK),
    EntranceName.Overworld_ShamanHesperia_To_ShamanVillageCave: EntranceData(EntranceName.Overworld_ShamanHesperia_To_ShamanVillageCave, RegionName.ShamanVillageCave, '2:57', ERTestGroups.OW_WALK),
    EntranceName.Overworld_ShamanHesperia_To_ShamanVillage: EntranceData(EntranceName.Overworld_ShamanHesperia_To_ShamanVillage, RegionName.ShamanVillage, '2:58', ERTestGroups.OW_WALK),
    EntranceName.Overworld_SouthernAtteka_To_AttekaCavern: EntranceData(EntranceName.Overworld_SouthernAtteka_To_AttekaCavern, RegionName.AttekaCavern, '2:88', ERTestGroups.OW_WALK),
    EntranceName.Overworld_CentralAtteka_To_AttekaInlet_Land: EntranceData(EntranceName.Overworld_CentralAtteka_To_AttekaInlet_Land, RegionName.AttekaInlet, '2:53', ERTestGroups.OW_WALK),
    EntranceName.Overworld_CentralAtteka_To_Contigo: EntranceData(EntranceName.Overworld_CentralAtteka_To_Contigo, RegionName.Contigo, '2:54', ERTestGroups.OW_WALK),
    EntranceName.Overworld_CentralAtteka_To_JupiterLighthouse: EntranceData(EntranceName.Overworld_CentralAtteka_To_JupiterLighthouse, RegionName.JupiterLighthouse, '2:55', ERTestGroups.OW_WALK),
    EntranceName.Overworld_LowNorthernReaches_To_Prox: EntranceData(EntranceName.Overworld_LowNorthernReaches_To_Prox, RegionName.Prox, '2:62', ERTestGroups.OW_WALK),
    EntranceName.Overworld_HighNorthenReaches_To_Prox: EntranceData(EntranceName.Overworld_HighNorthenReaches_To_Prox, RegionName.Prox, '2:63', ERTestGroups.OW_WALK),
    EntranceName.MarsLighthouse_To_Overworld: EntranceData(EntranceName.MarsLighthouse_To_Overworld, RegionName.MarsLighthouse, '2:84', ERTestGroups.OW_WALK),

    #Idejima
    EntranceName.Idejima_To_Overworld: EntranceData(EntranceName.Idejima_To_Overworld, RegionName.Indra_IdejimaArea, '9:4', ERTestGroups.WEST | ERTestGroups.SCREEN_EDGE_WALK, EntranceType.ONE_WAY),

    #Daila
    EntranceName.Overworld_To_Daila_NorthSide: EntranceData(EntranceName.Overworld_To_Daila_NorthSide, RegionName.Indra_Daila, '2:3', ERTestGroups.OW_WALK | ERTestGroups.SOUTH),
    EntranceName.Overworld_To_Daila_SouthSide: EntranceData(EntranceName.Overworld_To_Daila_SouthSide, RegionName.Indra_Daila, '2:2', ERTestGroups.OW_WALK | ERTestGroups.NORTH),
    EntranceName.Daila_North_To_Overworld: EntranceData(EntranceName.Daila_North_To_Overworld, RegionName.Indra_IdejimaArea, '13:9', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.Daila_South_To_Overworld: EntranceData(EntranceName.Daila_South_To_Overworld, RegionName.Indra_NorthernIndra, '13:8', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),

    #Kandorean Temple
    EntranceName.Overworld_To_KandoreanTemple: EntranceData(EntranceName.Overworld_To_KandoreanTemple, RegionName.KandoreanTemple_Outside_OuterEdge, '2:4', ERTestGroups.OW_WALK | ERTestGroups.NORTH),
    EntranceName.KandoreanTemple_To_Overworld: EntranceData(EntranceName.KandoreanTemple_To_Overworld, RegionName.Indra_NorthernIndra, '21:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KandoreanTemple_Outside_SideCave: EntranceData(EntranceName.KandoreanTemple_Outside_SideCave, RegionName.KandoreanTemple_WellPathway, '21:3',ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KandoreanTemple_Outside_Outer_Gates: EntranceData(EntranceName.KandoreanTemple_Outside_Outer_Gates, RegionName.KandoreanTemple_Outside_Templegrounds),
    EntranceName.KandoreanTemple_WellPath_To_CaveExit: EntranceData(EntranceName.KandoreanTemple_WellPath_To_CaveExit, RegionName.KandoreanTemple_Outside_OuterEdge, '18:1', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KandoreanTemple_WellPath_To_WellRope: EntranceData(EntranceName.KandoreanTemple_WellPath_To_WellRope, RegionName.KandoreanTemple_Outside_Templegrounds, '18:3', ERTestGroups.UP | ERTestGroups.LADDER),
    EntranceName.KandoreanTemple_TempleGrounds_WellRope: EntranceData(EntranceName.KandoreanTemple_TempleGrounds_WellRope, RegionName.KandoreanTemple_WellPathway, '21:4', ERTestGroups.DOWN | ERTestGroups.LADDER),
    EntranceName.KandoreanTemple_TempleGrounds_SouthGates: EntranceData(EntranceName.KandoreanTemple_TempleGrounds_SouthGates, RegionName.KandoreanTemple_Outside_OuterEdge),
    EntranceName.KandoreanTemple_TempleGrounds_NorthDoor: EntranceData(EntranceName.KandoreanTemple_TempleGrounds_NorthDoor, RegionName.KandoreanTemple_PreChallenge_Lobby, '21:2', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KandoreanTemple_Lobby_To_SouthDoor: EntranceData(EntranceName.KandoreanTemple_Lobby_To_SouthDoor, RegionName.KandoreanTemple_Outside_Templegrounds, '22:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KandoreanTemple_Lobby_LashRope: EntranceData(EntranceName.KandoreanTemple_Lobby_LashRope, RegionName.KandoreanTemple_PreChallenge_LashLedge),
    EntranceName.KandoreanTemple_Lobby_To_NorthDoor: EntranceData(EntranceName.KandoreanTemple_Lobby_To_NorthDoor, RegionName.KandoreanTemple_Challenge_Entry_Room, '22:9', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KandoreanTemple_DropDownLedge_Dropdown: EntranceData(EntranceName.KandoreanTemple_DropDownLedge_Dropdown, RegionName.KandoreanTemple_PreChallenge_Lobby),
    EntranceName.KandoreanTemple_DropDownLedge_Door: EntranceData(EntranceName.KandoreanTemple_DropDownLedge_Door, RegionName.KandoreanTemple_Challenge_MastersRoom, '22:2', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KandoreanTemple_LashLedge_Door: EntranceData(EntranceName.KandoreanTemple_LashLedge_Door, RegionName.KandoreanTemple_Challenge_MastersRoom, '22:3', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KandoreanTemple_EntryRoom_SouthDoor: EntranceData(EntranceName.KandoreanTemple_EntryRoom_SouthDoor, RegionName.KandoreanTemple_PreChallenge_Lobby, '15:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KandoreanTemple_EntryRoom_BackStaircase: EntranceData(EntranceName.KandoreanTemple_EntryRoom_BackStaircase, RegionName.KandoreanTemple_Challenge_ZigZagColumns_Room, '15:4', ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KandoreanTemple_JumpColumns_CentralStaircase: EntranceData(EntranceName.KandoreanTemple_JumpColumns_CentralStaircase, RegionName.KandoreanTemple_Challenge_Entry_Room, '20:2', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KandoreanTemple_JumpColumns_ZigZagsDoor: EntranceData(EntranceName.KandoreanTemple_JumpColumns_ZigZagsDoor, RegionName.KandoreanTemple_Challenge_CliffsEdge, '20:1', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KandoreanTemple_CliffsEdge_SouthDoor: EntranceData(EntranceName.KandoreanTemple_CliffsEdge_SouthDoor, RegionName.KandoreanTemple_Challenge_ZigZagColumns_Room, '14:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KandoreanTemple_CliffsEdge_Staircase: EntranceData(EntranceName.KandoreanTemple_CliffsEdge_Staircase, RegionName.KandoreanTemple_Challenge_WaterStream, '14:3', ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KandoreanTemple_WaterStream_WestsideStaircase: EntranceData(EntranceName.KandoreanTemple_WaterStream_WestsideStaircase, RegionName.KandoreanTemple_Challenge_CliffsEdge, '19:1', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KandoreanTemple_WaterStream_EastsideDoorway: EntranceData(EntranceName.KandoreanTemple_WaterStream_EastsideDoorway, RegionName.KandoreanTemple_Challenge_GeyserPuzzles, '19:2', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KandoreanTemple_GeyserPuzzles_SouthDoor: EntranceData(EntranceName.KandoreanTemple_GeyserPuzzles_SouthDoor, RegionName.KandoreanTemple_Challenge_WaterStream, '17:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KandoreanTemple_GeyserPuzzles_WestGeyser: EntranceData(EntranceName.KandoreanTemple_GeyserPuzzles_WestGeyser, RegionName.KandoreanTemple_Challenge_TightRopeArea, '17:3', ERTestGroups.UP | ERTestGroups.GEYSER),
    EntranceName.KandoreanTemple_GeyserPuzzles_EastGeyser: EntranceData(EntranceName.KandoreanTemple_GeyserPuzzles_EastGeyser, RegionName.KandoreanTemple_Challenge_TightRopeIsolated, '17:4', ERTestGroups.UP | ERTestGroups.GEYSER),
    EntranceName.KandoreanTemple_TightRopeArea_EastGeyserPlatform: EntranceData(EntranceName.KandoreanTemple_TightRopeArea_EastGeyserPlatform, RegionName.KandoreanTemple_Challenge_GeyserPuzzles, '14:6', ERTestGroups.DOWN | ERTestGroups.GEYSER),
    EntranceName.KandoreanTemple_TightRopeArea_WestGeyserPlatform: EntranceData(EntranceName.KandoreanTemple_TightRopeArea_WestGeyserPlatform, RegionName.KandoreanTemple_Challenge_GeyserPuzzles, '14:5', ERTestGroups.DOWN | ERTestGroups.GEYSER),
    EntranceName.KandoreanTemple_TightRopeArea_RopeGeyser: EntranceData(EntranceName.KandoreanTemple_TightRopeArea_RopeGeyser, RegionName.KandoreanTemple_Challenge_GeyserPuzzleLedgeArea, '14:10', ERTestGroups.DOWN | ERTestGroups.FALL, ERTestGroups.FALL | ERTestGroups.UP, 'Geyzer Puzzle Ledge - Drop Area', EntranceType.ONE_WAY),
    EntranceName.KandoreanTemple_TightRopeArea_StairsNearRopes: EntranceData(EntranceName.KandoreanTemple_TightRopeArea_StairsNearRopes, RegionName.KandoreanTemple_Challenge_GeyserPuzzleLedgeArea, '14:4', ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KandoreanTemple_TightRopeArea_SouthEastDoor: EntranceData(EntranceName.KandoreanTemple_TightRopeArea_SouthEastDoor, RegionName.KandoreanTemple_Challenge_DjinnRoom, '14:2', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KandoreanTemple_GeyzerPuzzleLedge_Staircase: EntranceData(EntranceName.KandoreanTemple_GeyzerPuzzleLedge_Staircase, RegionName.KandoreanTemple_Challenge_TightRopeArea, '17:2', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KandoreanTemple_DjinnRoom_DoorNearLashRope: EntranceData(EntranceName.KandoreanTemple_DjinnRoom_DoorNearLashRope, RegionName.KandoreanTemple_Challenge_TightRopeArea, '20:3', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KandoreanTemple_DjinnRoom_SouthStairs: EntranceData(EntranceName.KandoreanTemple_DjinnRoom_SouthStairs, RegionName.KandoreanTemple_Challenge_StairWell, '20:4', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KandoreanTemple_StairWell_WestStairs: EntranceData(EntranceName.KandoreanTemple_StairWell_WestStairs, RegionName.KandoreanTemple_Challenge_DjinnRoom, '15:2', ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KandoreanTemple_StairWell_EastStairs: EntranceData(EntranceName.KandoreanTemple_StairWell_EastStairs, RegionName.KandoreanTemple_Challenge_BurningPotRoom, '15:3', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KandoreanTemple_PotRoom_SouthStairs: EntranceData(EntranceName.KandoreanTemple_PotRoom_SouthStairs, RegionName.KandoreanTemple_Challenge_StairWell, '16:1', ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KandoreanTemple_PotRoom_NorthLadder: EntranceData(EntranceName.KandoreanTemple_PotRoom_NorthLadder, RegionName.KandoreanTemple_Challenge_PurpleHallway, '16:2', ERTestGroups.UP | ERTestGroups.LADDER),
    EntranceName.KandoreanTemple_PurpleHallway_NorthLadder: EntranceData(EntranceName.KandoreanTemple_PurpleHallway_NorthLadder, RegionName.KandoreanTemple_Challenge_BurningPotRoom, '22:8', ERTestGroups.DOWN | ERTestGroups.LADDER),
    EntranceName.KandoreanTemple_PurpleHallway_SouthDoor: EntranceData(EntranceName.KandoreanTemple_PurpleHallway_SouthDoor, RegionName.KandoreanTemple_Challenge_MastersRoom, '22:7', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KandoreanTemple_MastersRoom_NorthWestDoor: EntranceData(EntranceName.KandoreanTemple_MastersRoom_NorthWestDoor, RegionName.KandoreanTemple_Challenge_PurpleHallway, '22:6', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KandoreanTemple_MastersRoom_SouthWestDoor: EntranceData(EntranceName.KandoreanTemple_MastersRoom_SouthWestDoor, RegionName.KandoreanTemple_PreChallenge_DropDownLedge, '22:4', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KandoreanTemple_MastersRoom_SouthEastDoor: EntranceData(EntranceName.KandoreanTemple_MastersRoom_SouthEastDoor, RegionName.KandoreanTemple_PreChallenge_LashLedge, '22:5', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),


    #Shrine of the Sea God
    EntranceName.Overworld_To_ShrineOfTheSeaGod: EntranceData(EntranceName.Overworld_To_ShrineOfTheSeaGod, RegionName.ShrineOfTheSeaGod_EntryRoom_LowerHalf, '2:5', ERTestGroups.OW_WALK | ERTestGroups.NORTH),
    EntranceName.ShrineOfTheSeaGod_To_Overworld: EntranceData(EntranceName.ShrineOfTheSeaGod_To_Overworld, RegionName.Indra_NorthernIndra, '23:3', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.ShrineOfTheSeaGod_EntryLow_EastDoor: EntranceData(EntranceName.ShrineOfTheSeaGod_EntryLow_EastDoor, RegionName.ShrineOfTheSeaGod_Torched_DeadEnd, '23:2', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.ShrineOfTheSeaGod_TorchedDeadEnd_WestDoor: EntranceData(EntranceName.ShrineOfTheSeaGod_TorchedDeadEnd_WestDoor, RegionName.ShrineOfTheSeaGod_EntryRoom_LowerHalf, '24:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.ShrineOfTheSeaGod_EntryLow_LashRope: EntranceData(EntranceName.ShrineOfTheSeaGod_EntryLow_LashRope, RegionName.ShrineOfTheSeaGod_EntryRoom_UpperHalf),
    EntranceName.ShrineOfTheSeaGod_EntryHigh_DropDown: EntranceData(EntranceName.ShrineOfTheSeaGod_EntryHigh_DropDown, RegionName.ShrineOfTheSeaGod_EntryRoom_LowerHalf),
    EntranceName.ShrineOfTheSeaGod_EntryHigh_WestDoor: EntranceData(EntranceName.ShrineOfTheSeaGod_EntryHigh_WestDoor, RegionName.ShrineOfTheSeaGod_Quad_Bridge_Upper_Ridges, '23:1', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.ShrineOfTheSeaGod_QuadBridgesUpper_EasternDoor: EntranceData(EntranceName.ShrineOfTheSeaGod_QuadBridgesUpper_EasternDoor, RegionName.ShrineOfTheSeaGod_EntryRoom_UpperHalf, '25:5', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.ShrineOfTheSeaGod_QuadBridgesUpper_Stairs: EntranceData(EntranceName.ShrineOfTheSeaGod_QuadBridgesUpper_Stairs, RegionName.ShrineOfTheSeaGod_SkippingStones_DeadEnd, '25:3', ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.ShrineOfTheSeaGod_SkippingStonesDeadEnd_Staircase: EntranceData(EntranceName.ShrineOfTheSeaGod_SkippingStonesDeadEnd_Staircase, RegionName.ShrineOfTheSeaGod_Quad_Bridge_Upper_Ridges, '30:2', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.ShrineOfTheSeaGod_QuadBridgesUpper_BridgeDropDown: EntranceData(EntranceName.ShrineOfTheSeaGod_QuadBridgesUpper_BridgeDropDown, RegionName.ShrineOfTheSeaGod_Quad_Bridge_Dropped_Area),
    EntranceName.ShrineOfTheSeaGod_QuadBridgesDroppedArea_DropDown: EntranceData(EntranceName.ShrineOfTheSeaGod_QuadBridgesDroppedArea_DropDown, RegionName.ShrineOfTheSeaGod_Quad_Bridge_Upper_Ridges),
    EntranceName.ShrineOfTheSeaGod_QuadBridgesDroppedArea_SouthStairs: EntranceData(EntranceName.ShrineOfTheSeaGod_QuadBridgesDroppedArea_SouthStairs, RegionName.ShrineOfTheSeaGod_Djinn_Footsteps_Area, '25:4', ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.ShrineOfTheSeaGod_DjinnFootstepsArea_NorthernStairs: EntranceData(EntranceName.ShrineOfTheSeaGod_DjinnFootstepsArea_NorthernStairs, RegionName.ShrineOfTheSeaGod_Quad_Bridge_Dropped_Area, '26:1', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.ShrineOfTheSeaGod_DjinnFootstepsArea_WesternStairs: EntranceData(EntranceName.ShrineOfTheSeaGod_DjinnFootstepsArea_WesternStairs, RegionName.ShrineOfTheSeaGod_Djinn_Fleeing_Bridge, '26:2', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.ShrineOfTheSeaGod_DjinnFootstepsArea_EasternStairs: EntranceData(EntranceName.ShrineOfTheSeaGod_DjinnFootstepsArea_EasternStairs, RegionName.ShrineOfTheSeaGod_Djinn_Fleeing_Bridge, '26:4', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.ShrineOfTheSeaGod_DjinnFootstepsArea_SouthernStairs: EntranceData(EntranceName.ShrineOfTheSeaGod_DjinnFootstepsArea_SouthernStairs, RegionName.ShrineOfTheSeaGod_Djinn_Torch_Corner, '26:3', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.ShrineOfTheSeaGod_DjinnFleeingBridge_WesternStairs: EntranceData(EntranceName.ShrineOfTheSeaGod_DjinnFleeingBridge_WesternStairs, RegionName.ShrineOfTheSeaGod_Djinn_Footsteps_Area, '27:3', ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.ShrineOfTheSeaGod_DjinnFleeingBridge_EasternStairs: EntranceData(EntranceName.ShrineOfTheSeaGod_DjinnFleeingBridge_EasternStairs, RegionName.ShrineOfTheSeaGod_Djinn_Footsteps_Area, '27:2', ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.ShrineOfTheSeaGod_DjinnTorchCorner_SouthernStairs: EntranceData(EntranceName.ShrineOfTheSeaGod_DjinnTorchCorner_SouthernStairs, RegionName.ShrineOfTheSeaGod_Djinn_Footsteps_Area, '27:4', ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.ShrineOfTheSeaGod_DjinnTorchCorner_FrostJumps: EntranceData(EntranceName.ShrineOfTheSeaGod_DjinnTorchCorner_FrostJumps, RegionName.ShrineOfTheSeaGod_NearDjinn_Frost_Ledge),
    EntranceName.ShrineOfTheSeaGod_FrostLedge_NorthernDoor: EntranceData(EntranceName.ShrineOfTheSeaGod_FrostLedge_NorthernDoor, RegionName.ShrineOfTheSeaGod_OceansView, '27:1', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.ShrineOfTheSeaGod_OceansView_SouthernDoor: EntranceData(EntranceName.ShrineOfTheSeaGod_OceansView_SouthernDoor, RegionName.ShrineOfTheSeaGod_NearDjinn_Frost_Ledge, '28:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.ShrineOfTheSeaGod_OceansView_NorthEasternStairs: EntranceData(EntranceName.ShrineOfTheSeaGod_OceansView_NorthEasternStairs, RegionName.ShrineOfTheSeaGod_RushingWaterBridges, '28:2', ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.ShrineOfTheSeaGod_RushingWaterBridges_WesternStairs: EntranceData(EntranceName.ShrineOfTheSeaGod_RushingWaterBridges_WesternStairs, RegionName.ShrineOfTheSeaGod_OceansView, '29:1', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.ShrineOfTheSeaGod_RushingWaterBridges_BridgeDropDown: EntranceData(EntranceName.ShrineOfTheSeaGod_RushingWaterBridges_BridgeDropDown, RegionName.ShrineOfTheSeaGod_RushingWaterLash),
    EntranceName.ShrineOfTheSeaGod_RushingWaterBridgesLash_LashRope: EntranceData(EntranceName.ShrineOfTheSeaGod_RushingWaterBridgesLash_LashRope, RegionName.ShrineOfTheSeaGod_RushingWaterBridges),
    EntranceName.ShrineOfTheSeaGod_RushingWaterBridgesLash_EasternStairs: EntranceData(EntranceName.ShrineOfTheSeaGod_RushingWaterBridgesLash_EasternStairs, RegionName.ShrineOfTheSeaGod_QuadBridgeWestLedge, '29:2', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.ShrineOfTheSeaGod_QuadBridgesWest_WesternStairs: EntranceData(EntranceName.ShrineOfTheSeaGod_QuadBridgesWest_WesternStairs, RegionName.ShrineOfTheSeaGod_RushingWaterLash, '25:1', ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.ShrineOfTheSeaGod_QuadBridgesWest_LogJump: EntranceData(EntranceName.ShrineOfTheSeaGod_QuadBridgesWest_LogJump, RegionName.ShrineOfTheSeaGod_Quad_Bridge_Upper_Ridges),
    EntranceName.ShrineOfTheSeaGod_QuadBridgesWest_EasternStairs: EntranceData(EntranceName.ShrineOfTheSeaGod_QuadBridgesWest_EasternStairs, RegionName.ShrineOfTheSeaGod_WateryShrineInWater, '25:2', ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.ShrineOfTheSeaGod_WateryShrineInWater_SouthWestStairs: EntranceData(EntranceName.ShrineOfTheSeaGod_WateryShrineInWater_SouthWestStairs, RegionName.ShrineOfTheSeaGod_QuadBridgeWestLedge, '30:1', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.ShrineOfTheSeaGod_WateryShrineInWater_ElevateShrine: EntranceData(EntranceName.ShrineOfTheSeaGod_WateryShrineInWater_ElevateShrine, RegionName.ShrineOfTheSeaGod_ElevatedShrine, '30:3', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.ShrineOfTheSeaGod_ElevatedShrine_LoweringShrine: EntranceData(EntranceName.ShrineOfTheSeaGod_ElevatedShrine_LoweringShrine, RegionName.ShrineOfTheSeaGod_WateryShrineInWater, '31:1', ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.ShrineOfTheSeaGod_ElevatedShrine_NorthWestLadder: EntranceData(EntranceName.ShrineOfTheSeaGod_ElevatedShrine_NorthWestLadder, RegionName.ShrineOfTheSeaGod_UpperTowerArea, '31:2', ERTestGroups.UP | ERTestGroups.LADDER),
    EntranceName.ShrineOfTheSeaGod_UpperTowerArea_WestLadder: EntranceData(EntranceName.ShrineOfTheSeaGod_UpperTowerArea_WestLadder, RegionName.ShrineOfTheSeaGod_ElevatedShrine, '32:40', ERTestGroups.DOWN | ERTestGroups.LADDER),
    EntranceName.ShrineOfTheSeaGod_UpperTowerArea_EastLadder: EntranceData(EntranceName.ShrineOfTheSeaGod_UpperTowerArea_EastLadder, RegionName.ShrineOfTheSeaGod_TopOfTheShrine, '32:41', ERTestGroups.UP | ERTestGroups.LADDER),
    EntranceName.ShrineOfTheSeaGod_TopOfTheShrine_EastLadder: EntranceData(EntranceName.ShrineOfTheSeaGod_TopOfTheShrine_EastLadder, RegionName.ShrineOfTheSeaGod_UpperTowerArea, '33:40', ERTestGroups.DOWN | ERTestGroups.LADDER),

    #Dehkan Plateau
    EntranceName.Overworld_To_DehkanPlateau_NorthWestSide: EntranceData(EntranceName.Overworld_To_DehkanPlateau_NorthWestSide, RegionName.DehkanPlateau_TripleStairs, '2:6',  ERTestGroups.OW_WALK | ERTestGroups.EAST),
    EntranceName.Overworld_To_DehkanPlateau_SouthEastSide: EntranceData(EntranceName.Overworld_To_DehkanPlateau_SouthEastSide, RegionName.DehkanPlateau_QuadStairs, '2:7',  ERTestGroups.OW_WALK | ERTestGroups.NORTH),
    EntranceName.DehkanPlateau_West_To_Overworld: EntranceData(EntranceName.DehkanPlateau_West_To_Overworld, RegionName.Indra_NorthernIndra, '34:1', ERTestGroups.WEST | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_East_To_Overworld: EntranceData(EntranceName.DehkanPlateau_East_To_Overworld, RegionName.Indra_SouthernIndra, '36:6', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),

    EntranceName.DehkanPlateau_TripleStairsCrackedFloor: EntranceData(EntranceName.DehkanPlateau_TripleStairsCrackedFloor, RegionName.DehkanPlateau_HorizontalOvalShapedCavern, '34:13', ERTestGroups.DOWN | ERTestGroups.FALL, ERTestGroups.FALL | ERTestGroups.UP, 'Dekhan Platea - Horizontal Overal Shaped Cavern Drop Down', EntranceType.ONE_WAY),
    EntranceName.DehkanPlateau_HorizontalOvalShapedCave_SouthDoorway: EntranceData(EntranceName.DehkanPlateau_HorizontalOvalShapedCave_SouthDoorway, RegionName.DehkanPlateau_IsolatedNearTripleStairs, '37:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_IsolatedNearTripleStairs_Doorway: EntranceData(EntranceName.DehkanPlateau_IsolatedNearTripleStairs_Doorway, RegionName.DehkanPlateau_HorizontalOvalShapedCavern, '34:2', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_HorizontalOvalShapedCave_NorthDoorway: EntranceData(EntranceName.DehkanPlateau_HorizontalOvalShapedCave_NorthDoorway, RegionName.DehkanPlateau_AboveTripleStairs, '37:2', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_TripleStairsUpperLedgeDoorway: EntranceData(EntranceName.DehkanPlateau_TripleStairsUpperLedgeDoorway, RegionName.DehkanPlateau_HorizontalOvalShapedCavern, '34:3', ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_TripleStairsUpperLedgeDropDown: EntranceData(EntranceName.DehkanPlateau_TripleStairsUpperLedgeDropDown, RegionName.DehkanPlateau_TripleStairs),
    EntranceName.DehkanPlateau_TripleStairsUpperLedgeEasternExit: EntranceData(EntranceName.DehkanPlateau_TripleStairsUpperLedgeEasternExit, RegionName.DehkanPlateau_TripleStonePillars, '34:6', ERTestGroups.EAST | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_TripleStonePillars_WesternExit: EntranceData(EntranceName.DehkanPlateau_TripleStonePillars_WesternExit, RegionName.DehkanPlateau_AboveTripleStairs, '34:7', ERTestGroups.WEST | ERTestGroups.SCREEN_EDGE_WALK),

    EntranceName.DehkanPlateau_TripleStonePillars_CrackedFloor: EntranceData(EntranceName.DehkanPlateau_TripleStonePillars_CrackedFloor, RegionName.DehkanPlateau_TeasingCavernUpperSide, '34:19', ERTestGroups.DOWN | ERTestGroups.FALL, ERTestGroups.FALL | ERTestGroups.UP, 'Dekhan Plateau - Teasing Cavern Upper Ledge Drop Down', EntranceType.ONE_WAY),
    EntranceName.DehkanPlateau_TeasingCavernDropDown: EntranceData(EntranceName.DehkanPlateau_TeasingCavernDropDown, RegionName.DehkanPlateau_TeasingCavernLowerSide),
    EntranceName.DehkanPlateau_TeasingCavernSouthernExit: EntranceData(EntranceName.DehkanPlateau_TeasingCavernSouthernExit, RegionName.DehkanPlateau_UShapedCavern, '37:41', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_UShapedCavern_EastDoorway: EntranceData(EntranceName.DehkanPlateau_UShapedCavern_EastDoorway, RegionName.DehkanPlateau_TeasingCavernLowerSide, '37:43', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),

    EntranceName.DehkanPlateau_UShapedCavern_WestDoorway: EntranceData(EntranceName.DehkanPlateau_UShapedCavern_WestDoorway, RegionName.DehkanPlateau_StonePillarsLogLedge, '37:4', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_StonePillarsLogLedge_Doorway: EntranceData(EntranceName.DehkanPlateau_StonePillarsLogLedge_Doorway, RegionName.DehkanPlateau_UShapedCavern, '34:4', ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_StonePillarsLogLedge_LogJump: EntranceData(EntranceName.DehkanPlateau_StonePillarsLogLedge_LogJump, RegionName.DehkanPlateau_TripleStonePillars),

    EntranceName.DehkanPlateau_TripleStonePillars_NorthernExit: EntranceData(EntranceName.DehkanPlateau_TripleStonePillars_NorthernExit, RegionName.DehkanPlateau_StonePillarMaze, '34:5', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_StonePillarMaze_SouthernExit: EntranceData(EntranceName.DehkanPlateau_StonePillarMaze_SouthernExit, RegionName.DehkanPlateau_TripleStonePillars, '35:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_StonePillarMaze_EasternExit: EntranceData(EntranceName.DehkanPlateau_StonePillarMaze_EasternExit, RegionName.DehkanPlateau_CrackedFloorsRockSlide, '35:5', ERTestGroups.EAST | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_CrackedFloorsRockSlide_WesternExit: EntranceData(EntranceName.DehkanPlateau_CrackedFloorsRockSlide_WesternExit, RegionName.DehkanPlateau_StonePillarMaze, '35:6', ERTestGroups.WEST | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_CrackedFloorsRockSlide_CrackedFloor: EntranceData(EntranceName.DehkanPlateau_CrackedFloorsRockSlide_CrackedFloor, RegionName.DehkanPlateau_BalloonCavern, '37:27', ERTestGroups.DOWN | ERTestGroups.FALL, ERTestGroups.FALL | ERTestGroups.UP, 'Dekhan Plateau - Balloon Cavern Drop Down', EntranceType.ONE_WAY),

    EntranceName.DehkanPlateau_BalloonCavern_SouthernExit: EntranceData(EntranceName.DehkanPlateau_BalloonCavern_SouthernExit, RegionName.DehkanPlateau_MirrorJCavern, '37:40', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_MirrorJCavern_EasternExit: EntranceData(EntranceName.DehkanPlateau_MirrorJCavern_EasternExit, RegionName.DehkanPlateau_BalloonCavern, '37:42', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_MirrorJCavern_WesternExit: EntranceData(EntranceName.DehkanPlateau_MirrorJCavern_WesternExit, RegionName.DehkanPlateau_IsolatedCrackedFloors, '37:6', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_IsolatedCrakcedFloorsArea_Doorway: EntranceData(EntranceName.DehkanPlateau_IsolatedCrakcedFloorsArea_Doorway, RegionName.DehkanPlateau_MirrorJCavern, '35:2', ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_IsolatedCrakcedFloorsArea_CrackedFloor: EntranceData(EntranceName.DehkanPlateau_IsolatedCrakcedFloorsArea_CrackedFloor, RegionName.DehkanPlateau_SideEyeCavern, '35:21', ERTestGroups.DOWN | ERTestGroups.FALL, ERTestGroups.FALL | ERTestGroups.UP, 'Dekhan Plateau - Side Eye Cavern Drop Down', EntranceType.ONE_WAY),

    EntranceName.DehkanPlateau_SideEyeCavern_Doorway: EntranceData(EntranceName.DehkanPlateau_SideEyeCavern_Doorway, RegionName.DehkanPlateau_RockslideArea, '37:5', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_RockSlideArea_Doorway: EntranceData(EntranceName.DehkanPlateau_RockSlideArea_Doorway, RegionName.DehkanPlateau_SideEyeCavern, '35:3', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_RockSlideArea_LogJump: EntranceData(EntranceName.DehkanPlateau_RockSlideArea_LogJump, RegionName.DehkanPlateau_CrackedFloorsRockSlide),
    EntranceName.DehkanPlateau_RockSlideArea_EasternExit: EntranceData(EntranceName.DehkanPlateau_RockSlideArea_EasternExit, RegionName.DehkanPlateau_RopeBridgeArea, '35:4', ERTestGroups.EAST | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_RopeBridge_WesternExit: EntranceData(EntranceName.DehkanPlateau_RopeBridge_WesternExit, RegionName.DehkanPlateau_RockslideArea, '36:1', ERTestGroups.WEST | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_RopeBridge_ToCrackedFloorArea: EntranceData(EntranceName.DehkanPlateau_RopeBridge_ToCrackedFloorArea, RegionName.DehkanPlateau_RopeBridgeCrackedFloorArea),
    EntranceName.DehkanPlateau_RopeBridge_CrackedFloor: EntranceData(EntranceName.DehkanPlateau_RopeBridge_CrackedFloor, RegionName.DehkanPlateau_BottleCavern, '36:17', ERTestGroups.DOWN | ERTestGroups.FALL, ERTestGroups.FALL | ERTestGroups.UP, 'Dekhan Plateau - Bottle Cavern Drop Down', EntranceType.ONE_WAY),
    EntranceName.DehkanPlateau_BottleCavern_Doorway: EntranceData(EntranceName.DehkanPlateau_BottleCavern_Doorway, RegionName.DehkanPlateau_RopeBridgeArea, '37:3', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_RopeBridge_Doorway: EntranceData(EntranceName.DehkanPlateau_RopeBridge_Doorway, RegionName.DehkanPlateau_BottleCavern, '36:2', ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_RopeBridge_VineLogClimb: EntranceData(EntranceName.DehkanPlateau_RopeBridge_VineLogClimb, RegionName.DehkanPlateau_BelowRopeBridgeArea),
    EntranceName.DehkanPlateau_BelowRopeBridge_ToCrackedFloorArea: EntranceData(EntranceName.DehkanPlateau_BelowRopeBridge_ToCrackedFloorArea, RegionName.DehkanPlateau_RopeBridgeCrackedFloorArea),
    EntranceName.DehkanPlateau_BelowRopeBridge_EasternExit: EntranceData(EntranceName.DehkanPlateau_BelowRopeBridge_EasternExit, RegionName.DehkanPlateau_CrampedWesternLedge, '36:7', ERTestGroups.EAST | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_CrampedWesternLedge_WesternExit: EntranceData(EntranceName.DehkanPlateau_CrampedWesternLedge_WesternExit, RegionName.DehkanPlateau_BelowRopeBridgeArea, '36:8', ERTestGroups.WEST | ERTestGroups.SCREEN_EDGE_WALK),

    EntranceName.DehkanPlateau_CrampedWesternLedge_LogJumpToMCentralLedge: EntranceData(EntranceName.DehkanPlateau_CrampedWesternLedge_LogJumpToMCentralLedge, RegionName.DehkanPlateau_MiddleLedgeBetweenStonePillars),
    EntranceName.DehkanPlateau_MiddleLedgeBetweenPillars_Dropdown: EntranceData(EntranceName.DehkanPlateau_MiddleLedgeBetweenPillars_Dropdown, RegionName.DehkanPlateau_BelowRopeBridgeArea),
    EntranceName.DehkanPlateau_MiddleLedgeBetweenPillars_Doorway: EntranceData(EntranceName.DehkanPlateau_MiddleLedgeBetweenPillars_Doorway, RegionName.DehkanPlateau_ThreeAngledCavern, '36:3', ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_ThreeAngledCavern_NorthernDoorway: EntranceData(EntranceName.DehkanPlateau_ThreeAngledCavern_NorthernDoorway, RegionName.DehkanPlateau_MiddleLedgeBetweenStonePillars, '38:1', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_ThreeAngledCavern_EasternDoorway: EntranceData(EntranceName.DehkanPlateau_ThreeAngledCavern_EasternDoorway, RegionName.DehkanPlateau_CrackedFloorCavernLowerHalf, '38:10', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_CrackedFloorCaveLowerHalf_SouthernDoorway: EntranceData(EntranceName.DehkanPlateau_CrackedFloorCaveLowerHalf_SouthernDoorway, RegionName.DehkanPlateau_ThreeAngledCavern, '38:7', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),

    EntranceName.DehkanPlateau_CrackedFloorCaveLowerHalf_ToCrackedFloorArea: EntranceData(EntranceName.DehkanPlateau_CrackedFloorCaveLowerHalf_ToCrackedFloorArea, RegionName.DehkanPlateau_CrackedFloorCavernCrackedFloor),
    EntranceName.DehkanPlateau_CrackedFloorCave_CrackedFloor: EntranceData(EntranceName.DehkanPlateau_CrackedFloorCave_CrackedFloor, RegionName.DehkanPlateau_DeepCavernDropDownArea, '38:28', ERTestGroups.DOWN | ERTestGroups.FALL, ERTestGroups.FALL | ERTestGroups.UP, 'Dekhan Plateau - Deep Cavern Drop Down', EntranceType.ONE_WAY),
    EntranceName.DehkanPlateau_DeepCavenDropDownArea_Doorway: EntranceData(EntranceName.DehkanPlateau_DeepCavenDropDownArea_Doorway, RegionName.DehkanPlateau_CrackedFloorCavernLowerHalf, '39:1', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_CrackedFloorCaveLowerHalf_WesternDoorway: EntranceData(EntranceName.DehkanPlateau_CrackedFloorCaveLowerHalf_WesternDoorway, RegionName.DehkanPlateau_DeepCavernDropDownArea, '38:2', ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_CrackedFloorCaveLowerHalf_EasternDoorway: EntranceData(EntranceName.DehkanPlateau_CrackedFloorCaveLowerHalf_EasternDoorway, RegionName.DehkanPlateau_PoundPillarCavernUpperHalf, '38:8', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_PoundPillarCavernUpperHalf_WesternDoorway: EntranceData(EntranceName.DehkanPlateau_PoundPillarCavernUpperHalf_WesternDoorway, RegionName.DehkanPlateau_CrackedFloorCavernLowerHalf, '38:9', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_PoundPillarCavernUpperHalf_EasternDoorway: EntranceData(EntranceName.DehkanPlateau_PoundPillarCavernUpperHalf_EasternDoorway, RegionName.DehkanPlateau_CrackedFloorsNorthOfCrackedPillar, '38:4', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_CrackedFloorsNorthOfPillar_Doorway: EntranceData(EntranceName.DehkanPlateau_CrackedFloorsNorthOfPillar_Doorway, RegionName.DehkanPlateau_PoundPillarCavernUpperHalf, '36:4', ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_CrackedFloorsNorthOfPillar_CrackedFloor: EntranceData(EntranceName.DehkanPlateau_CrackedFloorsNorthOfPillar_CrackedFloor, RegionName.DehkanPlateau_CrackedFloorCavernDjinnDropDown, '36:17', ERTestGroups.DOWN | ERTestGroups.FALL, ERTestGroups.FALL | ERTestGroups.UP, 'Dekhan Plateau - Cracked Floor Cavern Drop Down', EntranceType.ONE_WAY),

    EntranceName.DehkanPlateau_CrackedFloorCaveDjinnDrop_ToLowerHalf: EntranceData(EntranceName.DehkanPlateau_CrackedFloorCaveDjinnDrop_ToLowerHalf, RegionName.DehkanPlateau_CrackedFloorCavernLowerHalf),
    EntranceName.DehkanPlateau_CrackedFloorCaveDjinnDrop_ToUpperHalf: EntranceData(EntranceName.DehkanPlateau_CrackedFloorCaveDjinnDrop_ToUpperHalf, RegionName.DehkanPlateau_CrackedFloorCavernUpperHalf),
    EntranceName.DehkanPlateau_CrackedFloorCaveUpperHalf_ToCrackedFloorArea: EntranceData(EntranceName.DehkanPlateau_CrackedFloorCaveUpperHalf_ToCrackedFloorArea, RegionName.DehkanPlateau_CrackedFloorCavernCrackedFloor),
    EntranceName.DehkanPlateau_CrackedFloorCaveUpperHalf_NorthenDoorway: EntranceData(EntranceName.DehkanPlateau_CrackedFloorCaveUpperHalf_NorthenDoorway, RegionName.DehkanPlateau_DeepCavernUpperLedge, '38:3', ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_DeepCavernUpperLedge_NorthernDoorway: EntranceData(EntranceName.DehkanPlateau_DeepCavernUpperLedge_NorthernDoorway, RegionName.DehkanPlateau_CrackedFloorCavernUpperHalf, '39:2', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_DeepCavernUpperLedge_SouthernDoorway: EntranceData(EntranceName.DehkanPlateau_DeepCavernUpperLedge_SouthernDoorway, RegionName.DehkanPlateau_DjinnCombatCavern, '39:40', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_DjinnCombatCavernRoom_NorthernDoorway: EntranceData(EntranceName.DehkanPlateau_DjinnCombatCavernRoom_NorthernDoorway, RegionName.DehkanPlateau_DeepCavernUpperLedge, '39:41', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_DjinnCombatCavernRoom_SouthernDoorway: EntranceData(EntranceName.DehkanPlateau_DjinnCombatCavernRoom_SouthernDoorway, RegionName.DehkanPlateau_FlatHallwayCavern, '39:42', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_FlatHallwayDeepCavern_EasternDoorway: EntranceData(EntranceName.DehkanPlateau_FlatHallwayDeepCavern_EasternDoorway, RegionName.DehkanPlateau_DjinnCombatCavern, '39:43', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_FlatHallwayDeepCavern_WesternDoorway: EntranceData(EntranceName.DehkanPlateau_FlatHallwayDeepCavern_WesternDoorway, RegionName.DehkanPlateau_PoundPillarCavernLowerHalf, '39:3', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_PoundPillarCavernLowerHalf_EasternDoorway: EntranceData(EntranceName.DehkanPlateau_PoundPillarCavernLowerHalf_EasternDoorway, RegionName.DehkanPlateau_FlatHallwayCavern, '38:6', ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_PoundPillarCavernLowerHalf_ToUpperHalf: EntranceData(EntranceName.DehkanPlateau_PoundPillarCavernLowerHalf_ToUpperHalf, RegionName.DehkanPlateau_PoundPillarCavernUpperHalf),
    EntranceName.DehkanPlateau_PoundPillarCavernUpperHalf_ToLowerHalf: EntranceData(EntranceName.DehkanPlateau_PoundPillarCavernUpperHalf_ToLowerHalf, RegionName.DehkanPlateau_PoundPillarCavernLowerHalf),
    EntranceName.DehkanPlateau_PoundPillarCavernLowerHalf_WesternDoorway: EntranceData(EntranceName.DehkanPlateau_PoundPillarCavernLowerHalf_WesternDoorway, RegionName.DehkanPlateau_QuadStairs, '38:5', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_QuadStairs_EasternDoorway: EntranceData(EntranceName.DehkanPlateau_QuadStairs_EasternDoorway, RegionName.DehkanPlateau_PoundPillarCavernLowerHalf, '36:5', ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.DehkanPlateau_QuadStairs_LogVines: EntranceData(EntranceName.DehkanPlateau_QuadStairs_LogVines, RegionName.DehkanPlateau_CrampedWesternLedge),

    #Indra Cavern
    EntranceName.Overworld_To_IndraCavern: EntranceData(EntranceName.Overworld_To_IndraCavern, RegionName.IndraCavern, '2:83', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceName.IndraCavern_To_Overworld: EntranceData(EntranceName.IndraCavern_To_Overworld, RegionName.Indra_SouthernIndra, '275:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),

    #Madra
    EntranceName.Overworld_To_Madra: EntranceData(EntranceName.Overworld_To_Madra, RegionName.Madra, '2:9', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceName.Madra_To_Overworld: EntranceData(EntranceName.Madra_To_Overworld, RegionName.Indra_SouthernIndra, '44:11', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),

    #Madra Catacombs
    EntranceName.MadraToMadraCatacombsEast: EntranceData(EntranceName.MadraToMadraCatacombsEast, RegionName.MadraCatacombsLadderRoomEast, '44:16', ERTestGroups.DOWN | ERTestGroups.LADDER),
    EntranceName.MadraCatacombsEastToMadra: EntranceData(EntranceName.MadraCatacombsEastToMadra, RegionName.Madra, '48:3', ERTestGroups.UP | ERTestGroups.LADDER),
    EntranceName.MadraToMadraCatacombsWest: EntranceData(EntranceName.MadraToMadraCatacombsWest, RegionName.MadraCatacombsLadderRoomWest, '44:15', ERTestGroups.DOWN | ERTestGroups.LADDER),
    EntranceName.MadraCatacombsWestToMadra: EntranceData(EntranceName.MadraCatacombsWestToMadra, RegionName.Madra, '48:1', ERTestGroups.UP | ERTestGroups.LADDER),
    EntranceName.MadraCatacombsLadderRoomEast_SouthernDoorway: EntranceData(EntranceName.MadraCatacombsLadderRoomEast_SouthernDoorway, RegionName.MadraCatacombsEastConnectorRoom, '48:4', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsEastConnectorRoom_NorthEasternDoorway: EntranceData(EntranceName.MadraCatacombsEastConnectorRoom_NorthEasternDoorway, RegionName.MadraCatacombsLadderRoomEast, '49:4', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsEastConnectorRoom_NorthWesternDoorway: EntranceData(EntranceName.MadraCatacombsEastConnectorRoom_NorthWesternDoorway, RegionName.MadraCatacombsRockBlockedRoom, '49:3', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRockBlockedRoom_SouthernDoorway: EntranceData(EntranceName.MadraCatacombsRockBlockedRoom_SouthernDoorway, RegionName.MadraCatacombsEastConnectorRoom, '49:2', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsEastConnectorRoom_SouthWesternDoorway: EntranceData(EntranceName.MadraCatacombsEastConnectorRoom_SouthWesternDoorway, RegionName.MadraCatacombsRockLedgeEastRidge, '49:5', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRockLedgeEastRidge_Doorway: EntranceData(EntranceName.MadraCatacombsRockLedgeEastRidge_Doorway, RegionName.MadraCatacombsEastConnectorRoom, '49:8', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsLadderRoomWest_SouthernDoorway: EntranceData(EntranceName.MadraCatacombsLadderRoomWest_SouthernDoorway, RegionName.MadraCatacombsRockLedgeWestRidge, '48:2', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRockLedgeWestRidge_NorthernDoorway: EntranceData(EntranceName.MadraCatacombsRockLedgeWestRidge_NorthernDoorway, RegionName.MadraCatacombsLadderRoomWest, '49:7', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRockLedgeEastRidge_LashRope: EntranceData(EntranceName.MadraCatacombsRockLedgeEastRidge_LashRope, RegionName.MadraCatacombsRockLedgeWestRidge),
    EntranceName.MadraCatacombsRockLedgeWestRidge_WesternDoorway: EntranceData(EntranceName.MadraCatacombsRockLedgeWestRidge_WesternDoorway, RegionName.MadraCatacombs_RuinsEntry, '49:6', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRuinsEntry_EasternDoorway: EntranceData(EntranceName.MadraCatacombsRuinsEntry_EasternDoorway, RegionName.MadraCatacombsRockLedgeWestRidge, '47:5', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRuinsEntry_RevealDoor: EntranceData(EntranceName.MadraCatacombsRuinsEntry_RevealDoor, RegionName.MadraCatacombsMainRuinsArea),
    EntranceName.MadraCatacombsMainRuins_RevealDoor: EntranceData(EntranceName.MadraCatacombsMainRuins_RevealDoor, RegionName.MadraCatacombs_RuinsEntry),
    EntranceName.MadraCatacombsMainRuins_VineClimb: EntranceData(EntranceName.MadraCatacombsMainRuins_VineClimb, RegionName.MadraCatacombsBackRuinsArea),
    EntranceName.MadraCatacombsBackRuins_ScalingTheRuins: EntranceData(EntranceName.MadraCatacombsBackRuins_ScalingTheRuins, RegionName.MadraCatacombsUpperRuinsArea),
    EntranceName.MadraCatacombsUpperRuins_DropDown: EntranceData(EntranceName.MadraCatacombsUpperRuins_DropDown, RegionName.MadraCatacombsMainRuinsArea),
    EntranceName.MadraCatacombsBackRuins_EasternRuinEntry: EntranceData(EntranceName.MadraCatacombsBackRuins_EasternRuinEntry, RegionName.MadraCatacombsRuinedBuilding_EasternHallway_EasternLedge, '47:2', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRuinedBuilding_EasternHallway_EasternLedge_SouthExit: EntranceData(EntranceName.MadraCatacombsRuinedBuilding_EasternHallway_EasternLedge_SouthExit, RegionName.MadraCatacombsBackRuinsArea, '50:7', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRuinedBuilding_EasternHallway_EasternLedge_Stairway: EntranceData(EntranceName.MadraCatacombsRuinedBuilding_EasternHallway_EasternLedge_Stairway, RegionName.MadraCatacombsRuinedBuilding_TightRidge, '50:5', ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRuinedBuilding_TightRidge_Stairway: EntranceData(EntranceName.MadraCatacombsRuinedBuilding_TightRidge_Stairway, RegionName.MadraCatacombsRuinedBuilding_EasternHallway_EasternLedge, '52:4', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRuinedBuilding_TightRidge_Doorway: EntranceData(EntranceName.MadraCatacombsRuinedBuilding_TightRidge_Doorway, RegionName.MadraCatacombsRuinedBuilding_TremorRoom, '52:3', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRuinedBuilding_TremorRoom_SouthDoorway: EntranceData(EntranceName.MadraCatacombsRuinedBuilding_TremorRoom_SouthDoorway, RegionName.MadraCatacombsRuinedBuilding_TightRidge, '52:2', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsMainRuinsArea_MainRuinEntry: EntranceData(EntranceName.MadraCatacombsMainRuinsArea_MainRuinEntry, RegionName.MadraCatacombsRuinedBuilding_EntryHall, '47:4', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRuinedBuilding_EntryHall_SouthernDoorway: EntranceData(EntranceName.MadraCatacombsRuinedBuilding_EntryHall_SouthernDoorway, RegionName.MadraCatacombsMainRuinsArea, '50:13', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRuinedBuilding_EntryHall_WesternDoorway: EntranceData(EntranceName.MadraCatacombsRuinedBuilding_EntryHall_WesternDoorway, RegionName.MadraCatacombsRuinedBuilding_CollapsedHall_SouthSide, '50:11', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRuinedBuilding_CollapsedHall_SouthDoorway: EntranceData(EntranceName.MadraCatacombsRuinedBuilding_CollapsedHall_SouthDoorway, RegionName.MadraCatacombsRuinedBuilding_EntryHall, '50:2', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRuinedBuilding_EntryHall_NorthernDoorway: EntranceData(EntranceName.MadraCatacombsRuinedBuilding_EntryHall_NorthernDoorway, RegionName.MadraCatacombsRuinedBuilding_CentralRoom, '50:9', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRuinedBuilding_CentralRoom_SouthDoor: EntranceData(EntranceName.MadraCatacombsRuinedBuilding_CentralRoom_SouthDoor, RegionName.MadraCatacombsRuinedBuilding_EntryHall, '50:3', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRuinedBuilding_EntryHall_EastStairs: EntranceData(EntranceName.MadraCatacombsRuinedBuilding_EntryHall_EastStairs, RegionName.MadraCatacombsRuinedBuilding_MainUpstairsEastArea, '50:10', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRuinedBuilding_MainUpstairsEastArea_EastStairs: EntranceData(EntranceName.MadraCatacombsRuinedBuilding_MainUpstairsEastArea_EastStairs, RegionName.MadraCatacombsRuinedBuilding_EntryHall, '51:7', ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRuinedBuilding_MainUpstairsEastArea_EastDoorway: EntranceData(EntranceName.MadraCatacombsRuinedBuilding_MainUpstairsEastArea_EastDoorway, RegionName.MadraCatacombsRuinedBuilding_EastBedroom, '51:6', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRuinedBuilding_EastBedroom_Doorway: EntranceData(EntranceName.MadraCatacombsRuinedBuilding_EastBedroom_Doorway, RegionName.MadraCatacombsRuinedBuilding_MainUpstairsEastArea, '51:4', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRuinedBuilding_EntryHall_EasternDoorway: EntranceData(EntranceName.MadraCatacombsRuinedBuilding_EntryHall_EasternDoorway, RegionName.MadraCatacombsRuinedBuilding_EasternHallway_WesternLedge, '50:12', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRuinedBuilding_EasternHallway_WesternLedge_SouthDoor: EntranceData(EntranceName.MadraCatacombsRuinedBuilding_EasternHallway_WesternLedge_SouthDoor, RegionName.MadraCatacombsRuinedBuilding_EntryHall, '50:8', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRuinedBuilding_EasternHallway_WesternLedge_DownStairway: EntranceData(EntranceName.MadraCatacombsRuinedBuilding_EasternHallway_WesternLedge_DownStairway, RegionName.MadraCatacombsRuinedBuilding_LockedRoom, '50:6', ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRuinedBuilding_LockedRoom_Stairway: EntranceData(EntranceName.MadraCatacombsRuinedBuilding_LockedRoom_Stairway, RegionName.MadraCatacombsRuinedBuilding_EasternHallway_WesternLedge, '52:1', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRuinedBuilding_EasternHallway_WesternLedge_UpStairway: EntranceData(EntranceName.MadraCatacombsRuinedBuilding_EasternHallway_WesternLedge_UpStairway, RegionName.MadraCatacombsRuinedBuilding_LongHallway, '50:4', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRuinedBuilding_LongHallway_EastDownStairway: EntranceData(EntranceName.MadraCatacombsRuinedBuilding_LongHallway_EastDownStairway, RegionName.MadraCatacombsRuinedBuilding_EasternHallway_WesternLedge, '51:2', ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRuinedBuilding_LongHallway_WestDownStairway: EntranceData(EntranceName.MadraCatacombsRuinedBuilding_LongHallway_WestDownStairway, RegionName.MadraCatacombsRuinedBuilding_CollapsedHall_NorthSide, '51:1', ERTestGroups.DOWN | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRuinedBuilding_CollapsedHall_NorthSide_Stairway: EntranceData(EntranceName.MadraCatacombsRuinedBuilding_CollapsedHall_NorthSide_Stairway, RegionName.MadraCatacombsRuinedBuilding_LongHallway, '50:1', ERTestGroups.UP | ERTestGroups.SCREEN_EDGE_WALK),

    EntranceName.MadraCatacombsUpperRuinsArea_RuinsUpperDoorway: EntranceData(EntranceName.MadraCatacombsUpperRuinsArea_RuinsUpperDoorway, RegionName.MadraCatacombsRuinedBuilding_MainUpstairsWestArea, '47:1', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRuinedBuilding_MainUpstairsWestArea_SouthDoorway: EntranceData(EntranceName.MadraCatacombsRuinedBuilding_MainUpstairsWestArea_SouthDoorway, RegionName.MadraCatacombsUpperRuinsArea, '51:8', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRuinedBuilding_MainUpstairsWestArea_NorthDoorway: EntranceData(EntranceName.MadraCatacombsRuinedBuilding_MainUpstairsWestArea_NorthDoorway, RegionName.MadraCatacombsRuinedBuilding_WestBedroom, '51:5', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraCatacombsRuinedBuilding_WestBedroom_Doorway: EntranceData(EntranceName.MadraCatacombsRuinedBuilding_WestBedroom_Doorway, RegionName.MadraCatacombsRuinedBuilding_MainUpstairsWestArea, '51:3', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),


    #Madra Drawbridge
    EntranceName.Overworld_To_MadraDrawbridge_SouthSide: EntranceData(EntranceName.Overworld_To_MadraDrawbridge_SouthSide, RegionName.MadraDrawBridge, '2:10', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceName.Overworld_To_MadraDrawbridge_NorthSide: EntranceData(EntranceName.Overworld_To_MadraDrawbridge_NorthSide, RegionName.MadraDrawBridge, '2:11', ERTestGroups.SOUTH |ERTestGroups.OW_WALK),
    EntranceName.MadraDrawbridge_South_To_Overworld: EntranceData(EntranceName.MadraDrawbridge_South_To_Overworld, RegionName.Indra_SouthernIndra, '53:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MadraDrawbridge_North_To_Overworld: EntranceData(EntranceName.MadraDrawbridge_North_To_Overworld, RegionName.Indra_MadraDrawBridgeArea, '53:2', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),

    #Osenia
    #Osenia Cliffs
    EntranceName.Overworld_To_OseniaCliffs_WestSide: EntranceData(EntranceName.Overworld_To_OseniaCliffs_WestSide, RegionName.OseniaCliffs, '2:12', ERTestGroups.EAST | ERTestGroups.OW_WALK),
    EntranceName.Overworld_To_OseniaCliffs_EastSide: EntranceData(EntranceName.Overworld_To_OseniaCliffs_EastSide, RegionName.OseniaCliffs, '2:13', ERTestGroups.WEST | ERTestGroups.OW_WALK),
    EntranceName.OseniaCliffs_West_To_Overworld: EntranceData(EntranceName.OseniaCliffs_West_To_Overworld, RegionName.Indra_MadraDrawBridgeArea, '54:1', ERTestGroups.WEST | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.OseniaCliffs_East_To_Overworld: EntranceData(EntranceName.OseniaCliffs_East_To_Overworld, RegionName.Oseania_SouthWesternOsenia, '54:2', ERTestGroups.EAST | ERTestGroups.SCREEN_EDGE_WALK),

    #Mikasalla
    EntranceName.Overworld_To_Mikasalla: EntranceData(EntranceName.Overworld_To_Mikasalla, RegionName.Mikasalla, '2:14', ERTestGroups.WEST | ERTestGroups.OW_WALK),
    EntranceName.Mikasalla_To_Overworld: EntranceData(EntranceName.Mikasalla_To_Overworld, RegionName.Oseania_SouthWesternOsenia, '55:6', ERTestGroups.EAST | ERTestGroups.SCREEN_EDGE_WALK),

    #Osenia Cavern
    EntranceName.Overworld_To_OseniaCavern: EntranceData(EntranceName.Overworld_To_OseniaCavern, RegionName.OseniaCavern, '2:82', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceName.OseniaCavern_To_Overworld: EntranceData(EntranceName.OseniaCavern_To_Overworld, RegionName.Oseania_SouthWesternOsenia, '276:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),

    #Garoh
    EntranceName.Overworld_To_Garoh: EntranceData(EntranceName.Overworld_To_Garoh, RegionName.Garoh, '2:15', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceName.Garoh_To_Overworld: EntranceData(EntranceName.Garoh_To_Overworld, RegionName.Oseania_SouthWesternOsenia, '61:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),

    #Airs Rock
    EntranceName.Overworld_To_AirsRock: EntranceData(EntranceName.Overworld_To_AirsRock, RegionName.AirsRock, '2:16', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceName.AirsRock_To_Overworld: EntranceData(EntranceName.AirsRock_To_Overworld, RegionName.Oseania_SouthWesternOsenia, '82:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),

    #Yampi Desert
    EntranceName.YampiDesertBack_To_Overworld_Garoh: EntranceData(EntranceName.YampiDesertBack_To_Overworld_Garoh, RegionName.Oseania_SouthWesternOsenia, '75:2', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.YampDesertFront_To_Overworld: EntranceData(EntranceName.YampDesertFront_To_Overworld, RegionName.Oseania_SouthWesternOsenia, '67:1', ERTestGroups.WEST | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.YampiDesertBack_To_Overworld_Alhafra: EntranceData(EntranceName.YampiDesertBack_To_Overworld_Alhafra, RegionName.Oseania_AlhafraArea, '74:2', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),

    #Alhafra
    EntranceName.Overworld_To_Alhafra: EntranceData(EntranceName.Overworld_To_Alhafra, RegionName.Alhafra, '2:20', ERTestGroups.NORTH | ERTestGroups.OW_WALK),
    EntranceName.Alhafra_To_Overworld: EntranceData(EntranceName.Alhafra_To_Overworld, RegionName.Oseania_AlhafraArea, '95:9', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
 
    #Gondowan Cliffs
    EntranceName.GondowanCliffs_East_To_Overworld: EntranceData(EntranceName.GondowanCliffs_East_To_Overworld, RegionName.Indra_SouthernIndra, '102:2', ERTestGroups.EAST | ERTestGroups.SCREEN_EDGE_WALK),

    #Gondowan
    EntranceName.GondowanCliffs_West_To_Overworld: EntranceData(EntranceName.GondowanCliffs_West_To_Overworld, RegionName.Gondowan_SouthernGondowan, '102:1', ERTestGroups.WEST | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.Naribwe_South_To_Overworld: EntranceData(EntranceName.Naribwe_South_To_Overworld, RegionName.Gondowan_SouthernGondowan, '105:6', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.Naribwe_North_To_Overworld: EntranceData(EntranceName.Naribwe_North_To_Overworld, RegionName.Gondowan_SouthernGondowan, '105:7', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KibomboMountains_South_To_Overworld: EntranceData(EntranceName.KibomboMountains_South_To_Overworld, RegionName.Gondowan_SouthernGondowan, '108:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KibomboMountains_NorthWest_To_Overworld: EntranceData(EntranceName.KibomboMountains_NorthWest_To_Overworld, RegionName.Gondowan_CentralGondowan, '107:1', ERTestGroups.WEST | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.Kibombo_To_Overworld: EntranceData(EntranceName.Kibombo_To_Overworld, RegionName.Gondowan_CentralGondowan, '113:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),


    #Eastern Sea
    EntranceName.Overworld_Indra_North_To_EasternSea: EntranceData(EntranceName.Overworld_Indra_North_To_EasternSea, RegionName.EasternSea),
    EntranceName.Overworld_Indra_South_To_EasternSea: EntranceData(EntranceName.Overworld_Indra_South_To_EasternSea, RegionName.EasternSea),
    EntranceName.Overworld_Oseania_AlhafraArea_To_EasternSea: EntranceData(EntranceName.Overworld_Oseania_AlhafraArea_To_EasternSea, RegionName.EasternSea),
    EntranceName.Overworld_Gondowan_Central_To_EasternSea: EntranceData(EntranceName.Overworld_Gondowan_Central_To_EasternSea, RegionName.EasternSea),
    EntranceName.Overworld_Gondowan_South_To_EasternSea: EntranceData(EntranceName.Overworld_Gondowan_South_To_EasternSea, RegionName.EasternSea),
    EntranceName.Overworld_WestIndraIslet_To_EasternSea: EntranceData(EntranceName.Overworld_WestIndraIslet_To_EasternSea, RegionName.EasternSea),
    EntranceName.Overworld_EastTundariaIslet_To_EasternSea: EntranceData(EntranceName.Overworld_EastTundariaIslet_To_EasternSea, RegionName.EasternSea),
    EntranceName.Overworld_NorthOseniaIslet_To_EasternSea: EntranceData(EntranceName.Overworld_NorthOseniaIslet_To_EasternSea, RegionName.EasternSea),
    EntranceName.Overworld_SouthEastAngaraIslet_To_EasternSea: EntranceData(EntranceName.Overworld_SouthEastAngaraIslet_To_EasternSea, RegionName.EasternSea),
    EntranceName.Overworld_SeaOfTimeIslet_To_EasternSea: EntranceData(EntranceName.Overworld_SeaOfTimeIslet_To_EasternSea, RegionName.EasternSea),
    EntranceName.Overworld_ApojiiIslands_To_EasternSea: EntranceData(EntranceName.Overworld_ApojiiIslands_To_EasternSea, RegionName.EasternSea),
    EntranceName.Overworld_AquaRock_To_EasternSea: EntranceData(EntranceName.Overworld_AquaRock_To_EasternSea, RegionName.EasternSea),
    EntranceName.Overworld_Izumo_To_EasternSea: EntranceData(EntranceName.Overworld_Izumo_To_EasternSea, RegionName.EasternSea),
    EntranceName.Overworld_TreasureIsland_To_EasternSea: EntranceData(EntranceName.Overworld_TreasureIsland_To_EasternSea, RegionName.EasternSea),
    EntranceName.Overworld_Tundaria_To_EasternSea: EntranceData(EntranceName.Overworld_Tundaria_To_EasternSea, RegionName.EasternSea),
    EntranceName.Overworld_SEAngara_To_EasternSea: EntranceData(EntranceName.Overworld_SEAngara_To_EasternSea, RegionName.EasternSea),
    EntranceName.Overworld_SouthernAngara_To_EasternSea: EntranceData(EntranceName.Overworld_SouthernAngara_To_EasternSea, RegionName.EasternSea),
    EntranceName.Overworld_SouthEastOsenia_To_EasternSea: EntranceData(EntranceName.Overworld_SouthEastOsenia_To_EasternSea, RegionName.EasternSea),

    EntranceName.Overworld_EasternSea_To_Indra_North: EntranceData(EntranceName.Overworld_EasternSea_To_Indra_North, RegionName.Indra_NorthernIndra),
    EntranceName.Overworld_EasternSea_To_Indra_South: EntranceData(EntranceName.Overworld_EasternSea_To_Indra_South, RegionName.Indra_SouthernIndra),
    EntranceName.Overworld_EasternSea_To_Osenia_AlhafraArea: EntranceData(EntranceName.Overworld_EasternSea_To_Osenia_AlhafraArea, RegionName.Oseania_AlhafraArea),
    EntranceName.Overworld_EasternSea_To_Gondowan_Central: EntranceData(EntranceName.Overworld_EasternSea_To_Gondowan_Central, RegionName.Gondowan_CentralGondowan),
    EntranceName.Overworld_EasternSea_To_Gondowan_South: EntranceData(EntranceName.Overworld_EasternSea_To_Gondowan_South, RegionName.Gondowan_SouthernGondowan),
    EntranceName.Overworld_EasternSea_To_WestIndraIslet: EntranceData(EntranceName.Overworld_EasternSea_To_WestIndraIslet, RegionName.Overworld_WestIndraIslet),
    EntranceName.Overworld_EasternSea_To_EastTundariaIslet: EntranceData(EntranceName.Overworld_EasternSea_To_EastTundariaIslet, RegionName.Overworld_EastTundariaIslet),
    EntranceName.Overworld_EasternSea_To_NorthOseniaIslet: EntranceData(EntranceName.Overworld_EasternSea_To_NorthOseniaIslet, RegionName.Overworld_NorthOseniaIslet),
    EntranceName.Overworld_EasternSea_To_SouthEastAngaraIslet: EntranceData(EntranceName.Overworld_EasternSea_To_SouthEastAngaraIslet, RegionName.Overworld_SouthEastAngaraIslet),
    EntranceName.Overworld_EasternSea_To_SeaOfTimeIslet: EntranceData(EntranceName.Overworld_EasternSea_To_SeaOfTimeIslet, RegionName.Overworld_SeaOfTimeIslet),
    EntranceName.Overworld_EasternSea_To_ApojiiIslands: EntranceData(EntranceName.Overworld_EasternSea_To_ApojiiIslands, RegionName.Overworld_ApojiiIslands),
    EntranceName.Overworld_EasternSea_To_AquaRock: EntranceData(EntranceName.Overworld_EasternSea_To_AquaRock, RegionName.Overworld_AquaRock),
    EntranceName.Overworld_EasternSea_To_Izumo: EntranceData(EntranceName.Overworld_EasternSea_To_Izumo, RegionName.Overworld_Izumo),
    EntranceName.Overworld_EasternSea_To_TreasureIsland: EntranceData(EntranceName.Overworld_EasternSea_To_TreasureIsland, RegionName.Overworld_TreasureIsland),
    EntranceName.Overworld_EasternSea_To_Tundaria: EntranceData(EntranceName.Overworld_EasternSea_To_Tundaria, RegionName.Overworld_Tundaria),
    EntranceName.Overworld_EasternSea_To_SEAngara: EntranceData(EntranceName.Overworld_EasternSea_To_SEAngara, RegionName.Overworld_SouthEasternAngara),
    EntranceName.Overworld_EasternSea_To_SouthernAngara: EntranceData(EntranceName.Overworld_EasternSea_To_SouthernAngara, RegionName.Overworld_SouthernAngara),
    EntranceName.Overworld_EasternSea_To_SouthEastOsenia: EntranceData(EntranceName.Overworld_EasternSea_To_SouthEastOsenia, RegionName.Overworld_SouthEasternOsenia),

    EntranceName.WestIndraIslet_To_Overworld: EntranceData(EntranceName.WestIndraIslet_To_Overworld, RegionName.Overworld_WestIndraIslet, '131:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.EastTundariaIslet_To_Overworld: EntranceData(EntranceName.EastTundariaIslet_To_Overworld, RegionName.Overworld_EastTundariaIslet, '132:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.NorthOseniaIslet_To_Overworld: EntranceData(EntranceName.NorthOseniaIslet_To_Overworld, RegionName.Overworld_NorthOseniaIslet, '133:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.SouthEastAngaraIslet_To_Overworld: EntranceData(EntranceName.SouthEastAngaraIslet_To_Overworld, RegionName.Overworld_SouthEastAngaraIslet, '134:10', ERTestGroups.WEST | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.SeaOfTimeIslet_To_Overworld: EntranceData(EntranceName.SeaOfTimeIslet_To_Overworld, RegionName.Overworld_SeaOfTimeIslet, '135:1', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.ApojiiIslands_To_Overworld: EntranceData(EntranceName.ApojiiIslands_To_Overworld, RegionName.Overworld_ApojiiIslands, '154:1', ERTestGroups.WEST | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.AquaRock_To_Overworld: EntranceData(EntranceName.AquaRock_To_Overworld, RegionName.Overworld_AquaRock, '158:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.Izumo_To_Overworld: EntranceData(EntranceName.Izumo_To_Overworld, RegionName.Overworld_Izumo, '171:1', ERTestGroups.WEST | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.GaiaRock_To_Overworld: EntranceData(EntranceName.GaiaRock_To_Overworld, RegionName.Overworld_Izumo, '174:5', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.TreasureIsland_To_Overworld: EntranceData(EntranceName.TreasureIsland_To_Overworld, RegionName.Overworld_TreasureIsland, '298:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.TundariaTower_To_Overworld: EntranceData(EntranceName.TundariaTower_To_Overworld, RegionName.Overworld_Tundaria, '206:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.AnkohlRuins_To_Overworld: EntranceData(EntranceName.AnkohlRuins_To_Overworld, RegionName.Overworld_SouthEasternAngara, '195:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.Champa_To_Overworld: EntranceData(EntranceName.Champa_To_Overworld, RegionName.Overworld_SouthernAngara, '182:9', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.YallamSouth_To_Overworld: EntranceData(EntranceName.YallamSouth_To_Overworld, RegionName.Overworld_SouthEasternOsenia, '139:10', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.YallamNorth_To_Overworld: EntranceData(EntranceName.YallamNorth_To_Overworld, RegionName.Overworld_NorthEasternOsenia, '139:11', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.TaopoSwamp_To_Overworld: EntranceData(EntranceName.TaopoSwamp_To_Overworld, RegionName.Overworld_NorthEasternOsenia, '143:1', ERTestGroups.WEST | ERTestGroups.SCREEN_EDGE_WALK),

    #Western Sea
    EntranceName.Overworld_WesternSea_To_SouthWestAttekaIslet: EntranceData(EntranceName.Overworld_WesternSea_To_SouthWestAttekaIslet, RegionName.Overworld_SouthWestAttekaIslet),
    EntranceName.Overworld_WesternSea_To_KaltIsland: EntranceData(EntranceName.Overworld_WesternSea_To_KaltIsland, RegionName.Overworld_KaltIsland),
    EntranceName.Overworld_WesternSea_To_WestGondowan: EntranceData(EntranceName.Overworld_WesternSea_To_WestGondowan, RegionName.Gondowan_WesternGondowan),
    EntranceName.Overworld_WesternSea_To_WesternAngara: EntranceData(EntranceName.Overworld_WesternSea_To_WesternAngara, RegionName.Overworld_WesternAngara),
    EntranceName.Overworld_WesternSea_To_NeHesperia: EntranceData(EntranceName.Overworld_WesternSea_To_NeHesperia, RegionName.Overworld_NeHesperia),
    EntranceName.Overworld_WesternSea_To_WestHesperia: EntranceData(EntranceName.Overworld_WesternSea_To_WestHesperia, RegionName.Overworld_WesternHesperia),
    EntranceName.Overworld_WesternSea_To_CentralHesperia: EntranceData(EntranceName.Overworld_WesternSea_To_CentralHesperia, RegionName.Overworld_CentralHesperia),
    EntranceName.Overworld_WesternSea_To_WesternAtteka: EntranceData(EntranceName.Overworld_WesternSea_To_WesternAtteka, RegionName.Overworld_WesternAtteka),
    EntranceName.Overworld_WesternSea_To_SouthernAtteka: EntranceData(EntranceName.Overworld_WesternSea_To_SouthernAtteka, RegionName.Overworld_SouthernAtteka),

    EntranceName.Overworld_SouthWestAttekaIslet_To_WesternSea: EntranceData(EntranceName.Overworld_SouthWestAttekaIslet_To_WesternSea, RegionName.WesternSea),
    EntranceName.Overworld_KaltIsland_To_WesternSea: EntranceData(EntranceName.Overworld_KaltIsland_To_WesternSea, RegionName.WesternSea),
    EntranceName.Overworld_WestGondowan_To_WesternSea: EntranceData(EntranceName.Overworld_WestGondowan_To_WesternSea, RegionName.WesternSea),
    EntranceName.Overworld_WesternAngara_To_WesternSea: EntranceData(EntranceName.Overworld_WesternAngara_To_WesternSea, RegionName.WesternSea),
    EntranceName.Overworld_WesternHesperia_To_WesternSea: EntranceData(EntranceName.Overworld_WesternHesperia_To_WesternSea, RegionName.WesternSea),
    EntranceName.Overworld_CentralHesperia_To_WesternSea: EntranceData(EntranceName.Overworld_CentralHesperia_To_WesternSea, RegionName.WesternSea),
    EntranceName.Overworld_SouthernAtteka_To_WesternSea: EntranceData(EntranceName.Overworld_SouthernAtteka_To_WesternSea, RegionName.WesternSea),

    EntranceName.SouthWestAttekaIslet_To_Overworld: EntranceData(EntranceName.SouthWestAttekaIslet_To_Overworld, RegionName.Overworld_SouthWestAttekaIslet, '221:1', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.KaltIsland_To_Overworld: EntranceData(EntranceName.KaltIsland_To_Overworld, RegionName.Overworld_KaltIsland, '219:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.GondowanSettlement_To_Overworld: EntranceData(EntranceName.GondowanSettlement_To_Overworld, RegionName.Gondowan_WesternGondowan, '213:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MagmaRock_To_Overworld: EntranceData(EntranceName.MagmaRock_To_Overworld, RegionName.Gondowan_WesternGondowan, '223:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.Loho_To_Overworld: EntranceData(EntranceName.Loho_To_Overworld, RegionName.Overworld_WesternAngara, '266:1', ERTestGroups.WEST | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.AngaraCavern_To_Overworld: EntranceData(EntranceName.AngaraCavern_To_Overworld, RegionName.Overworld_WesternAngara, '278:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.HesperiaSettlement_To_Overworld: EntranceData(EntranceName.HesperiaSettlement_To_Overworld, RegionName.Overworld_WesternHesperia, '216:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.ShamanVillageCave_SouthWest_To_Overworld: EntranceData(EntranceName.ShamanVillageCave_SouthWest_To_Overworld, RegionName.Overworld_CentralHesperia, '240:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.ShamanVillageCave_East_To_Overworld: EntranceData(EntranceName.ShamanVillageCave_East_To_Overworld, RegionName.Overworld_ShamanHesperia, '240:10', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.ShamanVillage_To_Overworld: EntranceData(EntranceName.ShamanVillage_To_Overworld, RegionName.Overworld_ShamanHesperia, '242:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.AttekaCavern_To_Overworld: EntranceData(EntranceName.AttekaCavern_To_Overworld, RegionName.Overworld_SouthernAtteka, '277:5', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.AttekaInlet_To_Overworld_Land: EntranceData(EntranceName.AttekaInlet_To_Overworld_Land, RegionName.Overworld_CentralAtteka, '235:2', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.Contigo_To_Overworld: EntranceData(EntranceName.Contigo_To_Overworld, RegionName.Overworld_CentralAtteka, '236:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.JupiterLighthouse_To_Overworld: EntranceData(EntranceName.JupiterLighthouse_To_Overworld, RegionName.Overworld_CentralAtteka, '251:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.Prox_To_Overworld_SouthSide: EntranceData(EntranceName.Prox_To_Overworld_SouthSide, RegionName.Overworld_Lower_NorthernReaches, '269:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.Prox_To_Overworld_NorthSide: EntranceData(EntranceName.Prox_To_Overworld_NorthSide, RegionName.Overworld_Upper_NorthernReaches, '271:3', ERTestGroups.NORTH | ERTestGroups.SCREEN_EDGE_WALK),
    EntranceName.MarsLighthouse_To_Overworld: EntranceData(EntranceName.MarsLighthouse_To_Overworld, RegionName.Overworld_Upper_NorthernReaches, '279:1', ERTestGroups.SOUTH | ERTestGroups.SCREEN_EDGE_WALK),



    EntranceName.MadraToLemurianShip: EntranceData(EntranceName.MadraToLemurianShip, RegionName.Lemurian_Ship),
    EntranceName.YampiDesertFrontToYampiDesertBack: EntranceData(EntranceName.YampiDesertFrontToYampiDesertBack, RegionName.YampiDesertBack),
    EntranceName.YampiDesertBackToYampiDesertCave: EntranceData(EntranceName.YampiDesertBackToYampiDesertCave, RegionName.YampiDesertCave),
    EntranceName.AlhafraToAlhafraCave: EntranceData(EntranceName.AlhafraToAlhafraCave, RegionName.AlhafraCave),
    EntranceName.KibomboToGabombaStatue: EntranceData(EntranceName.KibomboToGabombaStatue, RegionName.GabombaStatue),
    EntranceName.GabombaStatueToGabombaCatacombs: EntranceData(EntranceName.GabombaStatueToGabombaCatacombs, RegionName.GabombaCatacombs),
    EntranceName.EasternSeaToSeaOfTime: EntranceData(EntranceName.EasternSeaToSeaOfTime, RegionName.SeaOfTime),
    EntranceName.EasternSeaToWesternSea: EntranceData(EntranceName.EasternSeaToWesternSea, RegionName.WesternSea),
    EntranceName.SeaOfTimeIsletToIsletCave: EntranceData(EntranceName.SeaOfTimeIsletToIsletCave, RegionName.IsletCave),
    EntranceName.TreasureIslandToTreasureIsland_Grindstone: EntranceData(EntranceName.TreasureIslandToTreasureIsland_Grindstone, RegionName.TreasureIsland_Grindstone),
    EntranceName.TreasureIsland_GrindstoneToTreasureIsland_PostReunion: EntranceData(EntranceName.TreasureIsland_GrindstoneToTreasureIsland_PostReunion, RegionName.TreasureIsland_PostReunion),
    EntranceName.TundariaTowerToTundariaTower_Parched: EntranceData(EntranceName.TundariaTowerToTundariaTower_Parched, RegionName.TundariaTower_Parched),
    EntranceName.AnkohlRuinsToAnkohlRuins_Sand: EntranceData(EntranceName.AnkohlRuinsToAnkohlRuins_Sand, RegionName.AnkohlRuins_Sand),
    EntranceName.SeaOfTimeToLemuria: EntranceData(EntranceName.SeaOfTimeToLemuria, RegionName.Lemuria),
    EntranceName.LemuriaToShipRevisit: EntranceData(EntranceName.LemuriaToShipRevisit, RegionName.Lemurian_Ship_Revisit),
    EntranceName.WesternSeaToAttekaInlet: EntranceData(EntranceName.WesternSeaToAttekaInlet, RegionName.AttekaInlet),
    EntranceName.WesternSeaToProx: EntranceData(EntranceName.WesternSeaToProx, RegionName.Overworld_Lower_NorthernReaches),
    EntranceName.AttekaInletToShipRevisit: EntranceData(EntranceName.AttekaInletToShipRevisit, RegionName.Lemurian_Ship_Revisit),
    EntranceName.ContigoToAnemosInnerSanctum: EntranceData(EntranceName.ContigoToAnemosInnerSanctum, RegionName.AnemosSanctum),
    EntranceName.ContigoToReunion: EntranceData(EntranceName.ContigoToReunion, RegionName.Reunion),
    EntranceName.MagmaRockToMagmaRockInterior: EntranceData(EntranceName.MagmaRockToMagmaRockInterior, RegionName.MagmaRockInterior),
    EntranceName.Overworld_HighNorthenReaches_To_MarsLighthouse: EntranceData(EntranceName.Overworld_HighNorthenReaches_To_MarsLighthouse, RegionName.MarsLighthouse),
    EntranceName.MarsLighthouseToMarsLighthouse_Activated: EntranceData(EntranceName.MarsLighthouseToMarsLighthouse_Activated, RegionName.MarsLighthouse_Activated)
}


def create_vanilla_connections(multiworld: MultiWorld, player: int):
    for name, connection in vanilla_connections.items():
        entrance = multiworld.get_entrance(connection.source_entrance, player)
        entrance.randomization_group = connection.rando_group
        entrance.randomization_type = connection.rando_type
        target = multiworld.get_region(connection.target, player)

        entrance.connect(target)